### ISSUE TITLE
Better performance analysis / debugging tools

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1026]
This is a preliminary tracking issue for a few projects I would like to see at some point.

It is going to be important that we have better tools for debugging performance issues, as well as things like event and update flow, and I want to record a few ideas here for concrete approaches to this.

## tracing:

There's an issue for this (#102) but I want to also mention it here; I would like to integrate trace recording and saving into druid, based on the `xi-trace` crate that we used in xi-editor; this is a high-performance probe-based tracing tool that lets you do things like record the duration of some operation, or the instant that some event occurs, and then to view this information using chrome's built in tracing tools.

This has the very nice quality that it is low overhead, and can be running constantly; we use a ring buffer to store some number of most recent events (~100k) and then at any point we can dump that to a file for review.

## Detailed event debugging 

A second approach for this stuff would be to have a feature flag that turns on fine-grained event tracing. The idea here is to track the propagation of every event and every update, including potentially every mutation of `Data`, to track down things like what events are causing unexpected cascades of invalidation, or where in  the widget graph a particular update is being suppressed; these are the sorts of problems I've needed to track down in `Runebender`, and its been a source of headaches.

This would work via the current `WidgetPod` + `BaseState` + `merge_up` mechanism; we would have some event log, and each `WidgetPod` would record whether it saw an event, whether it recursed, and whether it changed the data, and this would be passed back up and stored after each event.

## Bonus: an interactive event debugger

An issue with the above approach is that we end up with a whole lot of data but no real way of sifting through it. What would be extra amazing would be if we had the ability to open an 'event debugger window'; this would be running in the same process as your application, and would record each event that occurs; you could 'pause' your application and then step through the list of events, and we could draw on top of your application to show the widgets involved at various points.

This is all a reasonable amount of work (especially the last item) but on a long enough time frame I think that we will want to be building tools like these.

**Comment by xStrom** [comment]
On the same topic, it would be nice to have some sort of list of pre-existing analysis tools that can be really useful. I saw [Superluminal](https://superluminal.eu/rust/) mentioned on zulip and although I haven't tried it yet it looks great on the surface. I would definitely be interested in knowing about other similar tools for Rust performance analysis.

**Comment by ratmice** [comment]
I think its also worth considering dtrace/sdt style probes, IIUC option 1 is based upon a branch/atomic bool for enabling/disabling tracing.

While implementations like [rust-libprobe](https://github.com/cuviper/rust-libprobe) essentially leave  a `nop` instructions in the binary, and then use `ptrace` to rewrite this `nop` into branching to tracing when a probe is enabled (or something).
Given the recent progress on rusts inline assembly support which has at least a chance of stablization.  I think it is worth considering.

So I think another option for an implementation of **detailed event debugging** is to have a single feature that initially requires nightly. That could potentially be made default if inline-assembly is ever stablized. I'm not familiar enough with `xi-trace` to know whether or not it's possible to be made compatible with the `rust-libprobe` probe mechanism via a feature in `xi-trace`.

anyhow my feeling at least is that once inline-asm is stablized, the tracing ecosystem should probably change to more efficient probes, and its worthwhile to prepare for it in advance?

**Comment by cmyr** [comment]
on macOS I use [`cargo-instruments`](https://crates.io/crates/cargo-instruments) all the time, and find it very useful; it's dtrace under the hood. Having some nice mechanism for inserting dtrace/ptrace probes does sound interesting, but I'm also pretty happy with `xi-trace` as a pretty immediate solution.

**Comment by smmalis37** [comment]
In terms of external analysis tools I've had a lot of experience with [WPA](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer). As the name implies it's Windows exclusive, and its not the most user friendly until you learn how to navigate it. However you can get a lot of system-level data that you can line up side-by-side with your own events (like message pump delays, context switches, disk accesses, etc). The logging backend would need to support output to ETW for this to be possible though, no idea if anything like that exists currently.

**Comment by raphlinus** [comment]
https://github.com/microsoft/rust_win_etw exists. I do most of my work on Windows so would find this useful. One thing I haven't investigated is whether we can do a simple, friendly API for emitting tracing events that can ultimately output either Chromium trace JSON (like xi-trace) or to ETW.

**Comment by PoignardAzur** [comment]
I think we can probably close this?

We've added a dependency on tracing which already does most of the work mentioned in the issue. The suggested idea of having a way to open the event timeline in a window is really cool, and I'm planning to work on something similar, but it's an entire project in itself.
