### ISSUE TITLE
Widgets for dragging / resizing windows

### ISSUE THREAD

**Issue by rhzk** [linebender/druid#1038]
Widgets for dragging / resizing windows.

I could work on this after we are done with window logic, creating a issue as a reminder.

**Comment by cmyr** [comment]
I'm not 100% clear on what this would mean; do you mean a widget that can be resized within a window?

**Comment by xStrom** [comment]
I think the goal is to have a widget that acts as the window border. Then you can have a borderless window that can still be resized.

**Comment by cmyr** [comment]
right. I wonder if we want a widget for this, or some other mechanism?

**Comment by xStrom** [comment]
I think we definitely want a non-widget way to do this. I'm less sure that we want an official widget implementing that mechanic, because it's pretty niche.

**Comment by rhzk** [comment]
What I was thinking with this is a custom titlebar where you can drag the window, maximize button etc.
I have also seen something like this (Very bad drawing) in the bottom corner of applications as a "resize icon":

![image](https://user-images.githubusercontent.com/45132707/86186727-14390580-bb3a-11ea-8004-354fe8c2c82c.png)

**Comment by blemelin** [comment]
I know this is an old issue, but I would be interested in helping out. 

Right now, when using [show_titlebar](https://docs.rs/druid/0.7.0/druid/struct.WindowDesc.html#method.show_titlebar) to hide the title bar, on the *gtk* platform, the window is no longer resizeable (which is normal considering that it calls [gtk-window-set-decorated](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-decorated) internally).

The change I propose is to implement manual window resizing in the *gtk* `WindowHandle` implementation. This would be activated or deactivated using the [resizable](https://docs.rs/druid/0.7.0/druid/struct.WindowDesc.html#method.resizable) method. The way I propose to do it is to call [gtk-window-begin-resize-drag](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-begin-resize-drag) when the mouse down event is fired near a window border. 

Of course, when the decorations are on, this manual window resize would be deactivated.

I'll submit a PR if you are interested.
