### ISSUE TITLE
Container::rounded takes f64 directly

### ISSUE THREAD

**Issue by binomial0** [linebender/druid#1052]
The method [Container::rounded](https://docs.rs/druid/0.6.0/druid/widget/struct.Container.html#method.rounded) takes a `f64` directly, instead of an `impl Into<KeyOrValue<f64>>`. This seems to be an oversight. Fixing it would allow customisation through `Env` keys, like with the other visual properties of `Container`.

**Comment by ForLoveOfCats** [comment]
That does indeed seem like an oversight. Fixing this would be quite simple and shouldn't break existing code so it would be a great way to get involved if you would like to :)

**Comment by binomial0** [comment]
Seems like a good idea. I'll see if I have time this week to implement it, I think I will.
