### ISSUE TITLE
Updating child widgets?

### ISSUE THREAD

**Issue by timothyhollabaugh** [linebender/druid#1073]
I have a custom widget that has a tree of child widgets, where the data of the child widgets is made up of both the widget's data and some of the widget's internal state. The `event`, `lifecycle`, `update`, `layout`, and `paint` methods all handle assembling these together.

In particular, the `event` method looks like this:

```rust
fn event(&mut self, ctx: &mut EventCtx, event: &Event, tools: &mut ToolTable, env: &Env) {
    let mut data = (self.state.to_owned(), tools.to_owned());

    self.widgets.event(ctx, event, &mut data, env);

    let (new_state, new_tools) = data;

    if !new_state.same(&self.state) {
        self.state = new_state;
    }

    if !new_tools.same(&new_tools) {
        *tools = new_tools;
    }
}
```

This works great, except that when the widget's internal state changes, the children do not get updated.

Does it make sense to add a `request_update` method on `EventCtx`? Or is there a better way to do this?

**Comment by rhzk** [comment]
Hi, you can use WidgetPod for this. I recommend you take a look at:
https://github.com/linebender/druid/blob/master/druid/src/widget/scroll.rs#L110
https://github.com/linebender/druid/blob/master/druid/src/widget/scroll.rs#L442
https://github.com/linebender/druid/blob/master/druid/src/widget/scroll.rs#L470

**Comment by timothyhollabaugh** [comment]
I'll take a look. I changed up my UI to avoid this problem, so I'll close this issue.

**Comment by raphlinus** [comment]
I'm going to reopen this, as I think a `request_update` method on `EventCtx` is something we really should have. I'll try to make a PR for it.

**Comment by cmyr** [comment]
uh, thinking about this my first thought is that you should be responsible for calling `update` in your own `update` call? If you're a container you are responsible for forwarding all calls to children as needed.

**Comment by raphlinus** [comment]
Yes, we discussed this on Zulip and the consensus is to just have the `request_update` call for the parent.
