### ISSUE TITLE
Widget customization

### ISSUE THREAD

**Issue by sysint64** [linebender/druid#1078]
Hello there, I would like to suggest a new way of building default widgets, the current approach is to create full-featured widgets like buttons and text boxes. Still, it's harder to create your widget that also should have some text editing features. It can be impossible to customize the current widget kit, e.g., button at the moment non-customizable; you can not change how it draws the background. 

What I suggest is to create some parts of widgets and combine them; as an example for text input, you can have only text that can be editing and background as a different widget, same to a button, click handling is one widget, but drawing background is a different one. Druid can also provide a default UI kit with some design concepts, but if it's not suitable for you, you can create your UI kit based on low-level druid widgets. 

There some ideas how can this looks:

Create focusable text box:
```rust
    Focus::new(
        TextBoxDecorator::new(
            EditableText::new()
                .with_placeholder("Enter the command")
                .fix_width(TEXT_BOX_WIDTH),
        ),
    );
```

Create focusable button:
```rust
    Focus::new(
        ClickGestureDetector::new(
            BoxDecoration::new(LinkText::new()),
            &on_click,
        ),
    );
```

What do you think about such a design?

**Comment by cmyr** [comment]
Composition is great, and I certainly think we could be doing better than we currently are.

There are *some* experiments in this direction; I'd point you to `Painter` + `on_click`, which is a way of customizing buttons. Focus is trickier, because it isn't always clear exactly when you would want to take focus, or when you would resign it; these are quite particular decisions.

I would definitely encourage you to play around with these ideas, and see what feels good and what doesn't, in practice? That's how we've arrived at most of our designs; trying out various things in projects that use druid, and then bringing the ones that worked into druid itself.

**Comment by sysint64** [comment]
Okay, got it, I'm working on my application, and I've decided to try using druid as a UI framework, I've been playing for a while with the druid, and made simple Focus widget and customizable button. At the moment I have this (probably not the best names):

```rust
    let button = Focus::new(
        AccessorDecorator::new(
            ButtonDecorator::new(),
            Label::new("Content").padding((8.0, 2.0)),
        )
        .on_click(|_, _, _| println!("Hello World!")),
    );
```

And ButtonDecorator impl:

```rust
pub struct ButtonDecorator;

impl ButtonDecorator {
    pub fn new() -> Self {
        ButtonDecorator
    }
}

struct ButtonColors {
    bg_color: Color,
    text_color: Color,
}

impl ButtonColors {
    fn new(data: &AccessorData, env: &Env) -> Self {
        if data.is_active {
            ButtonColors {
                bg_color: env.get(theme::BUTTON_CLICK_COLOR),
                text_color: env.get(theme::BUTTON_CLICK_TEXT_COLOR),
            }
        }
        else if data.is_hot {
            ButtonColors {
                bg_color: env.get(theme::BUTTON_HOVER_COLOR),
                text_color: env.get(theme::BUTTON_HOVER_TEXT_COLOR),
            }
        }
        else {
            ButtonColors {
                bg_color: env.get(theme::BUTTON_COLOR),
                text_color: env.get(theme::BUTTON_TEXT_COLOR),
            }
        }
    }
}

impl AccessorDecorator for ButtonDecorator {
    fn paint(&mut self, ctx: &mut PaintCtx, data: &AccessorData, env: &Env) {
        let size = ctx.size();

        let rounded_rect = Rect::from_origin_size(Point::ORIGIN, size)
            .to_rounded_rect(env.get(theme::BUTTON_BORDER_RADIUS));

        let colors = ButtonColors::new(data, env);
        ctx.fill(rounded_rect, &colors.bg_color);
    }

    fn set_env(&mut self, _ctx: &mut PaintCtx, data: &AccessorData, env: &mut Env) {
        let colors = ButtonColors::new(data, env);
        env.set(theme::LABEL_COLOR, colors.text_color);
    }
}
```

**Comment by sysint64** [comment]
To pass updated Env, I create a new copy, but I think it's better to create some hierarchical env, to avoid extra copying.
It can looks like this:
```rust
let new_env = Env::new(env);
new_env.set(theme::LABEL_COLOR, colors.text_color);
```

**Comment by jneem** [comment]
Maybe have a look at the existing `WidgetExt` trait for some API inspiration. For example, it allows `w.padding(1.0)` instead of `Padding::new(1.0, w)`. I think this is nicer, especially when nesting.

Regarding `Env`, maybe the `HashMap` in it could be replaced by an `im::HashMap`? Then cloning would be cheap, and the current cloning pattern would give you an effectively hierarchical env. But currently, `im` is only an optional dependency...

**Comment by cmyr** [comment]
we do have some longer-term plans to improve the efficiency of `Env`; one of the simple ones is to have a small fixed-length array of key/value pairs that we set on changes, and then we only bother to actually hit the map when that layer is filled up. Moving to an immutable data structure could also be a win, although not necessarily; a lot depends on how many keys we have, and what the bucket size of the `im::HashMap` is, so this stuff should be measured before we make changes.

**Comment by sysint64** [comment]
> Maybe have a look at the existing `WidgetExt` trait for some API inspiration. For example, it allows `w.padding(1.0)` instead of `Padding::new(1.0, w)`. I think this is nicer, especially when nesting.

Okay, thanks. At the moment I'm trying to come up with API for widgets and extensions are not so important, I can add it later.
> we do have some longer-term plans to improve the efficiency of `Env`; one of the simple ones is to have a small fixed-length array of key/value pairs that we set on changes, and then we only bother to actually hit the map when that layer is filled up. Moving to an immutable data structure could also be a win, although not necessarily; a lot depends on how many keys we have, and what the bucket size of the `im::HashMap` is, so this stuff should be measured before we make changes.

I see, then I just keep the current implementation.

**Comment by cmyr** [comment]
catching up on old notifications; going to close this, @sysint64 if you still have concerns please feel free to reopen. :)
