### ISSUE TITLE
Pass a command to all descendants

### ISSUE THREAD

**Issue by sysint64** [linebender/druid#1090]
I can pass it to particular widget like this:

```rust
ctx.submit_command(MY_COMMAND, ctx.widget_id()),
```

But for my task I need pass the command to all descendants

**Comment by ForLoveOfCats** [comment]
Generally widgets which have children (such as container widgets) pass all or unhandled events to their children which includes commands as seen [here](https://docs.rs/druid/0.6.0/druid/enum.Event.html#variant.Command)

Some examples are [SizedBox](https://github.com/linebender/druid/blob/master/druid/src/widget/sized_box.rs#L135) which forwards all events to its child and [Scroll](https://github.com/linebender/druid/blob/master/druid/src/widget/scroll.rs#L393) which forwards all unhandled events to its child.

**Comment by sysint64** [comment]
Thanks, this works perfectly :+1:
