### ISSUE TITLE
TextLayout::hit_test_text_position is platform dependent.

### ISSUE THREAD

**Issue by aDotInTheVoid** [linebender/druid#1105]
On macOS, `hit_test_text_position` returns the bottom of the text, whereas in Linux it's the top.

```rust
impl Widget<()> for TextTest {
    fn paint(&mut self, ctx: &mut PaintCtx, _: &(), env: &Env) {
        let font_name = env.get(theme::FONT_NAME);
        let font_size = env.get(theme::TEXT_SIZE_NORMAL);
        let font = ctx
            .text()
            .new_font_by_name(font_name, font_size)
            .build()
            .unwrap();
        let text = ctx
            .text()
            .new_text_layout(&font, "Test", None)
            .build()
            .unwrap();
        let pos = text.hit_test_text_position(1).unwrap().point;
        panic!("{:#?}", pos);
    }
}
```
[full code](https://gist.github.com/aDotInTheVoid/8dbcb41bca30cdb0e91bd71acc7f9b06)

When running this code, these are the results.
- Linux (fedora 32, gtk 3.24.21): `(9.0, 0.0)`
- MacOS (10.15.5): `(8.331298828125, 14.0)`

I haven't checked on Windows

**Comment by cmyr** [comment]
This will be fixed when we update to piet 0.2 (shortly)

**Comment by aDotInTheVoid** [comment]
On commit 2961898fb9081dd3224f4f60ab2f69705ccb5817, with
```rust
    fn paint(&mut self, ctx: &mut PaintCtx, _data: &(), _env: &Env) {
        let text = ctx.text().new_text_layout("Test").build().unwrap();
        panic!("{:#?}", text.hit_test_text_position(1));
    }
```
[(full code)](https://gist.github.com/aDotInTheVoid/339eb5fe2bb7bf826f31bc562240daa5)

Macos: `HitTestPosition {
    point: (7.01953125, 12.0),
    line: 0,
}`

**Comment by cmyr** [comment]
Slightly belated, but if you're curious these are different because the fonts and font stacks are different.
