### ISSUE TITLE
Ensure that widgets receive LifeCycle::WidgetAdded as first "event".

### ISSUE THREAD

**Issue by Finnerale** [linebender/druid#1127]
We currently have the rule, that widgets can rely on `LifeCycle::WidgetAdded` being the first "event" (/update/layout/…) a widget receives. Yet we take no measures to ensure this is the case,  and I would like to change that.

My first approach to this was preventing calls to `update`/`event/etc. by doing a "debug panic", i.e. only panic in debug mode, but log a message when running in release mode.

After implementing that I realized that it might be possible to just initialize any widget during those events if it has not been initialized yet, and it turned out that this would be possible as well.

But now I'm unsure which one would be the better solution. The first one allows easy pinpointing of where you did something wrong, while the second basically ignores it and just fixes your mess. The letter however would not fix the whole problem, because if you forgot to call `children_changed` (which is the main cause for a missing `WidgetAdded`), you also end up with a missing `request_layout`, which can not be solved lazily.

I think option one (panicking) is better, because it requires you to take proper care of it. The latter is mostly nice for prototyping I guess, but unless it makes `children_changed` completely redundant it would make things more difficult to debug instead.

**Comment by cmyr** [comment]
My feeling here is that the assertion approach is better; it forces the programmer to be aware of their responsibilities, and also exposes situations where something unexpected is happening. In my experience solutions like the second end up papering over bugs, but don't help in the longer-term.
