### ISSUE TITLE
Show scroll when changing size

### ISSUE THREAD

**Issue by MGlolenstine** [linebender/druid#1129]
If we scroll and show the scrollbar, we can see it's size changing, but if we keep on changing the height of the content, it eventually fades away.
Would there be a way to keep it if the content is changing. That's how most other frameworks do it, just do that you know that something's changing.

**Comment by Finnerale** [comment]
What platform are you on? I tried it with GTK and X11 and both keep the bar visible as long as I keep resizing.

**Comment by MGlolenstine** [comment]
I'm on Linux, GTK as well... You resize what? I tried it with the `list` example and if you keep on adding the items, the scroll starts acting up.

**Comment by Finnerale** [comment]
Oh, my bad
> changing the height of the content

missed the "content", thought you were referring to changing the windows size.


I think we can fix this by showing the scroll bar whenever the content size changes (during layout), should be easy to fix.
