### ISSUE TITLE
Declaring a Widget into an outer scope for List

### ISSUE THREAD

**Issue by swfsql** [linebender/druid#1131]
Hi! I'm a new user of Druid, and I'd like to ask for your help.

Related to a List widget, I'm trying to move a Label::new(..) widget into an outer scope (to lower the code left-tabbing space).

The example is very straight-forward, which is a simple edit on the `list` example.  
The diff can be seen in: https://github.com/linebender/druid/compare/master...swfsql:external-label-on-list?expand=1  
The example can be checked with:

```sh
git clone https://github.com/swfsql/druid.git
cd druid/druid
git checkout external-label-on-list
cargo check --features="im" --example list
```

And the error is:

```
    Checking druid v0.6.0 (E:\r\druid\druid)
error[E0507]: cannot move out of `label`, a captured variable in an `Fn` closure
  --> druid\examples\list.rs:87:29
   |
80 |     let label =
   |         ----- captured outer variable
...
87 |                 .with_child(label.align_vertical(UnitPoint::LEFT))
   |                             ^^^^^ move occurs because `label` has type `druid::widget::Label<(druid::im::Ve
ctor<u32>, u32)>`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
error: could not compile `druid`.
```

Which appears to be related to `FnOnce` vs `Fn` (or maybe something else).  
What I'm really trying is to move the entire widget declaration into the outer scope, do you guys think this is possible?

Note: It's possible to leave the actual `Label(` `_` `)` declaration on the inner scope, and just move out the "textual" information (not the whole widget) into the outer scope (by adding some `move`s here and there), but I couldn't move the whole widget.  
Note: I tested this in another example (hello), which isn't related to a List widget, and moving the widget declaration into an outer scope worked fine, so this is why I think this is related to List kind of widget.

Thanks in advance!

**Comment by Finnerale** [comment]
I think the problem here is that you declare a single `Label` and add it to `n` list items, which won't work.
If you want the equivalent of putting the `Label` into the `List` closure, try something like this:
```rust
        .lens(AppData::left),
        1.0,
    );

    let label = || Label::new(|(_, item): &(Vector<u32>, u32), _env: &_| {
        format!("List item #{}", item)
    });

    // Build a list with shared data
    lists.add_flex_child(
        Scroll::new(List::new(move || {          // <- also, use move for the closure
            Flex::row()
                .with_child(label().align_vertical(UnitPoint::LEFT))
                .with_flex_spacer(1.0)
                .with_child(
                    Button::new("Delete")
```
That way, the label can be recreated for every item.

**Comment by swfsql** [comment]
Yes, that worked perfectly! And indeed, it really shouldn't work for one label to be applied to various items on the list!

Thank you very much!
