### ISSUE TITLE
Label height is too small for upper case accented letters

### ISSUE THREAD

**Issue by alarcheres** [linebender/druid#1134]
Label height is too small for upper case accented letters, accents overflow on the above widget (or are cropped when there is none).

![druid-wrong-label-height](https://user-images.githubusercontent.com/60073372/90342208-a4f27480-e006-11ea-8231-cde1bf5a19ce.png)

Minimal reprodution: 
```rust
use druid::widget::*;
use druid::*;

pub fn main() {
    let main_window = WindowDesc::new(|| Label::new("ÉÀÈÊ"))
        .title("")
        .window_size((400.0, 400.0));

    AppLauncher::with_window(main_window)
        .launch(())
        .expect("Failed to launch application");
}
```
System Specification: 
Druid 0.6
Debian 10 with GTK Backend

**Comment by cmyr** [comment]
this is likely a limitation of cairo's toy text API, and so there isn't much we can do about it until we implement a new text system for linux.

**Comment by PoignardAzur** [comment]
@cmyr Any progress?

**Comment by cmyr** [comment]
should be fixed, can you verify?

**Comment by PoignardAzur** [comment]
That looks fixed to me:

![textbox_screenshot](https://user-images.githubusercontent.com/8573618/128243934-1055783d-ca13-46ce-a6df-e3886ebe2059.png)

But I'm not sure how the textbox example would have looked before.

**Comment by Maan2003** [comment]
yeah probably got fixed by the pango text
![image](https://user-images.githubusercontent.com/49202620/128244518-891e5e27-1c84-4d6e-aaa5-0e961ffd75d8.png)

![image](https://user-images.githubusercontent.com/49202620/128244318-7130f957-4919-4edc-afd0-cf7a91762718.png)
