### ISSUE TITLE
lens::Index does not work on arrays

### ISSUE THREAD

**Issue by smmalis37** [linebender/druid#1138]
As per the title, when attempting to use a lens::Index on an array value I receive errors about Index and IndexMut not being implemented for the array. This is technically true, as they're only implemented on slices, not arrays. Arrays should coerce into slices, but something in all the generics is preventing that from happening. Using lens::Deref doesn't help here, as this is a real coercion and not a Deref impl. I ended up creating a lens::Field that simply indexes in its two closures, which feels unnecessary but works.

**Comment by Finnerale** [comment]
Have you tried the [`lens!`](https://docs.rs/druid/0.6.0/druid/macro.lens.html) macro? Maybe that would help you.

**Comment by smmalis37** [comment]
I did. Both `lens!(Foo, array).Index(i)` and `lens!(Foo, array[i])` gave me various errors.

**Comment by Finnerale** [comment]
According to the docs, you should use it somewhat like `lens!([u8], [4])`, but I've never used it myself. Would be great to have an example of the code causing the error, if that does not work either.

**Comment by smmalis37** [comment]
Here's a minimal example:
```rust
use druid::{widget::*, *};

fn main() -> Result<(), PlatformError> {
    AppLauncher::with_window(WindowDesc::new(main_window)).launch(State::default())
}

#[derive(Clone, Default, Data, Lens)]
struct State {
    data: [String; 9],
}

fn main_window() -> impl Widget<State> {
    let mut column = Flex::column();

    for x in 0usize..9 {
        column.add_child(TextBox::new().lens(/* What goes here? */));
    }

    column
}
```

The following all give errors:
```rust
State::data.index(x)
lens!(State, data).index(x)
lens!(State, data[x])
lens!(State, data).then(lens!([String], [x]))
```
and there's probably others I tried and have forgotten. The only thing I could come up with that worked is
```rust
lens::Field::new(move |s| &s.data[x], move |s| &mut s.data[x])
```

**Comment by Finnerale** [comment]
After patching the `lens!` macro to use `move` closures, this works:
```rust
State::data.then(lens!([String; 9], [x])))
```
Another option would be adding a `Ref` lens, as counterpart do `Deref`:
```rust
/// `Lens` for invoking `AsRef` and `AsMut` on a type
///
/// See also `LensExt::ref`.
#[derive(Debug, Copy, Clone)]
pub struct Ref;

impl<T: ?Sized, U: ?Sized> Lens<T, U> for Ref
where
    T: AsRef<U> + AsMut<U>,
{
    fn with<V, F: FnOnce(&U) -> V>(&self, data: &T, f: F) -> V {
        f(data.as_ref())
    }
    fn with_mut<V, F: FnOnce(&mut U) -> V>(&self, data: &mut T, f: F) -> V {
        f(data.as_mut())
    }
}
```
Use like this:
```rust
State::data.then(lens::Ref).then(lens::Index::new(x))
// or with `LensExt`
State::data.ref().index(x)
```
And the latter seems quite elegant to me.

**Comment by smmalis37** [comment]
It's a shame that an as_ref lens is necessary here, because the idea that arrays aren't directly indexable is just plain weird. However it's true, and I can't think of anything better.

**Comment by cmyr** [comment]
I think the as_ref lens is an excellent solution.

**Comment by smmalis37** [comment]
If I had waited a few releases this might not have been needed lol: https://github.com/rust-lang/rust/pull/74989
