### ISSUE TITLE
Implement close request interception

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1159]
#1118 added the ability to intercept close requests, but this is currently only working for gtk; other backends should support this as well.

- [x] mac
- [x] windows
- [x] x11

**Comment by tay64** [comment]
Hello,
I've created a PR that adds the Windows part ([PR1238](https://github.com/linebender/druid/pull/1238)). This is the first time I'm trying to contribute here, hope I do not commit any faux pas in the process.

**Comment by rjwittams** [comment]
https://github.com/linebender/druid/pull/1254 ends up fixing this on mac
