### ISSUE TITLE
Released documentation  links the druidbook at https://xi-editor.io

### ISSUE THREAD

**Issue by jcdyer** [linebender/druid#1179]
Link is broken on docs.rs and crates.io.  Is it worth pushing an 0.6.1 release to fix the docs?

**Comment by cmyr** [comment]
Thanks for this. If you're interested in doing a PR to fix the links that would be welcome, or someone else can do it in not too long. We're due for a `0.7` release soon, so might hold off until that?

**Comment by jcdyer** [comment]
Looks like this has been resolved.
