### ISSUE TITLE
TextBox uses is_printable to filter text input which is unrelieable.

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#119]
The `is_printable` fn on `KeyCode` is not very useful, because it alone does not tell you whether a key event will have printable text.

As an example: `ctrl + e` on macOS uses the 'printable' `KeyE` keycode, but sends the unprintable ascii value 0x5. similarly with `ctrl + u`, `ctrl + k`, and others.

**Comment by cbondurant** [comment]
I think this is now a non-issue, since I cannot find reference to is_printable in the codebase, and it is most likely a function that was removed in some part of the event rework.

**Comment by xStrom** [comment]
Alright, let's close this for now.
