### ISSUE TITLE
How to set font

### ISSUE THREAD

**Issue by lhjok** [linebender/druid#1228]
I don't know how to set the font, with_font function cannot receive include_bytes! How to import fonts?

**Comment by cmyr** [comment]
to use a custom font right now is a bit of a hack:

Add a `Controller` widget the the root of your application; in that widget, handle `Event::WindowConnected`, and then load a font via the text factory available on the `EventCtx`, (the `text()` method) and then you can call `load_font` on that. If this succeeds, it will return a `FontFamily` object that you can then set on something.

The plan is that you can include fonts in your application bundle and then druid will load them for you and make them available, but we don't have application bundles implemented yet. (#397)
