### ISSUE TITLE
Transparent Window Background Color

### ISSUE THREAD

**Issue by Maan2003** [linebender/druid#1249]
setting `theme::WINDOW_BACKGROUND_COLOR` to a transparent/translucent color leads to some rendering bugs.
examples: 

![image](https://user-images.githubusercontent.com/49202620/93801075-186b4f80-fc5f-11ea-9647-07dd836812eb.png)
![image](https://user-images.githubusercontent.com/49202620/93801135-320c9700-fc5f-11ea-9603-37c9fcf53ab5.png)

**Comment by derekdreery** [comment]
IIRC transparent backgrounds is something that is *very* difficult to get right, because of the cross-platform nature of druid. Because druid will write over parts of the buffer that have changed, if those bits are not opaque you will see the content that was behind them before. Also, if you are writing to some OS-supplied buffer, then it will essentially be uninitialized data, i.e. it will have random stuff that was there before (which looks like the first image).

**Comment by derekdreery** [comment]
Out of interest, are you on windows?

**Comment by derekdreery** [comment]
This may be relevant: https://stackoverflow.com/questions/3970066/creating-a-transparent-window-in-c-win32

**Comment by raphlinus** [comment]
Pasted from Zulip: Doing transparent window backgrounds entails a bunch of changes. You have to do some settings on the swapchain. I think you have to disable the redirection surface on window creation, but I'm not 100% sure about that. If you do that, I believe you lose menus unless you do some more magic to bring that back.

**Comment by Maan2003** [comment]
This is reproducible without any changes to druid, just changing the `WINDOW_BACKGROUND_COLOR`.  

most of the bugs occur on resize. but some like textbox caret leaving trails don't require resize ( trails fade away after sometime )

> Out of interest, are you on windows? 
yes.

**Comment by cmyr** [comment]
my feeling is that we should ignore alpha for the background channel. If at some point we want to support transparent backgrounds as a platform-specific feature I'm open to that, but for the time being i'd consider this a bug.

**Comment by Ciantic** [comment]
I have a fork, where transparency now works:

<img src="https://user-images.githubusercontent.com/64731/107764574-16eb1280-6d39-11eb-9ac0-c2fb6473f1c8.png" width="500" />

Resizing too seems to work:

<img src="https://user-images.githubusercontent.com/64731/107764639-35510e00-6d39-11eb-9f06-da65f9231828.png" width="500" />

Test out the example "transparency.rs" in my fork #1583.
