### ISSUE TITLE
Remove vestigial support for cairo/gtk on macOS

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1250]
This was kept around for a while because I was testing GTK patches on macOS, but that's a poor reason to keep code around that we are obliged to maintain. This will make various `cfg(thing)` paths cleaner, and will also let us clean up some of our cargo manifests.

>we currently allow cairo to be used, opt-in, on macOS. I'm not sure we should, but we do; I think this is why these deps are in two places.

_Originally posted by @cmyr in https://github.com/linebender/druid/pull/1241#discussion_r491038814_

**Comment by PoignardAzur** [comment]
Is there any progress on this?

**Comment by cmyr** [comment]
this has been removed iirc.
