### ISSUE TITLE
label/button rendering issues on web

### ISSUE THREAD

**Issue by JAicewizard** [linebender/druid#1265]
On web the label/button text rendering is offset to the top. If the button is big it is not noticeable but if you resize the window to be small the text overflows the textbox.
There is also an issue in Piet that the colour (or any other attribute) is not settable, but that is not what this issue is about. Due to this it is hard to read the text.
![misplaced_button_text](https://user-images.githubusercontent.com/19241481/94427488-7502c900-018f-11eb-8a32-d79457a1011a.png)
For context the top is the search-bar and bottom is dev tools slided up to make the window smaller artificially.
This is 1 window with 1 child widget, the Button.

**Comment by cmyr** [comment]
See https://github.com/linebender/piet/issues/311; there's some work that needs to be done in the piet-web backend.

**Comment by JAicewizard** [comment]
ok nice, since there wasnt something a log entry (like attributes not being supported) I posted here, I guess we can keep this open until the piet issue is closed?
