### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by justinmoon** [linebender/druid#1268]
The ["Linux platform notes section of the README"](https://github.com/linebender/druid#linux) links to [this dead page](http://gtk-rs.org/docs/requirements.html). Link text is "gtk-rs dependencies".

I looked around the gtk-rs website a bit but couldn't the correct link. Upstream README also has bad link: https://github.com/gtk-rs/gtk/issues/1063

**Comment by Dmitry-Borodin** [comment]
I wrote original note and will fix that in a next few days.

**Comment by Dmitry-Borodin** [comment]
Looks like this link from upstream is the best one, despite they are suggesting to use latest versions of dependencies, not ones from your distro. I think our users will see that and we don't need to clarify.
