### ISSUE TITLE
Animation interferes with timer

### ISSUE THREAD

**Issue by bheisler** [linebender/druid#1277]
Platform: Windows 10

Code: https://gist.github.com/bheisler/f1185c6de8d8ee064fe2b3b215050aae

Druid Version: Latest git
```
[dependencies]
druid = { git = "https://github.com/linebender/druid.git", version = "0.6" }
```

I noticed that timer events don't seem to be delivered while a widget is animating. I found this surprising, as did several others on the Druid zulip, so I wrote a small test case to demonstrate this behavior.

To reproduce, run the example code and click the "Start Timer and Animation" button. About five seconds later, it will print something like this to the command line:
`Timer completed after 5.0059584s. Expected time: 1s. Animation time: 5s.`

The timer is registered for one second, not five, so this is surprising. However, if you comment out `ctx.request_anim_frame();` on either line 32 or 41, then the timer completes after about one second, as expected:
`Timer completed after 0.9909591s. Expected time: 1s. Animation time: 5s.`

You can also adjust ANIMATION_TIME to control how long the custom widget animates for; the timer event will not be delivered until after the animation stops.

**Comment by rhzk** [comment]
So when request_anim_frame() is called a WM_PAINT message is sent to the systems message queue. When we handle the WM_PAINT message Event::AnimFrame() is called which causes request_anim_frame() to get called again creating a WM_PAINT message and so on.

I think the problem here is that WM_TIMER messages have a low priority and therefore dont get put in the message queue as long as there is a WM_PAINT message there, which there constantly is because of the loop. Causing the WM_TIMER message to only be added after the loop ends and thats why your timer ends up lasting as long as the animation

**Comment by jneem** [comment]
Can you check how often `paint` is called on your system? Last time I checked on an actual windows machine, it seemed like we were only getting WM_PAINT about once per monitor refresh, but I remember possibly seeing some other behavior on a VM.

Also (as someone who knows nothing about programming on windows) is it possible to change the message priorities, or alternatively to just retrieve all the available messages and decide on our how how to prioritize them?

**Comment by bheisler** [comment]
Regarding the number of paint calls - it varies a bit but it's around 300 for a 5 second animation, so it looks like it's animating at or around 60fps. The CPU usage hovers around 1-2% as well (on a machine with 4 physical/8 logical cores) so it definitely isn't pinning a core repainting over and over.

Unfortunately I don't know anything about the windows API so I can't help you there.

**Comment by raphlinus** [comment]
It *is* possible to retrieve specific messages in the [GetMessageW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagew) call, but that's only effective when we control the event loop. That fails to be true much of the time: when resizing, when there's a context menu, when there's a file dialog open.

https://devblogs.microsoft.com/oldnewthing/20191108-00/?p=103080 may also be relevant, especially the comments.

Something seems funny here. The WM_PAINT isn't being generated immediately, but is held until the next vsync. If the implementation were sensible, that suggests to me the WM_TIMER should be getting through even though WM_PAINT is in fact a higher priority. But I don't think assuming the implementation is sensible is a good idea.

**Comment by jneem** [comment]
Every time I read the bit about GetMessage's return value, I die a little inside...

Besides the blog post, which definitely seems relevant, I noticed this in the documentation for GetMessage:
> GetMessage does not remove WM_PAINT messages from the queue. The messages remain in the queue until processed.

Do you know what "until processed" means? Could it be that we're doing something wrong and causing the old WM_PAINT message to languish in the queue somehow?

**Comment by raphlinus** [comment]
I *believe* the "until processed" is satisfied by the `ValidateRect` call in our WM_PAINT hander, but it is possible there's something funny going on with that as well.

**Comment by rhzk** [comment]
I dont know how/where windows generate the `WM_TIMER` message but it is possible that windows check timers and generate the message on `GetMessage` calls instead of doing it on some random kernel interrupt at which point `WM_PAINT` is already added to the queue

**Comment by jneem** [comment]
I had a quick stab at doing what the blog post suggested, but I don't have a windows machine handy right this second for testing. @bheisler , if you have a minute to test it, does [this branch](https://github.com/jneem/druid/tree/win-timers) help?

**Comment by bheisler** [comment]
That does seem to work, yes.

**Comment by jneem** [comment]
Thanks for checking! I've opened a PR

**Comment by jneem** [comment]
This should be fixed, with the caveat that timers might still get delayed while dragging or resizing, or during a modal dialog. Fixing those would require a more substantial rework.
