### ISSUE TITLE
Have a sane default minimum window size

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1303]
Currently by default windows can be made arbitrarily small. I think there should be a default minimum size in the 400x400 range, and if you want your window to be resizeable below that you need to explicitly set the minimum size to something smaller, using [`WindowDesc::with_min_size`](https://docs.rs/druid/0.6.0/druid/struct.WindowDesc.html#method.with_min_size).

Just as a note: you can set a minimum size for a window, and I think this should be set for most actual applications? I actually think this should have reasonable defaults, and if you want to be able to resize windows to be very small you should have to specify that manually, but that's also a separate issue. 😁

_Originally posted by @cmyr in https://github.com/linebender/druid/issues/1297#issuecomment-707235539_

**Comment by totsteps** [comment]
I am in favor of adding a minimum default size to `WindowConfig`.

When adding a minimum size to a window config either via `WindowConfig::default()` or `WindowConfig::with_min_size`, I noticed a small issue with the launched window not respecting the minimum size!

Let's say I add a min-size of 600x600, whereas the launched window has a min-size of 500x400!

**Comment by cmyr** [comment]
@totsteps that sounds like a separate bug, would you like to open an issue for it?

**Comment by totsteps** [comment]
Filed in #1322.
