### ISSUE TITLE
On Windows 10, TextBox in hello.rs example does not resize to fit placeholder text

### ISSUE THREAD

**Issue by bzm3r** [linebender/druid#1309]
On Windows 10, I modified the bleeding edge Hello World example (`hello.rs`) so that it looks like 

```Rust
// a textbox that modifies `name`.
    let textbox = TextBox::new()
        .with_placeholder("Who are we greeting?")
        .with_text_size(22.0) // Used to be `with_text_size(18.0)`
        .fix_width(TEXT_BOX_WIDTH)
        .lens(HelloState::name);
```
The text box does resize correctly to the height of the place holder text: 

![hello-world](https://user-images.githubusercontent.com/4350451/95928188-91992680-0d75-11eb-8b46-d1f4966a3652.gif)

**Comment by cmyr** [comment]
Cool, thanks @bzm3r! this is an issue with how I'm storing default attributes in piet, will open an issue there.
