### ISSUE TITLE
document book: #[data(ignore)]

### ISSUE THREAD

**Issue by JAicewizard** [linebender/druid#1362]
`#[data(ignore)]` has no documentation to be found and only 2 examples using it (one of which is not merged yet).

Maybe an idea is making a part in the book about `.update` with a section "when if .update called?" and reference `#[data(ignore)]` in there.

Once this is done the link in the cursor example should be updated so that it stays up-to-date.

**Comment by cmyr** [comment]
It is documented somewhat [in the `Data` trait docs](https://docs.rs/druid/0.6.0/druid/trait.Data.html#derive-macro-attributes), but I agree that this could be more discoverable.

**Comment by JAicewizard** [comment]
Oh yeah, I didnt look there, for less specific things like this I usually expect it to be in the book.
But It should also be documented in the book, that's where I would look for this kind of information and it is very incomplete.
