### ISSUE TITLE
Configurable key repeat

### ISSUE THREAD

**Issue by jjl** [linebender/druid#1400]
It would be nice to be able to configure the key repeat rate from within a druid application.

**Comment by cmyr** [comment]
hmm. I would normally expect this to be something that you manage at the OS level? There may be APIs available on the various platforms that let us ask for an override but I'm not really sure. In any case one for the "far future" milestone.

**Comment by jjl** [comment]
The use case I had in mind was a diagram editor. When you have a thing selected, you want to be able to move them and the default key repeat is obviously going to be terrible for this. But maybe there's something in the animation stuff or i can bodge it with timers

**Comment by cmyr** [comment]
I handle a similar interaction in runebender (and this is common in other drawing applications) by using the shift and meta modifiers to change the adjustment size when moving things with the arrows; shift is ten units, meta is 50, iirc.

**Comment by jjl** [comment]
I think i'd rather bodge it with timers

**Comment by PoignardAzur** [comment]
I agree with Colin that this is something traditionally handled at the OS layer. Closing the issue.
