### ISSUE TITLE
Small issues with building druid on Ubuntu

### ISSUE THREAD

**Issue by kneasle** [linebender/druid#1408]
When compiling druid I encountered a build error on `cairo-sys-rs v0.10.0`, which was solved by running this command (though I'm not sure which of the packages were necessary:
```
sudo apt-get install libglib2.0-dev libcairo-gobject2  libcairo2-dev libgail-dev libatk-bridge2.0-dev  eog-dev libgdk-pixbuf2.0-dev
```

I wouldn't normally make an issue with something like this, but one of the READMEs said to report any build issues, so I have.

**Comment by jneem** [comment]
Do you remember what the actual build error was? I'm confused because we should just require `libgtk-3-dev` and its dependencies. Do you have `libgtk-3-dev` installed? (I'd like to figure out what is actually necessary, so we don't need to recommend installing a bunch of random stuff.)

**Comment by kneasle** [comment]
I do have `libgtk-3-dev` installed, but I'm not sure if it installed with the commands above.

Once I get a chance, I'll uninstall those packages and `libgtk-3-dev` and figure out which ones are needed.

**Comment by jneem** [comment]
That would be great, thanks!

**Comment by kneasle** [comment]
Uninstall attempts:
- [ ] `libglib2.0-dev`
- [ ] `libcairo-gobject2`
- [ ] `libcairo2-dev`
- [ ] `libgail-dev`
- [ ] `libatk-bridge2.0-dev`
- [ ] `eog-dev`
- [ ] `libgdk-pixbuf2.0-dev`

**Comment by kneasle** [comment]
Right I think this experiment is done - I whittled down a few dependencies, but I'm still not sure whether `libgail-dev` is actually needed or if it contains some dependencies that druid needs.

**Comment by derekdreery** [comment]
It will be nice if piet-gpu ends up leading to us dropping the gtk dep. It has a major effect on build times as well.

**Comment by kneasle** [comment]
Hopefully - the build times are pretty long.  They are bearable, though, so long as they're not linear or superlinear in the size of my code (in which case they'd get unacceptable very quickly).

**Comment by derekdreery** [comment]
And you only have to build gtk bindings the first time

**Comment by JAicewizard** [comment]
piet-gpu doesnt have anything to do with GTK. GTK creates the window for us we dont use it in piet. We only use cairo/pango in piet which are also a dep on X11.

**Comment by Maan2003** [comment]
> Installing libgtk-3-dev fixes this and compilation is now successful

Feel free to reopen if you still have issues

**Comment by ardijanr** [comment]
Thanks for this, had to search for each package in dnf as the library names are not the same. However they did the trick.
