### ISSUE TITLE
TextBox crashes if a Lens (Or parse) modifies the string.

### ISSUE THREAD

**Issue by JAicewizard** [linebender/druid#1425]
This is because the caret is added when the character is inserted, caret moved to 1, but then the lens(or parse) removes the character again. TextBox doesn't detect this and the caret remains at 1. The TextBox tries a "replace_range", essentially just inserting since the range is 0 long. The caret is now outside the range of the string, and panics.

I got some solutions but they all seem imperfect:

- When the caret is out of bounds, set the caret at the end of the string.
pros:
  - easy, no additional state, just a bounds check.
cons:
  - only works if at the end of the text, if its in the middle the caret still moves.
- Somehow detect the string being changed, and revert the caret back to its previous position.
pros:
  - works in simple cases where some characters got filtered out.
cons:
  - extra state, need to somehow store information about the previous text and compare to the current one.
  - doesn't work if the text changes more then simply undo the last edit. (There might be some sensible default? like jump to the end/start)

**Comment by JAicewizard** [comment]
Here is a minimal example:
```
use druid::{widget::{TextBox, WidgetExt},AppLauncher, Lens, WindowDesc};
struct L;
impl Lens<(), String> for L {
    fn with<V, F: FnOnce(&String) -> V>(&self, _: &(), f: F) -> V {
        f(&"".into())
    }
    fn with_mut<V, F: FnOnce(&mut String) -> V>(&self, _: &mut (), f: F) -> V {
        f(&mut "".into())
    }
}
pub fn main() {
    AppLauncher::with_window(WindowDesc::new(|| TextBox::new().lens(L)))
        .use_simple_logger()
        .launch(())
        .unwrap();
}
```

**Comment by cmyr** [comment]
yes, we need to always ensure that the selection is valid when the text changes. I've had to fix this locally, if it isn't PR'd I'll take a look and do that.

**Comment by JAicewizard** [comment]
If you mean #1377 then yes you PR'd that already.

**Comment by cmyr** [comment]
right yea it's part of that but I could also split it out. Although I *do* hope to have a version of that ready for review tonight 🤞

**Comment by Zarenor** [comment]
Triage here: @cmyr I see #1377 was merged - did that fix this crash? can we close this issue and #1458?
