### ISSUE TITLE
Examples of canvas style rendering [question]

### ISSUE THREAD

**Issue by kneasle** [linebender/druid#1427]
Are there any examples of how to do canvas-style rendering similar to this in druid:
![image](https://user-images.githubusercontent.com/32932209/99965333-a31a1900-2d8c-11eb-9504-dafdf3d7d139.png)

Ideally I'd have a single widget which would store the raw grid of numbers and render the prettified version of that internal grid.

Also, it would be very beneficial for performance if I could somehow create an atlas of rendered numbers and use that to display the grids (like how `alacritty` handles glyph caching), but for now that's non-essential.

**Comment by derekdreery** [comment]
You will want to use the primitives in `piet` and `kurbo`. The key way to render primitives is through `piet::RenderContext`. These are useable in `druid` by implementing a `Widget` and using the `PaintCtx` in the `Widget::paint` method (which derefs to `piet::RenderContext`). You can also use `druid::widget::Painter` if you don't need to handle events/layout/etc.

Text is still a WIP (especially on linux), but you can use `druid::TextLayout` to calculate and retain glyph positions from text & text properties. If your data always consists of single digits, I would create layouts for `0..9`, and then use them multiple times.

**Comment by derekdreery** [comment]
`piet-gpu` is a project looking at moving rendering onto the GPU, and I'm sure this will include a glyph atlas, but the project is in its infancy. If and when it matures you'd be able to switch and benefit with minimal change to your code.

**Comment by derekdreery** [comment]
The basic pattern for text layouts is

```
let mut layout = TextLayout::new();

// possibly some time later...
layout.set_text("some text"); // you choose how the text is stored, but `Arc<str>` is a common choice and has the alias `ArcStr` in druid.
// optionally set some text properties

// possibly some time later...
// This is a potentially expensive operation that calculates all the retained state, including glyph offsets.
layout.rebuild_if_needed(ctx.text(), env);
// now we have access to a correct `layout.size()`
let size = layout.size();
let x_pos = x_mid - 0.5 * size.width(); // for some x_mid, for example
layout.draw(ctx, (x_pos, 0.0)); // for example

**Comment by derekdreery** [comment]
Also if you have more questions, feel free to drop by [#druid-help](https://xi.zulipchat.com/#narrow/stream/255910-druid-help) - you'll probably get a quicker response.

**Comment by kneasle** [comment]
Awesome - thanks!  I'll do some fiddling but this looks like exactly what I'm looking for.
