### ISSUE TITLE
Add "enabled" state for interactive widgets

### ISSUE THREAD

**Issue by futurepaul** [linebender/druid#143]
As mentioned in #134,  we need some sort of enabled / disabled state for the button widget. It also makes sense for other widgets: slider, checkbox (I'll have a PR for that soon), textbox, scrollbar, and I'm sure other widgets to come.

To kick things off, here's @raphlinus's comment:
> ...what I was thinking (and this is borrowed to some extent from SwiftUI) is that the enabled state becomes part of env (probably with specific API surface for it; doesn't have to go through the typed key/value mechanism) and widgets respond to it. There are definitely questions though.

This sounds pretty straightforward to implement. I'm not sure what the questions are, though!

**Comment by SecondFlight** [comment]
Closing as resolved via #1717.
