### ISSUE TITLE
Old radio button stays selected when new button is selected in `RadioGroup`.

### ISSUE THREAD

**Issue by derekdreery** [linebender/druid#1436]
Old radio button stays selected when new button is selected in `RadioGroup` (until you force it to redraw by e.g. hovering over it).

**Comment by JAicewizard** [comment]
What platform are you on? I do now have this issue (in the flex example) on linux/gtk

**Comment by derekdreery** [comment]
So I think my problem comes from the fact that my `RadioGroup` is inside a `List`.

**Comment by derekdreery** [comment]
Progress: in `ClipBox`, the widget is not correctly identifying that its children are active, and so it is not passing events down the tree. This only happens if the events have been added dynamically in a `List` so I assume this is the problem, but need to dig deeper.

**Comment by derekdreery** [comment]
I thought the patch would fix this bug, but sadly it does not. I will investigate.

**Comment by derekdreery** [comment]
This bug manifests without any `Scroll`, so the only requirement is that some `Radio` buttons are inside a `List`.

**Comment by derekdreery** [comment]
In the end it was a bug in user code - I need to implement `Data` manually to skip checking part of my state under certain conditions. I think added some new state, but forgot to update the `same` method, meaning that data wasn't being informed of a change.
