### ISSUE TITLE
Example in docs/src/get_started.md doesn't build

### ISSUE THREAD

**Issue by djeedai** [linebender/druid#1459]
```
fn build_ui() -> impl Widget<()> {
    Padding::new(
        10.0,
        Flex::row()
            .with_flex_child(
                Flex::column()
                    .with_flex_child(Label::new("top left"), 1.0)
                    .with_flex_child(Align::centered(Label::new("bottom left")), 1.0),
                1.0)
            .with_child(
                Flex::column()
                    .with_flex_child(Label::new("top right"), 1.0)
                    .with_flex_child(Align::centered(Label::new("bottom right")), 1.0),
                1.0))
}
```

The `with_child()` call has 2 argument, but that method only takes one. Not sure what the intent of the example was, either to use `with_flex_child()` (which fixes the build) or to use `with_child()` (but in that case probably remove the last `1.0`).

```
error[E0061]: this function takes 1 argument but 2 arguments were supplied
  --> src\main.rs:14:14
   |
14 |               .with_child(
   |                ^^^^^^^^^^ expected 1 argument
15 | /                 Flex::column()
16 | |                     .with_flex_child(Label::new("top right"), 1.0)
17 | |                     .with_flex_child(Align::centered(Label::new("bottom right")), 1.0),
   | |______________________________________________________________________________________-
18 |                   1.0,
   |                   --- supplied 2 arguments
```

**Comment by jneem** [comment]
Yes, that's something that's changed since 0.6. I think the `with_flex_child` option is the one that will preserve the previous behavior.

**Comment by mtsr** [comment]
I was taking a look at this, but it appears to have already been fixed in 5e2f82143d2771a330099759024c76a3318a053f.

**Comment by derekdreery** [comment]
Thanks for looking @mtsr! Sorry if you spent a lot of time on something already fixed.

**Comment by cmyr** [comment]
Let's close this for now, we'll get a new release out soon.

**Comment by mtsr** [comment]
> 
> 
> Thanks for looking @mtsr! Sorry if you spent a lot of time on something already fixed.

No worries, just a couple of minutes. And I needed to start looking at some code to learn more about druid anyway.
