### ISSUE TITLE
Blank window for example on Sway

### ISSUE THREAD

**Issue by erictapen** [linebender/druid#1469]
When running the [basic example](https://github.com/linebender/druid#example) from the projects Readme, I'm able to start the application but only get a blank window. The window is rendered completely in the color of my background, so I guess it's fully transparent.

My System:

- Distribution: Nixos 20.09
- rustc: 1.48.0
- GTK: gtk+3-3.24.23
- Sway: 1.5
- druid: latest master

I copied the code into a new crate, set `druid = { git = "https://github.com/linebender/druid.git" }` and ran with `cargo run`.

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/druid-test`
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]

(druid-test:21894): Gtk-CRITICAL **: 04:40:04.963: gtk_window_set_default_size: assertion 'width >= -1' failed

(druid-test:21894): Gtk-CRITICAL **: 04:40:04.963: gtk_widget_set_size_request: assertion 'width >= -1' failed
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
WARN  [druid::box_constraints] Bad BoxConstraints passed to Flex:
WARN  [druid::box_constraints] BoxConstraints { min: -19200.0W×-19200.0H, max: -19200.0W×-19200.0H }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Align:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -19200.0W×infH }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Padding:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -19200.0W×infH }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Padding:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -19200.0W×infH }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Flex:
WARN  [druid::box_constraints] BoxConstraints { min: -89664.0W×-89856.0H, max: -89664.0W×-89856.0H }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Align:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -89664.0W×infH }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Padding:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -89664.0W×infH }
WARN  [druid::box_constraints] Bad BoxConstraints passed to Padding:
WARN  [druid::box_constraints] BoxConstraints { min: 0.0W×0.0H, max: -89664.0W×infH }
```

I also tested `cargo run --release` with the same results.

I'm not sure which part of my setup is to blame here. Is it Wayland, Sway or NixOS? Any idea wether I missed out on some dependency?

**Comment by derekdreery** [comment]
I also use sway (on arch in my case) so I might be best placed to help look into this.

**Comment by derekdreery** [comment]
What would be really useful is the version of gtk that druid is linking to. Running `ldd <app location>` should tell you all the libs that are dynamically linked (assuming that you are using dynamic linking).

**Comment by derekdreery** [comment]
Ok, so I know what's going on, but not why.

In gtk+, you set the default width to -1 to indicate "no preference". Any value below -1 is considered an error and the window default size is not changed. As a consequence the window is not sized correctly and nothing is displayed.

Why something other than -1 is being passed to the gtk function I don't know.

**Comment by erictapen** [comment]
Thanks for the insights. I found out, that `window.get_display().get_default_screen().get_resolution()` is `-1` on my setup, which causes this weird `size_px` value of `-6.0W×-5.0H`.

I guess it would be sensible to check `get_resolution()` for `-1`, but what does that mean and how should one act on this information? I have no idea about GTK tbh.

Here is all the debug output I generated in the function you mentioned:
```
get_display(): Display { inner: ObjectRef { inner: 0x561caf09e1c0, type: GdkWaylandDisplay } }
get_default_screen(): Screen { inner: ObjectRef { inner: 0x561caf08b8e0, type: GdkWaylandScreen } }
get_resolution(): -1.0
SCALE_TARGET_DPI: 96.0
scale_factor: -0.010416666666666666
area: ScaledArea { size_dp: 576.0W×480.0H, size_px: -6.0W×-5.0H }
scale: Scale { x: -0.010416666666666666, y: -0.010416666666666666 }
size_px: -6.0W×-5.0H
```

**Comment by derekdreery** [comment]
Awesome, thanks. I don't know either, but I will do some research! :)

**Comment by Th3Whit3Wolf** [comment]
I had the same issue. You can make them work by exporting `GDK_BACKEND=x11`

druid doesn't appear to work natively on wayland.

**Comment by derekdreery** [comment]
Since this issue was opened, I've been working on a backend that uses wayland directly: https://github.com/linebender/druid/pull/1498. Hopefully in the future we can work directly on wayland with X fallback and not have to deal with gtk.

**Comment by erictapen** [comment]
I just reran my test case with latest druid `master` (ead3d8f3d6a7c4e7e477e690fdd946b220815b2b) and the issue doesn't persist anymore!

My setup changed in the following way:

- Distribution: NixOS 20.09 -> NixOS 21.05
- rustc: 1.48.0 -> 1.52.1
- GTK: gtk+3-3.24.23 -> gtk+3-3.24.27
- Sway: 1.5 -> 1.6
- druid: latest master

I don't think I managed to test the `wayland` branch by @derekdreery though, as it produces the same blank window from before for me.
The current state is fine for me for further experimenting with druid :+1:.
