### ISSUE TITLE
Have a from_hex function for creating a Color

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1471]
When creating a `Color` Enum there are a myriad of options, however there isn't a function like `from_hex(hex: &str)` which would take a color represented as hexadecimal. I know that rust does have hexadecimal literals so that could be used in the other functions in place of decimal literals. I feel that maybe a user wouldn't know that hexadecimals literals exists and might want to specify colors using a hex triplet. 

I feel like 
 - It should be noted in the documentation that a user can still use the hex triplet using the hex literal syntax
 - Maybe there should also be `from_hex(hex: &str)` function for convenience, though this wouldn't be as important as noting the hex literal syntax

**Comment by derekdreery** [comment]
I think you could make the function `const`, which might make it a nice way to define hard-coded colors.

**Comment by cmyr** [comment]
Just went ahead and implemented this in piet; it *is* const, but because parsing can fail it returns a `Result`; I'm not sure how well this will work in `const` contexts, as a result of that?

**Comment by arthmis** [comment]
Closed with https://github.com/linebender/piet/pull/374
