### ISSUE TITLE
Color::rgb usage not very "obvious"

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1472]
This function actually expects the values to be between 0 and 1, however it accepts anything that can be converted to a `f64`. So I used it like so `rgb(85, 83, 99)`. Which seems to translate to rgba(1.0, 1.0, 1.0). I know there are the `rgb8` functions and others like it which provide other options. I was under the impression that it would scale the number appropriately and was just trying to figure out why the background was always just a white background no matter what value I chose. Could this function be more restrictive?

**Comment by raphlinus** [comment]
(This is actually in piet, rather than druid, so should probably be filed and discussed there. Thanks for raising the issue though, I would like to improve it)
