### ISSUE TITLE
Implement serde::deserialize for Vector

### ISSUE THREAD

**Issue by IronOxidizer** [linebender/druid#1476]
This should be behind a feature and would improve ergonomics when ingesting data from any serialized data directly to `druid::Data`. This should be pretty straight forward as `Vector` already implements `FromIterator` and `FromVec`.

**Comment by derekdreery** [comment]
There is probably a `serde` flag on `im` that will enable this.

**Comment by derekdreery** [comment]
I did a PR to add a `serde` flag that enables the `(De)Serialize` implementation for `im` types.
