### ISSUE TITLE
[feature request] A widget that sets the cursor on hover.

### ISSUE THREAD

**Issue by derekdreery** [linebender/druid#1478]
Currently if you want to set the cursor for a widget you need to intercept `event`s. This means using a custom `Controller`, which can be fiddly and error-prone.

This request involves adding a new widget (probably called `Cursor`) to `druid::widget` that sets the cursor whenever it is hovered, and a `cursor` method to `WidgetExt` that wraps the widget in a `Cursor`.

**Comment by derekdreery** [comment]
If you want to have a go at implementing it and have any questions, feel free to post them here.

**Comment by derekdreery** [comment]
I'll wait for people to comment on whether it's a good idea before I say people should have a go at implementing it.

**Comment by derekdreery** [comment]
Here's a widget I made to do something like this:

```rust
/// Button controller.
///
/// Responsible for setting the cursor and calling a contained on_click function on click.
struct BtnController<T> {
    cursor: Cursor,
    on_click: Box<dyn Fn(&mut EventCtx, &mut T, &Env)>,
}

impl<T> BtnController<T> {
    fn new(cursor: Cursor, on_click: impl Fn(&mut EventCtx, &mut T, &Env) + 'static) -> Self {
        BtnController {
            cursor,
            on_click: Box::new(on_click),
        }
    }
}

impl<T, W: Widget<T>> Controller<T, W> for BtnController<T> {
    fn event(&mut self, child: &mut W, ctx: &mut EventCtx, event: &Event, data: &mut T, env: &Env) {
        match event {
            Event::MouseMove(_) => ctx.set_cursor(&self.cursor),
            Event::MouseDown(MouseEvent { buttons, .. }) if buttons.has_left() => {
                ctx.set_active(true)
            }
            Event::MouseUp(MouseEvent { buttons, .. }) if !buttons.has_left() => {
                if ctx.is_active() {
                    (*self.on_click)(ctx, data, env);
                    ctx.set_active(false);
                }
            }
            _ => (),
        }
    }
}
```

**Comment by jneem** [comment]
Do the changes in #1433 help here? I think they should give more-or-less the behavior you want without adding wrapper widget...

**Comment by derekdreery** [comment]
@jneem say I have a widget like `Flex::row().with_child(Label::new("test"))`, how do I make the cursor change on hover?

**Comment by jneem** [comment]
Oh, right, I was thinking of the case where you already have a custom widget.

What if we added `set_cursor` to the lifecycle context, and then added a `on_added` function to `WidgetExt`, allowing for a callback that's called when the widget gets `WidgetAdded`? I can imagine this being useful for other purposes, and it would allow you to do
```
Flex::row()
    .with_child(Label::new("test"))
    .on_added(|ctx, _data, _env| ctx.set_cursor(&Cursor::Arrow));
```

**Comment by derekdreery** [comment]
Hmm yeah that would work as well. So this is a custom controller that runs the callback on `LifeCycle::WidgetAdded`?

**Comment by jneem** [comment]
That's what I was thinking, yes. If there are other things that are worth having callbacks for, they could be included as well, of course.

**Comment by derekdreery** [comment]
Cool, then if we wanted then we could add a `WidgetExt::with_cursor` function on top. Sounds like a (more general) plan.

**Comment by cmyr** [comment]
I think this makes a lot of sense!

**Comment by derekdreery** [comment]
Ok sounds like just adding `on_added` for now is the consensus. I'll update the issue.
