### ISSUE TITLE
[feature request]: Create a method on `WidgetExt` that allows the user to run some code when the widget is added.

### ISSUE THREAD

**Issue by derekdreery** [linebender/druid#1480]
Follows on from https://github.com/linebender/druid/issues/1478.

Sometimes it's necessary to do something when a widget is created. One example would be to set the cursor when the mouse is hovered over the widget. Currently this would require creating a custom controller. This issue proposes the following function:

```rust
pub trait WidgetExt<T: Data>: Widget<T> + Sized + 'static {
  // .... after on_click
  fn on_added(self, f: impl Fn(&mut LifeCycleCtx, &T, &Env) + 'static) -> ControllerHost<Self, Added<T>>;
  // ...
}
```

(I might have got the function signature wrong). The function would require a new type be created (`Added<T>`) and `Controller` implemented for it. The controller would react to the `LifeCycle::WidgetAdded` lifecycle event by running the closure.

**EDIT** I did get the function signature wrong. Corrected now.

**Comment by derekdreery** [comment]
If anyone without much experience with druid wants to have a go, I'm happy to answer and questions you might have.

**Comment by arthmis** [comment]
I would like to do this.

**Comment by derekdreery** [comment]
@arthmis go for it! :)

**Comment by arthmis** [comment]
I have run into an issue here. 

The function parameter for on_added 
```rust
f: impl Fn(&mut LifeCycleCtx, &mut T, &Env)
```
requires a `&mut T` for data, which is incompatible with `Controller`'s `lifecycle`'s function definition which is
```rust
fn lifecycle(
        &mut self,
        child: &mut W,
        ctx: &mut LifeCycleCtx,
        event: &crate::LifeCycle,
        data: &T,
        env: &Env,
    )
```
Does the closure have to receive a `&mut T`?

**Comment by cmyr** [comment]
No, on_added doesn't get mutable access to the data. We *could* also have a `on_window_connected` method that does get mutable data, if we wanted; the potential gotcha there is that not all widgets will see the `WindowConnected` event (it's only sent once, so widgets created after the window is created won't get it).

**Comment by derekdreery** [comment]
@arthmis sorry my bad: `on_added` should get an immutable reference to `T`. I will update the issue accordingly.

The `on_added` method will be for setting things up inside the widget. It can use the data, but can't alter it.
