### ISSUE TITLE
How can I close windows console?

### ISSUE THREAD

**Issue by junknet** [linebender/druid#1483]

**Comment by cmyr** [comment]
You will have to find some way of packing up your binary into some format windows recognizes, and will let you launch. We don't do this for you yet, although we will eventually. I know that some people have got this working but I don't know the particulars. I think https://github.com/konkers/pollendina might be a project that does this?

**Comment by Zarenor** [comment]
I'm not entirely sure what's being asked here - if you want your windows app to not ever open a console, you're looking to add `#![windows_subsystem = "windows"]` to the file containing your `fn main()`. That should prevent a console window opening; it changes what entry point rustc emits, and handles other unsafe details that happen before `main` to get everything in std set up with the OS (where necessary).

If this isn't what you're looking for, I think it's what Colin is getting at - binary packing and the like that we haven't built any special tools for yet. It's possible someone has something experimental put together, but I can't bring anything to mind.

**Comment by junknet** [comment]
#![windows_subsystem = "windows"]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Colin Rofls<mailto:notifications@github.com>
发送时间: 2020年12月23日 3:49
收件人: linebender/druid<mailto:druid@noreply.github.com>
抄送: junknet<mailto:beini87@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [linebender/druid] How can I close windows console? (#1483)


You will have to find some way of packing up your binary into some format windows recognizes, and will let you launch. We don't do this for you yet, although we will eventually. I know that some people have got this working but I don't know the particulars. I think https://github.com/konkers/pollendina might be a project that does this?

―

**Comment by junknet** [comment]
> 
> 
> I'm not entirely sure what's being asked here - if you want your windows app to not ever open a console, you're looking to add `#![windows_subsystem = "windows"]` to the file containing your `fn main()`. That should prevent a console window opening; it changes what entry point rustc emits, and handles other unsafe details that happen before `main` to get everything in std set up with the OS (where necessary).
> 
> If this isn't what you're looking for, I think it's what Colin is getting at - binary packing and the like that we haven't built any special tools for yet. It's possible someone has something experimental put together, but I can't bring anything to mind.


That's what I wanted to find. Thank you so much！

**Comment by junknet** [comment]
1.
