### ISSUE TITLE
How to focus TextBox programatically?

### ISSUE THREAD

**Issue by fxdave** [linebender/druid#1487]
There are several use cases when you want a default element focused, so you don't have to click on it.
There is a set_focus method in context, but I can't really see where I could access it.

**Comment by cmyr** [comment]
This is slightly annoying right now; you would need to use a controller that requests focus in response to some other event; if you need very fine-grained control you could make this be a `Command` that you send.

**Comment by cmyr** [comment]
(closing since we have a bad habit of leaving every issue open, but feel free to ask follow-up questions here as needed 😄 )

**Comment by fxdave** [comment]
Thanks, it worked!

If anyone wants an example:
```rust

struct DefaultFocusController;

impl<W: Widget<VonalState>> Controller<VonalState, W> for DefaultFocusController {
    fn event(&mut self, child: &mut W, ctx: &mut EventCtx, event: &Event, data: &mut VonalState, env: &Env) {
        if let Event::WindowConnected = event {
            ctx.request_focus()
        }

        child.event(ctx, event, data, env)
    }
}
```

```rust
let search_box = TextBox::new()
        .with_placeholder("Try some keyword...")
        .controller(DefaultFocusController {})
```
