### ISSUE TITLE
how to build/run examples

### ISSUE THREAD

**Issue by BrennenSprimont** [linebender/druid#1490]
Howdy,

Sorry in advance if this is dumb or I missed documentation somewhere.

I can't get some of the examples to run. Most seem to run with `cargo run --example {file_name}` but some throw build errors. Specifically, any that use `druid::im` I can't seem to get working. The two I tried and that failed were `tabs` and `widget_gallery`,

This issue/comment on cargo seems to be related:
https://github.com/rust-lang/cargo/issues/4663#issuecomment-741709289

System:
 * Windows10 19042
 * rustc 1.48.0
 * cargo 1.48.0 

Steps to reproduce:
 * `git clone https://github.com/linebender/druid`
 * `cargo run --example tabs`
   * Cargo suggests adding the `--features` argument to build with `im`. If I add this, I then get another error stating `--features` doesn't do anything.

Output:
```
PS D:\repositories\druid> cargo run --example tabs
error: target `tabs` in package `druid` requires the features: `im`
Consider enabling them by passing, e.g., `--features="im"`
PS D:\repositories\druid> cargo run --features="im" --example tabs
error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
```

**Comment by cmyr** [comment]
yea, to run features you need to be inside the `druid` directory; the root directory has multiple crates, and so when you use `--features` there it doesn't know who you're trying to pass features to.

**Comment by BrennenSprimont** [comment]
that works, thanks!
