### ISSUE TITLE
Multiline textbox selection incorrect

### ISSUE THREAD

**Issue by jackyarndley** [linebender/druid#1514]
![image](https://user-images.githubusercontent.com/34801340/103942361-248b0680-5195-11eb-9385-997b48e3606c.png)

I have a multiline textbox which displays an editable string, sometimes updated by my application. When trying to select with the multiline textbox the selection is incorrect. 

Using the mouse from the bottom line to the top (selected) line in the screenshot does not select any of the middle lines, and also the top line is selected from the incorrect direction.

This is how the textbox is created:
`TextBox::multiline().with_text_size(10.0).expand_width().lens(FractalData::temporary_real)`

Using the latest version of druid on windows.

**Comment by cmyr** [comment]
Tracked this down to an issue with not correctly handling selections of lines that are not broken at whitespace; this will be fixed in the next release of piet.

**Comment by cmyr** [comment]
this should be fixed with #1677
