### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by cymqqqq** [linebender/druid#1516]
When I run "cargo build":
warning: unused import: `PlatformError`
 --> src\main.rs:2:41
  |
2 | use druid::{AppLauncher,LocalizedString,PlatformError,Widget,WidgetExt,WindowDesc};
  |                                         ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `colum` found for struct `Flex<_>` in the current scope
  --> src\main.rs:10:11
   |
10 |     Flex::colum().with_child(label).with_child(button)
   |           ^^^^^
   |           |
   |           function or associated item not found in `Flex<_>`
   |           help: there is an associated function with a similar name: `column`

error[E0308]: mismatched types
  --> src\main.rs:16:5
   |
13 |   fn main() {
   |             - expected `()` because of default return type
...
16 | /     AppLauncher::with_window(main_window)
17 | |     .use_simple_logger()
18 | |     .launch(data)
   | |                 ^- help: try adding a semicolon: `;`
   | |_________________|
   |                   expected `()`, found enum `std::result::Result`
   |
   = note: expected unit type `()`
                   found enum `std::result::Result<(), PlatformError>`

error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `druid`

To learn more, run the command again with --verbose.
So, how can I fix it?

**Comment by Zarenor** [comment]
It seems to me like following the compiler's suggestions would fix your issue; I'll expand a little on what it says: 
- You have a typo in `colum()`, it should be `column()`
-  `.launch(data)` doesn't return a unit type, so you need to add a semicolon (if you don't wish to handle any possible error case). Often, we'll just use `.expect("launch failed");` or something similar.

This kind of thing isn't really something to support with issues, though. For support like this (and any other questions you might have), we recommend joining [our zulip instance](https://xi.zulipchat.com/)

**Comment by cmyr** [comment]
agree that Zulip would a better place for this sort of question, it isn't a druid issue particularly. :)
