### ISSUE TITLE
Label TextAlignment is not working

### ISSUE THREAD

**Issue by edwin0cheng** [linebender/druid#1525]
![Screenshot from 2021-01-11 18-23-29](https://user-images.githubusercontent.com/11014119/104169207-27f2ec00-543a-11eb-8d34-c83277c33ce8.png)

**Comment by cmyr** [comment]
Text alignment is not yet implemented on linux, this is an issue in piet.

**Comment by Maan2003** [comment]
text alignment is now implemented on linux (linebender/piet#425)
