### ISSUE TITLE
Not receiving events on the main thread for an app running in the background on macOS

### ISSUE THREAD

**Issue by x3ro** [linebender/druid#1529]
Hey folks, 

so I've built a small GUI using druid, and it's working rather well as long as it's in the foreground or generally visible on screen. If it's not visible on the screen, however, it stops or slows down significantly in receiving events. This behaviour can be easily observed by running the druid `timers` example and inserting some output / logging [around here](https://github.com/linebender/druid/blob/689f0c40f2f7b1ded7ac97c9d197f8ba0d317f79/druid/examples/timer.rs#L56). 

The events I'm receiving are sent from a different thread I spawn in the beginning, and unfortunately I really need them to be sent and processed in the main thread because they trigger macOS accessibility functionality that can only be dispatched from there.

I initially expected that this is some macOS specific behaviour caused by some `NS*` class, but I've come up short on my search. Is this expected druid / macOS behaviour, and does anyone know if it can be fixed?

**Comment by cmyr** [comment]
Interesting, I do not have any idea what's going on here. I would not expect this behaviour for a cocoa application, and I suspect we're doing something funky when we get sent into the background, but I'm really not sure.

I would maybe start out by just verifying that if you make a simple dummy cocoa app timers continue to work as expected when that app is in the background, and then we can try to dig into what's going on here?

**Comment by x3ro** [comment]
Sounds good, I'll go ahead with that and report back. Just wanted to make sure that I'm not missing something really obvious first :D

**Comment by x3ro** [comment]
After creating an Objective-C project in Xcode and adding the following to the `AppDelegate`, I can indeed confirm that appears to be expected behaviour in macOS when creating an `NSTimer`:

```objc
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {  
    [NSTimer scheduledTimerWithTimeInterval:0.1
        target:self
        selector:@selector(targetMethod)
        userInfo:nil
        repeats:YES];
}

-(void)targetMethod {
    NSLog(@"tick tock");
}
```

Reading [this question on StackOverflow](https://stackoverflow.com/q/8415870/124257) it seems like this is expected behaviour. One of the answers suggests a workaround, though for iOS so I'm not sure if it'd be applicable (or desirable) on macOS. I also haven't examined Windows or Linux, but I'm assuming they're not exhibiting similar behaviour?

**Comment by cmyr** [comment]
this shouldn't be hard, you should be able to use the use the `objc-rs` `msg_send!` macro directly here, there's lots of examples of calling into cocoa/objc in `druid-shell/platform/src/mac` and in the piet repo's mac backend as well.

**Comment by x3ro** [comment]
It took some fiddling but in the end I arrived at a solution that seems to work, and is essentially a copy of what [this author](https://github.com/rennis250/processing-rs/blob/33e5c5b4abef16b6d27af6b27ec5b2d9892a732a/src/lib.rs#L305) did. 

I wrapped this into a crate for convenient usage: [macos-app-nap](https://crates.io/crates/macos-app-nap).

Since this is not a druid related problem I suppose this issue can be closed 🤔

**Comment by cmyr** [comment]
Glad you sorted this out, and it will be good to know for next time. :)
