### ISSUE TITLE
scroll method in WidgetExt

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1544]
From my limited experience, I sometimes wished I could just add a `.scroll` to the end of a widget definition. Wrapping a widget in a scroll isn't too annoying but it does, at least to me, make things a bit more difficult to read. The function definition would look like this

```rust
// I don't know if this definition is the correct one, specifically for the return type
pub fn scroll(self, direction: ScrollDirection) -> Scroll<T, Self> {
 // within here there can be some matching on the `ScrollDirection` which would 
// create the Scroll appropriately
}
pub enum ScrollDirection {
    Horizontal,
    Vertical,
    Both,
```
Would this sort of change be welcome in `WidgetExt`?

**Comment by cmyr** [comment]
Oops, missed this one!

yes, this would totally be a welcome addition.

I don't even think we need the `direction` argument; once you get the `Scroll` widget back, you can call `vertical()` or `horizontal()` on it as you wish, like:

```rust
my_widget.padding(8.0)
    .scroll()
    .vertical()
```

**Comment by arthmis** [comment]
Can someone mark this issue as `good first issue`. I think this should be easy for someone to do who is new to druid.

**Comment by cmyr** [comment]
@arthmis I've sent you an invite for 'triage' access to this repo, so you can add tags and do other things like that as you see fit. :)
