### ISSUE TITLE
Vertically Align text in TextBox

### ISSUE THREAD

**Issue by samyak-jain** [linebender/druid#1549]
I want text inside a TextBox to be centered vertically. ```with_text_alignment``` seems to only align text horizonatally.

I've tried using the Align widget but it doesn't seem to work. Is there any way to do this?

**Comment by x3ro** [comment]
If you're happy to align the TextBox relative to the other widgets, instead of aligning the text inside the TextBox vertically, you can do (written from memory, not tested):

```rust
Flex::column()
    .with_flex_spacer(1.0)
    .with_child(your_textbox)
    .with_flex_spacer(1.0);
```

**Comment by samyak-jain** [comment]
Not quite what I was looking for. Maybe something worth looking at for #883?

**Comment by cmyr** [comment]
@samyak-jain what are you looking for and what are you getting? Are you giving a textbox a fixed size that is taller than a line of text, and you want the text to be centered in the available space? If yes this is not currently supported. By default a single-line textbox is sized vertically to fit a line of text given the metrics of the font that textbox is configured with. Multi-line textboxes position their text at the top of the available space.

**Comment by samyak-jain** [comment]
Yup. That is exactly what I was asking about. Let me know if the issue is "won't fix" or would be handled in a separate issue so I can close this one. Or if you want to leave this up as a tracking issue, that's fine as well.

**Comment by cmyr** [comment]
I won't say 'wontfix' but this is definitely a low priority feature, for me. I'm curious about your specific motivation, though, is this a design pattern you see regularly?

**Comment by samyak-jain** [comment]
I think this would only make sense for single line texboxes which have a larger size. I think for multiline textboxes it would make more sense for the text to start from the top.
Just my 2 cents, other people in the community might have a different view. I'm not a UI/UX expert.

**Comment by x3ro** [comment]
Could you, for reference to a potential implementor, show a UI sketch of a layout that would benefit from this feature, i.e. on that is currently not achievable? Maybe @cmyr already fully understands this issue, but I'm not quite there yet 😅

**Comment by cmyr** [comment]
@samyak-jain My position is that a single-line textbox should be sized based on the size of the text it contains, which is the default behaviour. I suspect that forcing the height of a textbox to some larger value points to a design problem.

If you have a particular case where this is a desired behaviour I would be happy to see it, but otherwise I'm happy with the current design. :)

**Comment by samyak-jain** [comment]
@cmyr Fair enough. I'll close the issue then.
