### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by neurotok** [linebender/druid#1550]
What do you think ?

![druid logo](http://pingpongcat.com/data/druid.png)

Project page
https://www.figma.com/file/qdlcxe7k5VNEM3rN6WLtEh/Druid

**Comment by x3ro** [comment]
Looks pretty neat, I like the tone of purple. Are the font(s) used open source or freely available?

**Comment by neurotok** [comment]
O yeah. It's Rubik bold. Open Font Licence
https://fonts.google.com/specimen/Rubik#license

If you like it I can export it in all sours of formats. Its just a logo but I think that with some nice looking website, some visuals and awsome samples the project will attract FOSS developers faster and someday stand in the same league with Flutter and Qt. 

Im a UI designer/developer and I must say that there is a HUGE need on the market for this kind of UI solution.

**Comment by x3ro** [comment]
I'm not affiliated with the project, but like the idea. I agree that a great visual first impression can make a lot of difference :D

**Comment by cmyr** [comment]
@neurotok sorry for the delayed response! This is certainly a major improvement on our (currently non-existent) identity, so I'm definitely in favour. It's always good to have designers involved in open source.

**Comment by PoignardAzur** [comment]
@neurotok Could you provide a few more versions of the logo?

I'm thinking of adding:
- A slightly smaller version of the first banner (the purple one) at the beginning of the README.
- A 128x128 logo for [the doc.rs page](https://docs.rs/druid/0.7.0/druid/).

If you can provide images in that format, I'll write a PR to add them to the project.

**Comment by neurotok** [comment]
sure @PoignardAzur  here the banner pack extended by the formats you asked for:

https://www.dropbox.com/s/h6ocxmcmd8l95b2/druid_logo_pack.zip?dl=0

If you have any requests in the future for graphics or component designs you can count on me!

**Comment by leontepe** [comment]
Hey @neurotok, could you reach out to me [on Zulip](https://xi.zulipchat.com/)? I'd contact you myself, but can't seem to find a contact email anywhere. Thanks!

**Comment by xorgy** [comment]
> Looks pretty neat, I like the tone of purple. Are the font(s) used open source or freely available?

Just a tidbit about that: letterforms are almost never copyrightable, so as long as the files don't embed the fonts, the copyright on them is irrelevant.
