### ISSUE TITLE
The 'markdown_preview' is broken on Linux

### ISSUE THREAD

**Issue by ffreling** [linebender/druid#1553]
On Linux, the markdown preview example seems broken:
- there is no attribute applied to the text
- there is an artifact when rendering newlines (https://github.com/linebender/druid/issues/1545)

![druid_mardown_example](https://user-images.githubusercontent.com/324713/105771486-e8abbb80-5f60-11eb-8193-7ea6e195e392.png)

Revision: `b40a363d`
OS: Linux Manjaro 5.10.2-2-MANJARO

**Comment by cmyr** [comment]
Rich text isn't implemented on linux yet, although it should be soon, you can track https://github.com/linebender/piet/pull/389 for progress on that. :)

**Comment by kud1ing** [comment]
https://github.com/linebender/piet/pull/389 was closed. Can this issue be closed, too?

**Comment by ForLoveOfCats** [comment]
Yes! As of https://github.com/linebender/druid/pull/1677 this has been resolved. Good catch :)
![image](https://user-images.githubusercontent.com/30666851/114072019-c642f200-986f-11eb-8ceb-542ea0325976.png)
