### ISSUE TITLE
set_cursor in PaintCtx

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1555]
I would like to change to the mouse cursor in a Painter widget. It doesn't seem that `set_cursor` is available in `PaintCtx`, only in `EventCtx`. I basically want to change the cursor if the widget `is_hot` or maybe clicked on. Would it be possible to get `set_cursor` in `PaintCtx` or be able to handle events in `Painter`?

I guess I can also write a controller for this situation, though I would prefer not to implement another type for just this.

**Comment by cmyr** [comment]
By design, the paint method has no side effects. As you note, a controller would be a good approach here, handling the `HotChanged` event.

**Comment by arthmis** [comment]
Well in that case, would it be possible have another `Controller` widget like `Click`, that only handles event? I guess it's not terribly necessary, but not having to create another struct to handle only events would be nice.

**Comment by cmyr** [comment]
That's really sort of what `Controller` is about. You could maybe have a modular widget that allowed you to pass closures to implement the various methods but ultimately the API ends up not being much better. 🤷
