### ISSUE TITLE
Child process exits when window closes

### ISSUE THREAD

**Issue by kotx** [linebender/druid#1564]
If I check for the child process (using the same match code) before `AppLauncher::with_window`, the Neovim process exists. However, when it comes after (as shown below), closing the app window kills the child process for some reason. Is this intended behavior? If so, how can it be disabled? 

```rust
let mut child = nvim.spawn().expect("Failed to execute Neovim");

AppLauncher::with_window(WindowDesc::new(build_ui)).launch(())?;

// Clean up
match child.try_wait() {
    Ok(None) => {
        println!("Found Neovim child process running, killing it now.");
        child.kill().expect("Failed to kill Neovim child process");
    },
    Err(e) => println!("Error trying to wait for Neovim child process: {}", e),
    _ => {}
}
Ok(())
```

**Comment by cmyr** [comment]
You're trying to run an nvim server and communicate it via druid, but you would like the server to continue running after you close the druid window? This is not a case we've really considered, and it's very possible that something in the shutdown code on a given platform is terminating the process; you would have to investigate on your particular platform.

**Comment by kotx** [comment]
> You're trying to run an nvim server and communicate it via druid, but you would like the server to continue running after you close the druid window? This is not a case we've really considered, and it's very possible that something in the shutdown code on a given platform is terminating the process; you would have to investigate on your particular platform.

I'd like to handle the closing of the window with some cleanup (to close neovim properly), but maybe there's a way to catch that via an event?

**Comment by cmyr** [comment]
So there are two ways to handle this: one is by handling events in a custom widget or controller (`Event::WindowCloseRequested` and `Event::WindowDisconnected`) *or* you can set a global `AppDelegate` that can react to windows being added and removed; see the `multiwin` example for some use of that.

**Comment by kotx** [comment]
> So there are two ways to handle this: one is by handling events in a custom widget or controller (`Event::WindowCloseRequested` and `Event::WindowDisconnected`) _or_ you can set a global `AppDelegate` that can react to windows being added and removed; see the `multiwin` example for some use of that.

Thanks a bunch! I'll try these.
