### ISSUE TITLE
Flex spacers should not be implemented as widgets.

### ISSUE THREAD

**Issue by JAicewizard** [linebender/druid#1566]
Currently spacers are inefficiently implemented via normal widgets, this is not really the right tool for the job.
If spacers are just widgets, every time they are layed out they have to go through a `WidgetPod`, which doesn't actually do much in this case.

If instead we put some spacer data with the widgets, we can remove the unneeded layer of abstraction.
I used the `flex` showcase as a benchmark, timing the amount of time a layout each time, and averaging the values over time. (and a separate thread to force a rebuild and thus reload)
I implemented a simple system to use this method, which (at least looks like) it produces the exact same results on screen as before.
These are the results:
| spacer setting\time(µs)  | before | after |
| ------------- | ------------- |------------- |
| none  | 100  | 104  |
| default  | 128  | 112  |
| flex  | 116  | 104  |
| fixed  | 112  | 104  |

It is expected to see values go up with none since it doesn't benefit, while still having to carry the extra weight.

Implementation aside, is this something druid wants?

EDIT:
https://github.com/JAicewizard/druid/tree/non_widget_padding

**Comment by JAicewizard** [comment]
I got new benchmarks, with a different implementation. This implementation uses an enum to diferentiate between flex/fixed child/spacer. This makes it more flexible to future changes, and improves performance yet again. Most importantly, there is no longer a regression without spacers.
These numbers are wildly different, because these ware run in the release profile (I know...) and in a hot loop 1000 every time. This means it is all in cache and branch predictor can do its work. So these would be ideal conditions for all.

| spacer setting\time(µs)  | before | previous patch | current |
| ------------- | ------------- |------------- |
| none  | 2.7  | 2.9 | 2.7  |
| default  | 3.8 | 3.3 | 3.2  |
| flex  | 4.0  | 3.1 | 3.0  |
| fixed  | 3.1  | 3.0 | 2.8  |

Changes are pushed to the latest commit on the same branch

**Comment by cmyr** [comment]
Yea, this was a bit of a hack. I do think that the correct solution uses an enum; what I might imagine would be something like,

```rust
enum Item<T> {
    Child(WidgetPod<T, Box<Widget<T>>),
    Spacer(Spacer),
}
```


...or something. It ended up being a bit of a hassle, which is why I went with the simple solution we use currently.

**Comment by JAicewizard** [comment]
Hmm I seem to have messed something up, I thought I pushed the latest code, which uses an enum.
I basically do what your example does too, except I use 4 variants (2 extra for the flex versions of each)
