### ISSUE TITLE
Window Auto size

### ISSUE THREAD

**Issue by Zenthae** [linebender/druid#1567]
hello, is it possible to tell the window to start with a a size matching the content size ? so that it's not necessary to hard-code the size of the window, found this but no new for some times, #1246

**Comment by tarunzoot** [comment]
you can put `#![windows_subsystem = "windows"]` on the first line of your app, this should hide the console window

**Comment by rjwittams** [comment]
This exists. Use WindowSizePolicy::Content. However it doesn't currently interact well with resizing (an enhancement would be to initially size from content, then allow resizing, maybe open a new issue for that if it is what you want).

**Comment by Zenthae** [comment]
thanks, if anyone's looking for this too, only available on the master branch of the git repo, i was looking for the option on the doc but it's "outdated" since it's not taking into account new push

**Comment by cmyr** [comment]
Correct, this was added quite recently and isn't in a published version yet.

**Comment by Zenthae** [comment]
by the way, is it possible to add a new example or update an old one with this feature ? i can't make it work

**Comment by rjwittams** [comment]
Probably best to look at the Dropdown examples in the nursery repository which is the only thing that uses it right now.

**Comment by Zenthae** [comment]
if you are talking about this example https://github.com/linebender/druid-widget-nursery/blob/master/examples/dropdown.rs i can't see anything related to `WindowSizePolicy::Content`

**Comment by rjwittams** [comment]
It is in the dropdown.rs itself in the main src directory. I think asking on Zulip for this type of thing is a good idea. Its likely that there are widgets you can put as a window root which will respond with "bad" sizes that this doesn't handle well at the moment.

**Comment by Zenthae** [comment]
well, at least, this isn't working, which i don't understand why
```rust
#[derive(Debug, Default, Data, Clone, Lens)]
struct AppState {}

fn ui_builder() -> impl Widget<AppState> {
    Padding::new(5., Label::new("Hello Bluetooth monitor"))
}

fn main() -> windows::Result<()> {
    let main_window = WindowDesc::new(ui_builder())
        .title("Bluetooth Monitor")
        .window_size_policy(WindowSizePolicy::Content);

    AppLauncher::with_window(main_window)
        .use_simple_logger()
        .launch(AppState::default())
        .expect("Failed to start the app");

    Ok(())
}
```
