### ISSUE TITLE
How to hide cmd window when running gui?

### ISSUE THREAD

**Issue by zhoujun681** [linebender/druid#1568]
Its always show a cmd windows in back,
Is anyone konws how to hide cmd window when running gui?

**Comment by tarunzoot** [comment]
you can put #![windows_subsystem = "windows"] on the first line of your app, this should hide the console window

**Comment by Zenthae** [comment]
little improvement
```rust
// Switch to "windows" mode to hide the console in release version
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
```

**Comment by Finnerale** [comment]
It would probably make sense to add this to the docs.

**Comment by cmyr** [comment]
I'm definitely happy to have this written down but I'm not sure exactly where?

**Comment by Zenthae** [comment]
You could start by adding it in the examples while telling what it do ?

**Comment by cmyr** [comment]
That sounds reasonable.
