### ISSUE TITLE
Wrong font weight when using Source Han Sans font

### ISSUE THREAD

**Issue by Steve-xmh** [linebender/druid#1573]
I've checked my font family are of fonts with different weight. But they only displayed as regular weight. (Only `SUBHEADER` in code below displayed correctly)
```rust
// font is a FontFamily using Source Han Sans
// typography is consist of constast keys
env.set(
    typography::SUBHEADER,
    FontDescriptor::new(font.clone())
        .with_size(34.)
        .with_weight(FontWeight::EXTRA_LIGHT),
);
env.set(
    typography::HEADER,
    FontDescriptor::new(font.clone())
        .with_size(46.)
        .with_weight(FontWeight::EXTRA_LIGHT),
);

env.set(
    typography::TITLE,
    FontDescriptor::new(font.clone())
        .with_size(24.)
        .with_weight(FontWeight::EXTRA_LIGHT),
);

env.set(
    typography::CAPTION,
    FontDescriptor::new(font.clone())
        .with_size(12.)
        .with_weight(FontWeight::LIGHT),
);
env.set(
    typography::CAPTION_ALT,
    FontDescriptor::new(font.clone())
        .with_size(13.)
        .with_weight(FontWeight::LIGHT),
);
env.set(
    typography::BODY,
    FontDescriptor::new(font.clone())
        .with_size(14.)
        .with_weight(FontWeight::LIGHT),
);
env.set(
    typography::SUBTITLE_ALT,
    FontDescriptor::new(font.clone())
        .with_size(18.)
        .with_weight(FontWeight::LIGHT),
);
env.set(
    typography::SUBTIELE,
    FontDescriptor::new(font.clone())
        .with_size(20.)
        .with_weight(FontWeight::LIGHT),
);
env.set(
    typography::BASE,
    FontDescriptor::new(font.clone())
        .with_size(14.)
        .with_weight(FontWeight::REGULAR),
);
env.set(
    typography::BASE_ALT,
    FontDescriptor::new(font.clone())
        .with_size(14.)
        .with_weight(FontWeight::SEMI_BOLD),
);
```
Which looks like:
![image](https://user-images.githubusercontent.com/39523898/107314617-fcfac700-6acf-11eb-88d3-4c65accd7324.png)

**Comment by cmyr** [comment]
@Steve-xmh did you end up resolving this? Actually using custom fonts is something that was implemented in piet, but I don't know if anyone has ever actually tried it in druid, so it's possible something is broken. :)

**Comment by Steve-xmh** [comment]
> @Steve-xmh did you end up resolving this? Actually using custom fonts is something that was implemented in piet, but I don't know if anyone has ever actually tried it in druid, so it's possible something is broken. :)

I fixed, is my mistake that i forgot to set up the key string from copy-paste :P

But i think the font should have a group of font family to choose a suitable font like a string contains different languages (Chinese and english for me)

**Comment by cmyr** [comment]
@Steve-xmh eventually it would be nice to support manual font fallback so you can specify the order we go to fonts when looking for missing glyphs, but this is hard to do in a good cross-platform way. :(

**Comment by Steve-xmh** [comment]
> @Steve-xmh eventually it would be nice to support manual font fallback so you can specify the order we go to fonts when looking for missing glyphs, but this is hard to do in a good cross-platform way. :(

It doesn’t matter, hope this feature will come up soon :D
