### ISSUE TITLE
Overlay Widgets

### ISSUE THREAD

**Issue by raymanfx** [linebender/druid#1577]
One thing I'm missing in Druid right now is overlay type widgets. Common widgets that fit into this category are picklists, but also modal widgets. As a visual example, this is the `material.io` example overlay widget [1]:

[<img src="https://lh3.googleusercontent.com/djK1rThQ30yU32azhWve0J0rMUkJLzPnitUbEwYf5Hnf5MZgmmFlY-LbGj6n51UeyroPUywoqirccgyzAPAaNNCl0gKMqmqCsnA5Dg=w1064-v0">](material.io)

Now I guess https://github.com/linebender/druid/issues/429 (modal widgets) is related, but I'm not entirely sure whether it's the same thing. A full blown modal is a window that requires immediate attention and usually has buttons or other methods of control flow alteration (OK/Cancel/..). The example I linked in [1] is more of a 'simple' popover widget: you press a button and the list pops up. I guess it's technically just a `Scroll<List<Button>>`, since each element can be clicked to provoke an action.

Please let me know what you think.

**EDIT 1**
Some work for dropdown menus, modal widgets etc. has been done here: https://github.com/rjwittams/druid/commits/sub-window, but not merged back into upstream Druid (this repo). The current state of affairs is unclear, but I guess it would require some amount of work to rebase it onto the current HEAD.

[1] https://material.io/components/menus#dropdown-menu

**Comment by Ciantic** [comment]
Have you tried the dropdown in nursery? https://github.com/linebender/druid-widget-nursery

Before websites we just did these with separate windows, which I think is a nicer way to do these than overlay on others. But I can see Overlay Widgets as useful too if they are not out of scope.

**Comment by rjwittams** [comment]
That branch of mine is all merged from a separate squashed branch. 
I'm not sure if this issue really makes much sense given that subwindows do work in master, but specific widgets need to be written to use them. 
I'm sure there will be improvements to make once more experience is gathered from using subwindows.
