### ISSUE TITLE
Low framerate on Windows GUI (Nvidia GSync)

### ISSUE THREAD

**Issue by chrisheib** [linebender/druid#1579]
I'm not sure if this is a duplicate of #85 but it seemed to be different enough for me to open a new issue.

When I use my Druid App (https://github.com/chrisheib/wavers-client-gui) I experience massive drops in framerate whenever the main window is in focus.

I am using Nvidia GSYNC. That could probably adjust the displayed frames to the framerate thats reported by druid, resulting in massively visible low framerate on the entire monitor. I have the same problem with a few java apps that handle the drawing of their widgets on their own, but all native apps work flawlessly.

Is there a way to set a kind of 'minimal framerate' for druid, or just set the framerate to the default windows framerate, even if there is no state update?

**Comment by raphlinus** [comment]
We just use the standard Windows mechanisms for this - here's the [WM_PAINT handler](https://github.com/linebender/druid/blob/master/druid-shell/src/platform/windows/window.rs#L716) which as you can see just does a DXGI [Present1](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgiswapchain1-present1). To track this down will require some tracing, probably using ETW, to see where the slowdowns are coming from.

**Comment by chrisheib** [comment]
I'm not sure if something is slow somewhere or if WM_PAINT doesn't get added to the queue frequently enough. If it's only called 20 times a second, I think the GSync magic turns the monitor display rate down to 20hz, resulting in stuttering, regardless of how long each call takes.

**Comment by Ciantic** [comment]
I've noticed that my Google Chrome triggers the gsync sometimes too and the framerates seem to slow down. I had to disable the GSync windowed mode because of this.

**Comment by chrisheib** [comment]
```
struct TimerWidget {
    fps_timer_id: TimerToken,
}

impl Widget<DruidState> for TimerWidget {
    fn event(&mut self, ctx: &mut EventCtx, event: &Event, data: &mut DruidState, _env: &Env) {
        match event {
            Event::WindowConnected => {
                self.fps_timer_id = ctx.request_timer(Duration::from_millis(10));
            }
            Event::Timer(id) => {
                if *id == self.fps_timer_id {
                    self.fps_timer_id = ctx.request_timer(Duration::from_millis(10));
                    ctx.window().invalidate();
                }
            }
            _ => (),
        }
    }
}
```

This seems to stop the stuttering. CPU usage goes up a few % when moving the mouse over the windows tho, but I'm fine with that as long as my windows doesn't stutter.

**Comment by markijohn** [comment]
Yes. I also use gsync and I have this problem. This problem has no pattern but especially when the TextBox has focus. Then move the window around and the sometime lag disappears.

**Comment by Ciantic** [comment]
@chris-zen Did you try `ctx.request_paint()`? It's used to e.g. redraw only the blinking cursor in Textbox: https://github.com/linebender/druid/blob/master/druid/src/widget/textbox.rs#L346

**Comment by chrisheib** [comment]
@Ciantic if I just replace the invalidate with request paint the stuttering comes back unfortunately :( 
Maybe because nothing changed and therefore nothing gets invalidated and redrawn.
I could try to draw a pixel and change its color from #ffffff to #fefefe every 10ms or something, but that would be even more hacky then the above solution.

**Comment by chris-zen** [comment]
@Ciantic this is the code that I was using (the commented one):
https://github.com/chris-zen/kiro-synth/blob/master/kiro-synth-host/src/ui/view/mod.rs#L25-L57

**Comment by Ciantic** [comment]
Apologies, as you may have noticed I have auto-completed different Chris with your nick!

**Comment by chris-zen** [comment]
@Ciantic no worries.

**Comment by Jieiku** [comment]
I have not noticed this issue in the [Lapce](https://github.com/lapce/lapce) editor, maybe this has been resolved?

**Comment by xStrom** [comment]
I have never experienced Druid specific issues with any of my four G-Sync displays (I have 2 with the module, 2 are G-Sync compatible).

What I have experienced is just plain old Nvidia driver issues. G-Sync is just straight up broken with some driver versions, and G-Sync window mode is broken with even more versions. So various issues, including low framerate, does happen - but not exclusively with Druid - with absolutely everything, even mundane stuff like File Explorer.

Given the slowdown of reports in this thread, combined with my own G-Sync experiences, I think I'll call this a Nvidia driver problem for now and close this issue.

If anyone has new evidence, please post it and we'll reopen the issue.
