### ISSUE TITLE
unimplemented function

### ISSUE THREAD

**Issue by Zenthae** [linebender/druid#1589]
Can't use `WindowSizePolicy::Content` on windows until https://github.com/linebender/druid/blob/master/druid-shell/src/platform/windows/window.rs#L1661-L1664 is implemented

**Comment by HoNile** [comment]
I think it's better to continue here than in the merge PR.

Reminder:

> 
> 
> > @Zenthae did you have an example to reproduce this ? Myself I test using WindowSizePolicy::Content, with no size set on the tree example from nursery and it work fine.
> 
> it's the beginning of a new app i'm doing. i used this as a test
> 
> ```rust
> use druid::{
>     widget::{Label, Padding},
>     AppLauncher, Data, Lens, Widget, WindowDesc, WindowSizePolicy,
> };
> 
> #[derive(Debug, Default, Data, Clone, Lens)]
> struct AppState {}
> 
> fn ui_builder() -> impl Widget<AppState> {
>     Padding::new(5., Label::new("Hello Bluetooth monitor"))
> }
> 
> fn main() -> windows::Result<()> {
>     let main_window = WindowDesc::new(ui_builder())
>         .title("Bluetooth Monitor")
>         // .window_size((100.0, 40.0))
>         .window_size_policy(WindowSizePolicy::Content);
> 
>     AppLauncher::with_window(main_window)
>         .use_simple_logger()
>         .launch(AppState::default())
>         .expect("Failed to start the app");
> 
>     Ok(())
> }
> ```

So it looks like that if the window has no initial size, there is an issue, but I don't think `content_insets(&self)` should  do more than what it does I think this should be solved elsewhere. Still an easy workaround is to just set a temporary window_size.

Ex:

```
    WindowDesc::new(Padding::new(5., Label::new("Hello Bluetooth monitor")))
        .window_size((1., 1.))
        .window_size_policy(WindowSizePolicy::Content)
        .resizable(false)
```

This I think did what you want.

**Comment by Zenthae** [comment]
indeed, i just find it "sad" to have to define a size even when it should take the Content size by default.

**Comment by HoNile** [comment]
I think an okay solution could be to change `window_size_policy` on windows, to set the size to (1., 1.)  `if size_policy == WindowSizePolicy::Content`. (@cmyr Is it okay for you ?)

Or just handle the thing in the windows druid-shell but set the size is a `DeferredOp` so I don't know how this could be done.

I know @Ciantic want to do some refactoring on the windows druid-shell he may have a idea.

**Comment by cmyr** [comment]
yes, this sounds like a reasonable workaround.
