### ISSUE TITLE
Image example gives compile error on ImageBuf::from data

### ISSUE THREAD

**Issue by Dimev** [linebender/druid#1590]
I'm trying the image example, with druid set up as follows
```
[dependencies.druid]
features = ["im", "svg", "image"]
git = "https://github.com/linebender/druid"
```
However it fails when compiling with
```
error[E0599]: no function or associated item named `from_data` found for struct `ImageBuf` in the current scope
   --> src\main.rs:163:30
    |
163 |     let png_data = ImageBuf::from_data(include_bytes!("sakura.png")).unwrap();
    |                              ^^^^^^^^^
    |                              |
    |                              function or associated item not found in `ImageBuf`
    |                              help: there is an associated function with a similar name: `from_raw`

error: aborting due to previous error
```

**Comment by jneem** [comment]
Does adding the "png" feature help? The various image formats were recently put behind features to reduce dependencies.

**Comment by Dimev** [comment]
Yup that makes it work.
Is it because the from_data assumes png, so the functionality is only implemented with that?

**Comment by jneem** [comment]
No, I just suggested png because I saw that you were trying to load a png. `ImageBuf::from_data` tries to automatically detect the image format, but it looks like you need to compile in support for at least one image format in order for that function to exist.

**Comment by Dimev** [comment]
Ah ok, should probably be documented somewhere then
I'll close the issue for now
