### ISSUE TITLE
Focus previous doesnt work on Linux

### ISSUE THREAD

**Issue by xarvic** [linebender/druid#1595]
If i press Tab inside a Textbox it focuses the next one as expected, but shift + tab does nothing.

The `KeyEvent` in `Event::KeyDown` for Tab:
```
[druid/examples/focus.rs:20] ke = KeyEvent {
    state: Down,
    key: Tab,
    code: Tab,
    location: Standard,
    mods: Modifiers(
        (empty),
    ),
    repeat: false,
    is_composing: false,
}
```

The `KeyEvent` in `Event::KeyDown` for Shift + Tab:
```
[druid/examples/focus.rs:20] ke = KeyEvent {
    state: Down,
    key: Unidentified,
    code: Tab,
    location: Standard,
    mods: Modifiers(
        SHIFT,
    ),
    repeat: false,
    is_composing: false,
}
```

I think the problem is that `HotKey::matches` uses the `key` field of `KeyEvent`, which is Unidentified if Shift is pressed.

**Comment by cmyr** [comment]
Your explanation makes sense, thanks!
