### ISSUE TITLE
Documentation for PaintContext should help you find RenderContext methods

### ISSUE THREAD

**Issue by darakshan** [linebender/druid#1610]
PaintCtx documentation says "Widgets paint their appearance by calling methods on the `render_ctx`, which PaintCtx derefs to for convenience".  These are perhaps the most important methods for the novice, but finding the documentation is not easy.

The render_ctx field is shown to have type Piet. But that only leads to type D2DRenderContext, which does not list the methods. You have to discover the `impl<'a> RenderContext for D2DRenderContext<'a>` to see how the methods are finally documented in [RenderContext](https://docs.rs/piet/0.3.1/piet/trait.RenderContext.html).

**Comment by Maan2003** [comment]
Maybe just implement `RenderContext` for `PaintCtx`.

**Comment by cmyr** [comment]
I agree this is a gotcha. Implementing `RenderContext` directly ourselves is not a terrible idea, because it would let us do things like not expose `clear` to widgets.
