### ISSUE TITLE
Unable to load a font and use it in a label (Windows)

### ISSUE THREAD

**Issue by SecondFlight** [linebender/druid#1622]
Tested on Windows 10 with the latest master (36610300).

Repo: https://github.com/SecondFlight/druid-font-repro

![image](https://user-images.githubusercontent.com/6700184/109097197-df8f4500-76ec-11eb-9adc-cb618db99629.png)

I include a font (Noto Sans Mono in this case) with

```rust
pub const FONT: &[u8] = include_bytes!("NotoSansMono-Regular.ttf");
pub const FONT_KEY: Key<FontDescriptor> = Key::new("fonts.NotoSansMono-Regular");
```

I then load it into the environment in my parent widget, like so:

```rust
fn lifecycle(&mut self, ctx: &mut LifeCycleCtx, event: &LifeCycle, data: &(), env: &Env) {
    if let LifeCycle::WidgetAdded = event {
        let mono_regular_family = ctx.text().load_font(FONT).unwrap();

        self.content = WidgetPod::new(Box::new(Padding::new(3., Child::new()).env_scope(
            move |env, _data| {
                let mono_regular = FontDescriptor::new(mono_regular_family.clone())
                    .with_weight(FontWeight::REGULAR);

                env.set(FONT_KEY, mono_regular.clone());
            },
        )));
    }
    
    // ...
}
```

Then, in a child widget, I try to use the font:
```rust
fn lifecycle(&mut self, ctx: &mut LifeCycleCtx, event: &LifeCycle, data: &(), env: &Env) {
    if let LifeCycle::WidgetAdded = event {
        self.content = WidgetPod::new(Box::new(
            Flex::column()
                .with_child(Label::new("This does have a font").with_font(env.get(FONT_KEY).with_size(15.)))
                .with_spacer(10.)
                .with_child(Label::new("This does not have a font")),
        ));
        ctx.children_changed();
    }

    // ...
}
```

I expect the first label to have a monospace font, but it has the same font as the second label.

**Comment by cmyr** [comment]
@SecondFlight hmm. Maybe try some `println`'ing down into the logic for resolving that font? In particular take a look at what's going on in `TextLayout::rebuild_if_needed`, where we call `self.font.resolve(env)`. Does the font we resolve to have the correct family name?

This will be easier to debug if you don't have many text objects active.

**Comment by SecondFlight** [comment]
It seems to, yes. Thanks for the pointer; by adding a `println`, I can see that it seems to have the correct family name. Specifically, I've added the following after the descriptor is fetched in [`TextLayout::rebuild_if_needed`](https://github.com/linebender/druid/blob/master/druid/src/text/layout.rs):
```rust
println!("{:?}", descriptor.family.clone());
```

This prints the following:
```
FontFamily(Named("Noto Sans Mono"))
```

I've also tested this against [piet#406](https://github.com/linebender/piet/pull/406) with no change. I'm out of time for now, but I'll keep digging into this when I can.

**Comment by SecondFlight** [comment]
[`set_font_family`](https://github.com/linebender/piet/blob/master/piet-direct2d/src/dwrite.rs#L352) is getting called as expected. I added these lines to the top of the function:
```rust
println!("{}", family);
println!("{:?}", range);
```

This prints:
```
Noto Sans Mono
Utf16Range { start: 0, len: 21 }
```

Now to check the font loading path...

**Comment by SecondFlight** [comment]
With my very limited Direct2D knowledge, it does seem like everything is going as expected. The font loads (or at least [RegisterFontCollectionLoader](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritefactory-registerfontcollectionloader) gives back `S_OK` in [`dwrote`](https://crates.io/crates/dwrote)). I've confirmed via `assert_eq!` that [`IDWriteTextLayout::SetFontFamilyName`](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritetextlayout-setfontfamilyname), called by [`set_font_family`](https://github.com/linebender/piet/blob/master/piet-direct2d/src/dwrite.rs#L352), also returns `S_OK`.

All the pieces appear to be functioning and in play in this example. The Direct2D samples include some custom fonts and they work, so it's not like `piet-direct2d` *can't* render custom fonts, but it sure seems like `piet-direct2d` is handwaving and not actually changing the font.

**Comment by cmyr** [comment]
It would be nice to know if this is a problem somewhere in piet, or if it's a problem somewhere in druid.

For instance: it's possible that in druid we're loading this font into a *particular* `Text` object, but then using a different `Text` object when we build the layout, and not having the font available there?

What I would check here is in `D2DTextLayoutBuilder::add_attribute_shared`: when adding this attribute, are we correctly identifying it as a custom font?

**Comment by SecondFlight** [comment]
The test case does not fail on macOS (see below). I'm hoping this is evidence that the issue is in piet, not druid.

![image](https://user-images.githubusercontent.com/6700184/109720390-02e84300-7b78-11eb-9ee0-d21448cd883f.png)
