### ISSUE TITLE
Example provided by the book does not work.

### ISSUE THREAD

**Issue by TDecki** [linebender/druid#1637]
Hello,

In the "Get started with druid" page in the book, the line

```rust
    AppLauncher::with_window(WindowDesc::new(build_ui)).launch(())?;
```

inside the example currently throws an error, as `WindowDesc::new()` requires a `Widget` not a function returning a `Widget`.

Changing the line to

```rust
    AppLauncher::with_window(WindowDesc::new(build_ui())).launch(())?;
```

fixes things.

**Comment by memoryruins** [comment]
Which version of druid are you using? I think the book tracks the stable release. The first example should work on the current stable druid `0.7` while the second example works on master.

**Comment by TDecki** [comment]
Currently using the master branch.

**Comment by cmyr** [comment]
@memoryruins has it right, the readme works for the version on crates.io, but the latest version has some changes; we'll update the readme when we do the next release.
