### ISSUE TITLE
Receiving two KeyDown events for every key press (Windows 10)

### ISSUE THREAD

**Issue by ijijn** [linebender/druid#1642]
Hi team,

First of all, thanks for all the lovely work on this amazing Druid ecosystem!

After the very recent round of changes, I'm now getting two `KeyDown` events coming in for every key press, even very short ones, so all text input and keyboard shortcuts are being doubled. There is still only one `KeyUp` event generated. This is on Windows 10.

No other events (mouse clicks, etc.) seem to be affected.

Any thoughts would be greatly appreciated.

**Comment by raphlinus** [comment]
Can repro, and doing a bit of quick bisection, it seems to be  94dfcb60, the macOS IME. I'm sure that wasn't intended to change behavior on Windows. Also doing a little quick experimentation, it manifests at the druid-shell level. I didn't dig deeper than that.

**Comment by cmyr** [comment]
Oops yes it looks like we were delivering this event in two places. Thanks!

**Comment by cmyr** [comment]
@ijijn would you like to verify that this fix works? I don't have access to a windows environment at the moment.

**Comment by ijijn** [comment]
Wow!

Thank you @raphlinus for confirming this, and for your initial detective work!

Thank you @cmyr, I can confirm that this fixes the problem! Looking forward to removing my silly workaround...

Dream team 🥇

**Comment by cmyr** [comment]
@ijijn sometimes the stars align, thanks for the issue! 🤷
