### ISSUE TITLE
How to use DelegateCtx::new_window?

### ISSUE THREAD

**Issue by actuallyexeon** [linebender/druid#1646]
I'm trying to use DelegateCtx::new_window that requires two arguments. I pass it one argument (my window variable), but then it asks me for a window description. I tried to look in the crate docs but there are no examples. Here is a snippet of my code:  
```  rust
let new_win = WindowDesc::new(ui_builder_two())
        .title("testing");
DelegateCtx::new_window(new_win, desc: // dont know what to put here);
```

**Comment by cmyr** [comment]
You probably don't want a `DelegateCtx`; it's an internal type that druid passes to methods you might implement on an `AppDelegate`, which is itself an optional and fairly obscure feature. If you're just trying to create a window and launch an application, check out some off the examples here, in the `druid/examples` directory. If you *do* want to see how the `AppDelegate` can be used, check out the `multiwin` (`multi_win`?) example, or check out the [runebender](https://github.com/linebender) code.

**Comment by actuallyexeon** [comment]
It seems like the example does not work (on git not crate). I tried implementing the multiwin code into my app but always something is undefined. I'll look at the example more closely.

**Comment by actuallyexeon** [comment]
It seems like state is also undefined...

**Comment by Maan2003** [comment]
It works for me. Which platform are you on? Does it compile? Can you explain more

here is what I did: 
```
git clone https://github.com/linebender/druid
cd druid
cargo run --example multiwin
```

**Comment by actuallyexeon** [comment]
hmm, oh... i was making a new project then copying the code. but that still does not solve my problem.

**Comment by Maan2003** [comment]
what is the problem

**Comment by actuallyexeon** [comment]
Well like not defined

**Comment by arthmis** [comment]
If you are getting any errors, could you post them here?

**Comment by cmyr** [comment]
I think the problem is with copying code from the `master` branch but then using druid at `0.7.0.` Try browsing the examples at that tag: https://github.com/linebender/druid/tree/v0.7.0/druid/examples
