### ISSUE TITLE
add WidgetID of subtree for Notification

### ISSUE THREAD

**Issue by xarvic** [linebender/druid#1675]
I am working with notifications in druid. But i need to know where the notification came from. The problem is, the source of the notification is maybe wrapped inside another widget. In addition to the source, would it also be possible to store the WidgetID of the child from whose tree the notification came from?

**Comment by xarvic** [comment]
Sorry, i'm not good at explaining things :/ 
In my case, i have a widget "A" which sends notifications. This A is wrapped inside another widget "B". B is wrapped inside a widget "C" that contains multiple widgets just like A and B. I want to know if the widget which send the notification is inside B since i don't know the ID of A. Basically i want to know the last widget the notification was passed through before reaching me.

**Comment by lisael** [comment]
I had the same issue as @xarvic. @cmyr I think it's not always practicable. In this widget hierarchy:
```
CustomWidget1
  List(1)
    CustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
      ...
    CustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
      ...
  List(2)
    CustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
    CustomWidget2
      CustomWidgetCreatedOnTheFlyByCustomWidget2
```
If any `CustomWidgetCreatedOnTheFlyByCustomWidget2` sends a `Notification` and `CustomWidget1` needs to know which List it originate from, we're stuck. The only way is for the `CustomWidget1` to keep track of the Ids of the widgets it adds to each list, and to do a lot of bookkeeping to keep track of new `CustomWidgetCreatedOnTheFlyByCustomWidget2` (`CustomWidget2` would send a notification for each new child).

The other way I see is to wrap the Lists in a dummy widget that wraps notification events in a custom event.

That's a lot of work compared to `ctx.tell_me_the_id_of_the_child_widget_that_just_sent_me_this_please()` (naming is hard)

**Comment by cmyr** [comment]
What would this look like in practice? Do we store both the "original source" as well as a separate "route" ID, where the "route" ID is updated to the ID of the current widget, each time the notification is bubbled up?

**Comment by xarvic** [comment]
> What would this look like in practice? Do we store both the "original source" as well as a separate "route" ID, where the "route" ID is updated to the ID of the current widget, each time the notification is bubbled up?

Think this is the best way to do it
