### ISSUE TITLE
Possibly useful crate: Cassowary

### ISSUE THREAD

**Issue by ckaran** [linebender/druid#1680]
I'm not sure if this is truly useful to druid or not, but a while ago I ran across the [Cassowary](https://crates.io/crates/cassowary) crate, which is a constraint solver designed for laying out UI elements.  Basically, as you change the shape of the window that your layout is in, cassowary ensures that the layout is 'reasonable', in that things line up where you want them to be.  I haven't used it, but it looks interesting, and it may be useful to druid.

**Comment by cmyr** [comment]
Thanks! Druid uses a 'box' layout model, which is an alternative to the Cassowary algorithm, so this isn't directly useful to us, but I appreciate the thought. :)
