### ISSUE TITLE
Starting an app with `WindowState::Maximized` doesn't work quite right on macOS

### ISSUE THREAD

**Issue by JarrettBillingsley** [linebender/druid#1690]
I'm on macOS 10.15.5 and using the git version of Druid (post-0.7.0).

After posting a topic and repro on Zulip, we discovered that this code properly creates a maximized window on Windows, but not on macOS. The issue is that the window *is* maximized, but the widget *layout* is not. It still thinks the window is like 400x300 pixels or something. If I then resize the window, the layout corrects itself.

```rust
use druid::*;
use druid::widget::*;

#[derive(Clone, Data, Lens)]
struct AppState {}

impl Default for AppState {
    fn default() -> Self {
        Self {}
    }
}

fn build_ui() -> impl Widget<AppState> {
    Split::columns(Label::new("Split A"), Label::new("Split B"))
    .split_point(0.5)
    .draggable(true)
    .solid_bar(true)
    .min_size(250.0, 600.0)
}

fn main() -> Result<(), PlatformError> {
    AppLauncher::with_window(
        WindowDesc::new(build_ui())
        .set_window_state(WindowState::Maximized)
    )
    .launch(AppState::default())
}
```

Screenshot of what it looks like:

![image](https://user-images.githubusercontent.com/452240/113334567-dac43f00-92f1-11eb-8bee-252d82edc9c3.png)

**Comment by JarrettBillingsley** [comment]
The problem is here:

https://github.com/linebender/druid/blob/e60b2ab26b354789aa0472969c9a0ecde99b480f/druid-shell/src/platform/mac/window.rs#L289-L301

On line 290, it correctly calls `set_window_state` which maximizes the window. But then on line 299, it calls `size` using `frame.size` which is now out of sync with the real window size.

I added the first two lines - and sorry if this is absolutely the wrong way to do it, I'm not at all familiar with how mac OS windowing works - and it worked. The first layout call now sees the correct maximized window size. 

```rust
            // set_window_state above could have invalidated the frame size
            let frame = NSView::frame(content_view);

            (*view_state).handler.connect(&handle.clone().into());
            (*view_state).handler.scale(Scale::default());
            (*view_state)
                .handler
                .size(Size::new(frame.size.width, frame.size.height));
```

**Comment by cmyr** [comment]
yep this looks good to me, feel free to PR if you want!
