### ISSUE TITLE
Creating 'always on top' windows

### ISSUE THREAD

**Issue by gymore-io** [linebender/druid#1697]
When creating windows using gui frameworks, it is often possible to make them "always on top". I can't seem to find how to achieve that using druid (that I've started using today, I'm loving it :heart:).

I think #1585 was trying to do exactly that but I did not understand the answer. I looked a bit for that `WindowLevel` but I don't think it is possible to access it from the `WindowDesc` I need to start the application.

I'm surely missing something obvious...

```Rust
WindowDesc::new(build_ui)
            .resizable(false)
            .window_size((300.0, 500.0))
            .with_min_size((300.0, 500.0))
            // I initially thought I would need something like that
            // .always_on_top(true) ??
            // OR
            // .with_level(WindowLevel::??)
```

**Comment by SecondFlight** [comment]
Are you using Druid from git@master? I don't think `WindowLevel` is in `0.7.0`.

**Comment by gymore-io** [comment]
@SecondFlight Ho no, I feel so dumb now. I got confused because `WindowLevel` existed in `0.7.0` but wasn't exposed to the public API.

I just downloaded the master branch and made my project depend on it. It still doesn't work though... Is `WindowLevel` the right thing to use to get my window 'always on top' ?

**Comment by SecondFlight** [comment]
What OS are you trying this on?

**Comment by cmyr** [comment]
Taking a quick skim through the code it looks like this probably isn't implemented yet; `WindowLevel` would be the right place to look.

**Comment by mgalos999** [comment]
Just in case anyone wanted to force this for Windows only apps. You can do it by changing `src/backend/windows/windows.rs`:
```
                match level {
                    WindowLevel::AppWindow => {
                        dwExStyle = WS_EX_TOPMOST;
                    },
```
