### ISSUE TITLE
Documentation mistake: RawLabel does not actually require `ArcStr`

### ISSUE THREAD

**Issue by TonalidadeHidrica** [linebender/druid#1705]
According to the [documentation](https://github.com/linebender/druid/blob/master/druid/src/widget/label.rs#L92), `RawLabel` requires `ArcStr`.  However, the implementation does not; instead it just requires `TextStorage`.  So I think this is a documentation mistake, isn't it?

**Comment by cmyr** [comment]
yep, I think your assessment is correct!
