### ISSUE TITLE
implementation of Default for FlexParams is invalid

### ISSUE THREAD

**Issue by andrewhickman** [linebender/druid#1708]
#1691 added a check to prevent using a flex factor less than or equal to 0.0, but `FlexParams` has `#[derive(Default)]` which allows bypassing the check with `FlexParams::default()`.

Should we remove the implemenation or does it make sense to use a value like 1.0?

**Comment by cmyr** [comment]
Great question. Before that patch, passing `FlexParams::default()` would result in a non-flex child. I think what makes the most sense is to remove the `default` impl.
