### ISSUE TITLE
Add `#[data(eq)]` shorthand attribute for `Data` derive macro

### ISSUE THREAD

**Issue by TonalidadeHidrica** [linebender/druid#1718]
In my opinion it'd be common to use `PartialEq::eq` as a shorthand implementation of `Data::same`.  Currently we can already easily derive it with `#[data(same_fn="PartialEq::Eq")]`, but it may be more user-friendly if it provides with some shorthand attribute like `#[data(eq)]`.  Do you think it's a good idea?

**Comment by cmyr** [comment]
I like this idea!

**Comment by TonalidadeHidrica** [comment]
Thank you for implementing it!  @Maan2003 @cmyr
