### ISSUE TITLE
Split cursor flickering due to layout lag w.r.t. cursor fast moves

### ISSUE THREAD

**Issue by djeedai** [linebender/druid#1725]
The `list` widget does some hit-test of the mouse over the split bar during each mouse move. When moving fast (at least on Windows 10), the hardware cursor behind much faster than the Druid layout, it can happen that the cursor briefly moves out of the bar area, and back again the next frame. Because the cursor is set for each mouse move event, this produces some flickering.

https://github.com/linebender/druid/blob/5958963a05c18c7943256fb8724f7637bd524e8e/druid/src/widget/split.rs#L304-L313

The cursor should instead be locked when the bar is active (mouse down) and reset when it becomes inactive (mouse up). I've implemented a fix and it looks nicer, closer to the behavior of other controls like a scroll bar knob being dragged even if the mouse is not perfectly hovering it.

**Comment by PoignardAzur** [comment]
I think this issue can be closed?

**Comment by PoignardAzur** [comment]
I tested the split example and I think the PR fixed the problem. Closing this issue.
