### ISSUE TITLE
With show_titlebar(false), the window can't be minimized from the taskbar

### ISSUE THREAD

**Issue by ngugcx** [linebender/druid#1738]
```
    let main_window = WindowDesc::new(make_ui())
        .show_titlebar(false)
        .window_size((720., 600.))
        .with_min_size((620., 300.))
        .title("Flex Container Options");
```

After adding "show_titlebar(false)" to the flex demo, the window can't be minimized on Winodws when clicking the taskbar icon.

rust: 1.51.0 (2fd73fabe 2021-03-23)
druid: master (commit e0715c11eaaeb80ff790336f78895018b0dcb40f)
OS: Winodws 10

**Comment by SecondFlight** [comment]
Reproduced on Windows 10 with Druid@master, same commit (latest as of writing). Thanks for the report!

**Comment by SecondFlight** [comment]
This behavior is correct when `show_titlebar` is true.

**Comment by yokunjon** [comment]
I was checking out this and found out removing WS_MINIMIZEBOX flag in platform/windows/window.rs is the reason. I'm using Windows 10 and not removing that doesn't bring out the titlebar or minimize button.

Electron uses it to implement BrowserWindow.minimizable, default being true using WS_MINIMIZEBOX. Also saw an issue from 2014 in electron repo about minimization animation not firing related to WS_MINIMIZEBOX not being present.

While not removing WS_MINIMIZEBOX from dwStyle isn't breaking anything in Windows 10, I don't know about earlier versions.

**Comment by ngugcx** [comment]
Tested on Windows 7 sp1 and Windows 10, adding the WS_MINIMIZEBOX flag fixed this problem, but did not find that it caused other problems.
