### ISSUE TITLE
Menu bar transparent in Ubuntu 21.04

### ISSUE THREAD

**Issue by arifd** [linebender/druid#1745]
`cargo run --example textbox` produces a transparent menu bar in Ubuntu 21.04.

The picture may look okay when embedded in this comment with a white background, but the pixels are actually transparent

![screenshot](https://i.imgur.com/IkAFN3Q.png)

Note, the dropdown that appears when a menu title is clicked on is fine.

**Comment by cmyr** [comment]
Hmm, no clue what's going on here. Thanks!

**Comment by raymanfx** [comment]
I can confirm this on Ubuntu 20.10. It seems to be related to focus change events: when the window is *not* focused, the menu bar is fully opaque. Once the window gains focus again, the bar becomes transparent.

**Comment by ruffson** [comment]
This happens to me right after I upgraded to Fedora 34, I thought it has to do with the change to Gnome 40/Gtk4 but it seems that something else is the reason if this is happening on Ubuntu too.

**Comment by arifd** [comment]
It's a Wayland thing.

This is what happens when I run it with 'Ubuntu on Xorg'

![image](https://user-images.githubusercontent.com/2345750/117450294-53499b80-af41-11eb-9e58-594cd196c73f.png)

(note, not sure if it's meant to be black with a dark grey font)

**Comment by raymanfx** [comment]
It is *not* a Wayland only thing. Click outside of that window (so it loses focus) and watch the color of the menubar change from black to grey-ish with the default theme.

I actually thought this "black" bar was the transparent bar that you described in this issue initially. But it looks like there's an issue in both X11 and Wayland, just with different symptoms.

**Comment by arifd** [comment]
Ah you're right. In my case though, it becomes white when clicked away, but not transparent.

Should I edit my above post or anything?

**Comment by ruffson** [comment]
So we still don't know what is causing it, what is the thing that all our setups have in common.

The place where the `menubar` is set up is [here](https://github.com/linebender/druid/blob/ac3e0a6601fabeefa56c1ca7f6e4f4096febf4b5/druid-shell/src/platform/gtk/menu.rs#L128). 
And according to [this](https://developer.gnome.org/gtk4/stable/ch41s02.html#id-1.7.4.4.74) guide, `GtkMenu`, `GtkMenuBar` and `GtkMenuItem` will be gone in gtk4, maybe this is already a problem with a current libgtk3 change?

In any case, maybe it would be a good idea to try the new UI items which already work with gtk3.

**Comment by raymanfx** [comment]
Okay, so first things first I think it makes sense to update the first post with our updated findings:

- Wayland: menu bar is transparent
- X11: menu bar is black with grey font, changes back to normal once the window loses focus

Next, I agree with @ruffson that the best way to fix this may be to just try to switch to the new `GtkPopoverMenu` way of things. The GTK migration guide has a stanza on this: https://developer.gnome.org/gtk4/stable/ch41s02.html#id-1.7.4.4.74.
Let's take this to Zulip for better coordination. I'll open a new stream for this topic.

**Comment by Maan2003** [comment]
for future readers, [Zulip Topic link](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/druid.231745)
