### ISSUE TITLE
the readme.md example is not building

### ISSUE THREAD

**Issue by hammsvietro** [linebender/druid#1748]
after copying the README.md example in a new cargo project, using druid 0.7.0, I get  the following error:

```
error[E0277]: expected a `FnOnce<()>` closure, found `impl druid::Widget<u32>`
   --> src/main.rs:5:39
    |
5   |     let main_window = WindowDesc::new(ui_builder());
    |                                       ^^^^^^^^^^^^ expected an `FnOnce<()>` closure, found `impl druid::Widget<u32>`
    | 
   ::: /home/hvm/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-0.7.0/src/app.rs:347:28
    |
347 |         F: FnOnce() -> W + 'static,
    |                            ------- required by this bound in `WindowDesc::<T>::new`
    |
    = help: the trait `FnOnce<()>` is not implemented for `impl druid::Widget<u32>`
    = note: wrap the `impl druid::Widget<u32>` in a closure with no arguments: `|| { /* code */ }`
```

**Comment by chanble** [comment]
you should run this example  [https://github.com/linebender/druid/tree/v0.7.0](url)

**Comment by xarvic** [comment]
druid recently changed the signature of `WindowDesc::new()`. In druid 0.7 it needs a function to build the widget later. In the latest commit it just needs the widget. Since you are using druid 0.7 you need to remove the () brackets after `ui_builder`.

**Comment by hammsvietro** [comment]
thanks! but shouldn't the readme example be in sync with the version it's refering to?

**Comment by SecondFlight** [comment]
I may read it differently from you, but I don't believe the readme states or implies that the example uses `0.7.0`. The closest I see is this:

    ...Druid is available on [crates.io] and should work as
    a lone dependency (it re-exports all the parts of `druid-shell`, `piet`, and `kurbo`
    that you'll need):

    ```toml
    druid = "0.7.0"
    ```

    Since Druid is currently in fast-evolving state, you might prefer to drink from
    the firehose:

    ```toml
    druid = { git = "https://github.com/linebender/druid.git" }
    ```

This doesn't read to me as preferring one or the other, and it occurs below the example. It is the only mention of 0.7.0 I see.

Still, if you think this could be clearer, feel free to PR!
