### ISSUE TITLE
Selection of centered text is wrongly positioned

### ISSUE THREAD

**Issue by CryZe** [linebender/druid#1767]
![https://i.imgur.com/bfgdNQg.gif](https://i.imgur.com/bfgdNQg.gif)

(Also it seems like text that is too long is wrongly clipped (by like 1 pixel))

This is on 8e83610d19f1ccdbd3ebaacde98c189f2bfeffca (recent master)

**Comment by cmyr** [comment]
Mm, it looks like maybe the selection is being adjusted by a padding value unnecessarily? Just guessing...
