### ISSUE TITLE
Copyright Headers

### ISSUE THREAD

**Issue by hello350** [linebender/druid#1768]
Where are the copyright headers for this project? I want to use this but I can't comply with the license.

**Comment by raphlinus** [comment]
Druid is licensed under the Apache 2.0 license. This license is permissive and there is a massive quantity of software shipped with dependencies on Apache 2.0 libraries. It is extremely unusual for people not to be able to comply.

**Comment by hello350** [comment]
I thought Apache 2.0 required the copyright to be kept

**Comment by cmyr** [comment]
And for the record the license is in the usual place: the [`LICENCE`](https://github.com/linebender/druid/blob/master/LICENSE) file in the root of the repository.
