### ISSUE TITLE
Adding Debug implementations or derive Debug for Env

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1778]
From what I can tell, I think `Debug` for `Env` can be derived. Is there any reason it shouldn't have a debug implementation?

**Comment by cmyr** [comment]
The only one I can think of is that the output might be really long?

**Comment by arthmis** [comment]
Are there any details that should be left out of the debug information. Is the localization information important? If it isn't, then I can write an implementation that only displays the key value pairs.

**Comment by cmyr** [comment]
For localization it might be nice to just show a summary of the loaded locales? I'm not sure how verbose the `Debug` impl is on that, currently. I'm also not sure how easy it would be to customize, though..

**Comment by arthmis** [comment]
Ok I'll just put the whole thing in for now, and see how that goes
