### ISSUE TITLE
[Question]How to construct a dynamic Svg ?

### ISSUE THREAD

**Issue by TENX-S** [linebender/druid#1783]
I  can construct a dynamic `Label` by :
```rust
Label::new(|data: &AppData, _: &_| { ... })
```

How can I construct a dynamic `Svg` like that ? Or How can I change the `SvgData` to respond some events ?

**Comment by xarvic** [comment]
This is not exactly Svg, but you can use the Painter to draw arbitrary shapes:
```rust
use druid::widget::Painter;
use druid::kurbo::BezPath;
use druid::RenderContext;

let widget = Painter::new(|ctx, data: &mut _, env: &Env|{
    let mut path = BezPath::new();
    path.move_to((0.0, 0.0));
    path.line_to((1.0, 1.0));
    quad_to((1.0, 0.0), (0.0, 1.0));
    ctx.stroke(path, &Color::BLACK, 2.0);
});
```

**Comment by cmyr** [comment]
I don't believe we currently support dynamic Svg data. This should be possible with a custom widget, though?

**Comment by akshay1992kalbhor** [comment]
This might be a little off-topic but does druid have a widget like 'Canvas' from Tkinter, which can be used to draw shapes and text?

**Comment by SecondFlight** [comment]
Custom Druid widgets are essentially canvases. You can create one with this boilerplate:

```rust
pub struct MyWidget<T> {
    phantom_t: PhantomData<T>,
}

impl<T> Default for MyWidget<T> {
    pub fn default() -> MyWidget {
        phantom_t: PhantomData
    }
}

impl<T: Data> Widget<T> for MyWidget<T> {
    fn event(&mut self, _ctx: &mut EventCtx, _event: &Event, _data: &mut T, _env: &Env) {}

    fn lifecycle(&mut self, _ctx: &mut LifeCycleCtx, _event: &LifeCycle, _data: &T, env:_ &Env) {}

    fn update(&mut self, _ctx: &mut UpdateCtx, _old_data: &T, _data: &T, _env: &Env) {}

    fn layout(&mut self, _ctx: &mut LayoutCtx, bc: &BoxConstraints, _data: &T, _env: &Env) -> Size {
        bc.max()
    }

    fn paint(&mut self, ctx: &mut PaintCtx, _data: &T, _env: &Env) {
        let rect = ctx.size().to_rect();
        ctx.fill(rect, &Color::RED);
        // More paint calls here...
    }
}
```

Then you can use it by just adding it into your widget tree:

```rust
Flex::column().with_child(MyWidget::default())
// ... or however you lay out your widgets
```

I didn't check if this compiles, but it should be at least mostly correct.

You can do a lot more with custom widgets. [Here's a simple example](https://docs.rs/druid/0.7.0/src/druid/widget/sized_box.rs.html#129) of a custom container widget with a child. Each child of a custom widget should be in a `WidgetPod`, and the parent must pass all `event`, `lifecycle`, `update`, `layout` and `paint` calls to its child. The `WidgetPod` will take care of filtering those calls and making sure the right things get through to the child, as well as housekeeping work such as generating lifecycle events.

Hope this is helpful. Please let me know if you have any other questions!

**Comment by akshay1992kalbhor** [comment]
Thanks! Thats exactly what I wanted: a custom Widget.

**Comment by TENX-S** [comment]
> Custom Druid widgets are essentially canvases. You can create one with this boilerplate:
> 
> ```rust
> pub struct MyWidget<T> {
>     phantom_t: PhantomData<T>,
> }
> 
> impl<T> Default for MyWidget<T> {
>     pub fn default() -> MyWidget {
>         phantom_t: PhantomData
>     }
> }
> 
> impl<T: Data> Widget<T> for MyWidget<T> {
>     fn event(&mut self, _ctx: &mut EventCtx, _event: &Event, _data: &mut T, _env: &Env) {}
> 
>     fn lifecycle(&mut self, _ctx: &mut LifeCycleCtx, _event: &LifeCycle, _data: &T, env:_ &Env) {}
> 
>     fn update(&mut self, _ctx: &mut UpdateCtx, _old_data: &T, _data: &T, _env: &Env) {}
> 
>     fn layout(&mut self, _ctx: &mut LayoutCtx, bc: &BoxConstraints, _data: &T, _env: &Env) -> Size {
>         bc.max()
>     }
> 
>     fn paint(&mut self, ctx: &mut PaintCtx, _data: &T, _env: &Env) {
>         let rect = ctx.size().to_rect();
>         ctx.fill(rect, &Color::RED);
>         // More paint calls here...
>     }
> }
> ```
> 
> Then you can use it by just adding it into your widget tree:
> 
> ```rust
> Flex::column().with_child(MyWidget::default())
> // ... or however you lay out your widgets
> ```
> 
> I didn't check if this compiles, but it should be at least mostly correct.
> 
> You can do a lot more with custom widgets. [Here's a simple example](https://docs.rs/druid/0.7.0/src/druid/widget/sized_box.rs.html#129) of a custom container widget with a child. Each child of a custom widget should be in a `WidgetPod`, and the parent must pass all `event`, `lifecycle`, `update`, `layout` and `paint` calls to its child. The `WidgetPod` will take care of filtering those calls and making sure the right things get through to the child, as well as housekeeping work such as generating lifecycle events.
> 
> Hope this is helpful. Please let me know if you have any other questions!

Hi, when it comes to detailed implementation, I get a bit confused.

What I want to achieve is: when I click a button named "start", an `Svg` will appear below the button, and the button name will change to "stop", when I click "stop", the `Svg` will disappear and the button name will change to "start" again.

So this question turns into how to add/remove a widget at runtime. And thanks to this [reply](https://github.com/linebender/druid/issues/1728#issuecomment-827942377). I seem to know where to start coding. And that's the problem, I don't know how to implement `layout`, 'paint' for :
```rust
struct MyParent {
    children: Vec<WidgetPod<T, dyn Widget<T>>>,
}
```

**Comment by truelossless** [comment]
> What I want to achieve is: when I click a button named "start", an Svg will appear below the button, and the button name will change to "stop", when I click "stop", the Svg will disappear and the button name will change to "start" again.

You can use the [Either widget](https://docs.rs/druid/0.7.0/druid/widget/struct.Either.html) to do that.
Something like
```rust
Either::new(
    |data: &MyData, _| data.is_visible, // condition
    Svg::new(svg_data), // true branch
    SizedBox::empty() // false branch, use this to not display anything
);
```
Or you can use the Maybe widget and have `is_visible ` be an Option<()>. (the 0.7 docs don't have the widget so you'll have to use `cargo doc --open` with druid's master for the doc). You can then do

```rust
Maybe::or_empty(|| Svg::new(svg_data)).lens(MyData::is_visible);
```

If you want to display some kind of spinner there's already a [widget](https://docs.rs/druid/0.7.0/druid/widget/struct.Spinner.html) for that btw.

> So this question turns into how to add/remove a widget at runtime. And thanks to this reply. I seem to know where to start coding. And that's the problem, I don't know how to implement layout, paint

Why do you need to store an arbitrary number of elements in your custom widget? Unless you want to build some sort of container yourself I don't think it is a good idea (I feel like `layout` is going to be hard to express indeed). Maybe use a [List](https://docs.rs/druid/0.7.0/druid/widget/struct.List.html) if you can ?

I think what you want is building your custom SVG widget and then using the regular widget composition :smile:

**Comment by xarvic** [comment]
For the Button you can do this:

```rust
Button::new(Label::dynamic(|data: &YourData, _|if data.is_visible {"Stop"} else {"Start"}.to_string()))
    .on_click(|data: &mut YourData| { data.is_visible = !data.is_visible; })
```

**Comment by TENX-S** [comment]
That's exactly what I want ! Thank you !@truelossless @xarvic
