### ISSUE TITLE
Question: centering window and light theme

### ISSUE THREAD

**Issue by gko** [linebender/druid#1800]
Hello,

Thank you for `druid`.

Is this a proper way to center a window?
```rust
use druid::widget::Label;
use druid::{AppLauncher, PlatformError, Point, Screen, Size, Widget, WindowDesc};

fn build_ui() -> impl Widget<()> {
    Label::new("")
}

fn main() -> Result<(), PlatformError> {
    let window_size = Size {
        width: 500.0,
        height: 100.0,
    };

    if let Some(primary_display) = Screen::get_monitors()
        .iter()
        .find(|monitor| monitor.is_primary())
    {
        let main_window = WindowDesc::new(build_ui())
            .set_position(Point {
                x: primary_display.virtual_work_rect().center().x - window_size.width / 2.0,
                y: primary_display.virtual_work_rect().center().y - window_size.height / 2.0,
            })
            .window_size(window_size);

        AppLauncher::with_window(main_window)
            .launch(())
            .expect("failed to launch");
    }

    Ok(())
}
```

And is there any way to set a light theme without setting each color?
By default it is a dark theme: https://github.com/linebender/druid/blob/99a8d6638833752a1a0f343af31f0da9804a1407/druid/src/theme.rs#L120-L185

**Comment by xarvic** [comment]
> Is this a proper way to center a window?

I could not think of a better one right now.

> And is there any way to set a light theme without setting each color?

Not at the moment, but theming is being worked on.

**Comment by SecondFlight** [comment]
It's worth noting that Wayland doesn't allow top-level windows to be positioned. You can still position subwindows relative to their parent windows in Wayland. See here for more info: https://gitlab.freedesktop.org/wayland/wayland/-/issues/183

**Comment by santokalayil** [comment]
For positioning window to the center of screen I have used this code. Here I kept the window size to half of the screen size and placed in the 1/4 position of the screen
```
    let main_window = WindowDesc::new(build_root_widget).title(WINDOW_TITLE).window_size(
        (druid::Screen::get_display_rect().size() / 2.0)
        .to_vec2()
    )
    .set_position((druid::Screen::get_display_rect().size() / 4.0).to_vec2().to_point(),)
    .show_titlebar(false);
```
