### ISSUE TITLE
gtk: Unsound call to std::str::from_utf8_unchecked

### ISSUE THREAD

**Issue by psychon** [linebender/druid#1814]
This line calls `std::str::from_utf8_unchecked`: https://github.com/linebender/druid/blob/057f9f9bbf529c6fd60f00afaa8494fa3a7a4300/druid-shell/src/platform/gtk/clipboard.rs#L68

The given data is directly provided by the library user, thus making it trivial to violate the [safety contract](https://doc.rust-lang.org/std/str/fn.from_utf8_unchecked.html#safety) of this function.

**Comment by jneem** [comment]
Fixed by #1820
