### ISSUE TITLE
Single-line textboxes - features/customiisation

### ISSUE THREAD

**Issue by jjl** [linebender/druid#1833]
I am trying to customise a textbox for entry of ULIID data. They're 26 bytes of crockford base32 and if the user types an alphabet char that isn't permitted, i will transliterate for them. This is relatively easy in most toolkits but i'm having a hard job of it with druid.

Many toolkits permit a maximum length to be specified on a textbox. This one seems easy enough to implement and I can't see any downsides.

For anything else, I think there are basically two options:

1. Add callbacks, like we do with Button
2. Make it easier to figure out what a KeyEvent is actually going to do somehow *handwave*.

Thoughts?

If we can decide on a plan, I will probably find the time to implement it.

**Comment by cmyr** [comment]
Have you looked at the various examples of textbox validation? I think that should do what you need; take a look in `druid/examples/value_formatting`.

**Comment by jjl** [comment]
Ah, I'd missed this one cause it was in a subdirectory! I will take a closer look probably this weekend, but it looks promising.

PS this comment made me smile:
`//TODO: never write parsing code like this again`

**Comment by SecondFlight** [comment]
Closing as probably resolved. Feel free to comment with other questions / issues, or if this shouldn't be closed.
