### ISSUE TITLE
Add password field method to TextBox struct

### ISSUE THREAD

**Issue by dumrich** [linebender/druid#1834]
I'm trying to get password boxes to appear as little stars in my druid app. Is there a way for me to do this in the current version of Druid?

**Comment by dumrich** [comment]
Also, if it is not possible to do this in it's current state, could I make a pull request?

**Comment by Maan2003** [comment]
We had [discussion on zulip](https://xi.zulipchat.com/#narrow/stream/284299-pairing/topic/Work.20toegether.20on.20a.20.60PasswordInput.60.20Widget.3F) about password input

**Comment by cmyr** [comment]
I've put together something simple in #1839, that you can try out if you like?

**Comment by dumrich** [comment]
@cmyr I tested it out, it works great!
