### ISSUE TITLE
NSMenu missing init call

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1835]
We currently only call `NSMenu::alloc()` but i think we also need to call `init(title: String)`, which is [NSMenu's only constructor](https://developer.apple.com/documentation/appkit/nsmenu).
Cacao calls [msg_send![alloc, initWithTitle:&*title]](https://github.com/ryanmcgrath/cacao/blob/trunk/src/macos/menu/menu.rs).
Not sure how to solve this since `Menu::new()`does not have a title.

_Originally posted by @kud1ing in https://github.com/linebender/druid/issues/1307#issuecomment-832937084_

Regardless of anything else discussed, we *should* be calling init, and not just alloc.

**Comment by kud1ing** [comment]
Can be closed.

**Comment by cmyr** [comment]
Thanks!

**Comment by kud1ing** [comment]
Nah. Thank @terhechte and you!
