### ISSUE TITLE
`Ctrl+A` doesn't select all text in a `TextBox`

### ISSUE THREAD

**Issue by CryZe** [linebender/druid#1854]
It seems like an implementation along those lines needs to be added, but I'm not 100% sure how to do this correctly. usize::MAX is certainly wrong and I'm not at all sure how IME works, which is the unused return type. Also I've seen that `EditSession` also just straight up has `do_action` which can handle `TextAction::SelectAll`, among all the others. So is there some duplication going on already with the other actions?!

![https://i.imgur.com/4ymt5UJ.png](https://i.imgur.com/4ymt5UJ.png)

**Comment by cmyr** [comment]
This is supposed to be handled at the IME level. On platforms that don't currently have 'real' ime, you might take a look at the `simulate_input` method in `druid-shell/src/text.rs`; here you can handle ctrl+A and dispatch `SelectAll` to the active text field.

**Comment by CryZe** [comment]
It already receives SelectAll, but SelectAll doesn't do anything on TextBoxes.

**Comment by cmyr** [comment]
do you mean `SELECT_ALL` command, or `text::Action::SelectAll`?

**Comment by CryZe** [comment]
oh I meant SELECT_ALL. Seems like that's different from SelectAll. Why is it so different from Ctrl+C, V, R and co.?

**Comment by cmyr** [comment]
yea, it's fiddly. `SelectAll` is a special text event in macOS, but copy/paste are not.

**Comment by cmyr** [comment]
I think that probably `SELECT_ALL` shouldn't be part of `fallback_do_builtin_command`, it should always be handled by the text system. 🤔

**Comment by PoignardAzur** [comment]
In any case, this still happens. I can't Ctrl+A the text in the Textbox example.
