### ISSUE TITLE
with_line_break_mode in List invalidation

### ISSUE THREAD

**Issue by lhjok** [linebender/druid#1906]
```rust
fn history_list() -> impl Widget<CalcState> {
    Flex::column()
        .cross_axis_alignment(CrossAxisAlignment::Start)
        .with_spacer(9.0)
        .with_flex_child(
            Scroll::new(List::new(make_list_item)
                .lens(CalcState::history).fix_width(541.0)).vertical(),
            1.0
        )
        .fix_size(545.0, 155.0)
        .background(theme::BACKGROUND_LIGHT)
}

fn make_list_item() -> impl Widget<CalcEvent> {
    Flex::column()
        .with_child(
            Label::dynamic(|d: &CalcEvent, _| format!("{}=", d.expression()))
                .with_line_break_mode(LineBreaking::WordWrap)
                .with_font(FontDescriptor::with_weight(
                    FontDescriptor::new(FontFamily::new_unchecked("Consolas")),
                    FontWeight::BOLD))
                .with_text_size(20.0)
                .fix_width(541.0)
        )
        .with_child(
            Label::dynamic(|d: &CalcEvent, _| d.results())
                .with_text_color(theme::PRIMARY_DARK)
                .with_line_break_mode(LineBreaking::WordWrap)
                .with_font(FontDescriptor::with_weight(
                    FontDescriptor::new(FontFamily::new_unchecked("Consolas")),
                    FontWeight::BOLD))
                .with_text_size(20.0)
                .fix_width(541.0)
        )
}
```

Edit(Maan2003): format code

**Comment by Maan2003** [comment]
@lhjok can you explain?

**Comment by lhjok** [comment]
List::new(|| Label::new().with_line_break_mode(LineBreaking::WordWrap))

Label in List is with_line_break_mode invalid, Cannot break line

I'm sorry! English ability is limited, I hope you can understand

**Comment by lhjok** [comment]
List::new(|| Label::new(text).with_line_break_mode(LineBreaking::WordWrap))

**Comment by Maan2003** [comment]
1. are you using druid from crates.io or from git repo
2. which platform/os

**Comment by Maan2003** [comment]
some screenshots will be helpful.

I am not able to reproduce

**Comment by chanble** [comment]
line break mode depend on width of parent's widget box constraints( [code](https://github.com/linebender/druid/blob/master/druid/src/widget/label.rs#L596) ). But the flex container' width is INFINITY.
-----------------------------------
希望能帮到你(Hope to help you.)

**Comment by Maan2003** [comment]
No, flex gives infinite constraint to children along major axis - height in case of `Flex::column`

**Comment by lhjok** [comment]
Both children and parents have a fixed width

**Comment by lhjok** [comment]
I'll send the code address below. You can have a look at the applet when you have time
https://github.com/lhjok/Calc-ui/blob/master/src/main.rs

**Comment by Maan2003** [comment]
I cloned the repo. your `Cargo.lock` has you locked the druid to a very old git version.
`cargo update` and fixing some simple breaking changes fixed it.

![image](https://user-images.githubusercontent.com/49202620/129439759-f8807b07-8ab0-4cbd-8421-a38a2fc51b98.png)

**Comment by lhjok** [comment]
Thank you! Indeed, it has been solved!
