### ISSUE TITLE
event viewer examples panics

### ISSUE THREAD

**Issue by Maan2003** [linebender/druid#1927]
introduced by #1908 (edit: :facepalm: mentioned wrong pr)
### steps to reproduce
`cargo r --example event_viewer`
 
<details>
<summary>backtrace</summary>
<pre><code>
thread 'main' panicked at 'TextLayout::layout_metrics called without rebuilding layout object. Text was ''', druid/src/text/layout.rs:230:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:457:5
   2: druid::text::layout::TextLayout<T>::layout_metrics
             at ./src/text/layout.rs:230:9
   3: <druid::widget::textbox::TextBox<T> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/textbox.rs:555:13
   4: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/widget.rs:251:9
   5: <druid::widget::sized_box::SizedBox<T> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/sized_box.rs:167:28
   6: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::layout::{{closure}}
             at ./src/widget/lens_wrap.rs:128:32
   7: event_viewer::<impl druid::lens::lens::Lens<event_viewer::AppState,alloc::string::String> for event_viewer::app_state_derived_lenses::text_input>::with
             at ./examples/event_viewer.rs:49:23
   8: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/lens_wrap.rs:127:9
   9: <druid::widget::controller::ControllerHost<W,C> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/controller.rs:126:9
  10: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/widget.rs:251:9
  11: druid::core::WidgetPod<T,W>::layout
             at ./src/core.rs:582:24
  12: <druid::widget::flex::Flex<T> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/flex.rs:681:38
  13: druid::core::WidgetPod<T,W>::layout
             at ./src/core.rs:582:24
  14: <druid::widget::padding::Padding<T,W> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/padding.rs:101:20
  15: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/widget.rs:251:9
  16: druid::core::WidgetPod<T,W>::layout
             at ./src/core.rs:582:24
  17: <druid::widget::flex::Flex<T> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/flex.rs:681:38
  18: <alloc::boxed::Box<dyn druid::widget::widget::Widget<T>> as druid::widget::widget::Widget<T>>::layout
             at ./src/widget/widget.rs:251:9
  19: druid::core::WidgetPod<T,W>::layout
             at ./src/core.rs:582:24
  20: druid::window::Window<T>::layout
             at ./src/window.rs:455:13
  21: druid::window::Window<T>::do_paint
             at ./src/window.rs:422:13
  22: druid::win_handler::InnerAppState<T>::paint
             at ./src/win_handler.rs:340:13
  23: druid::win_handler::AppState<T>::paint_window
             at ./src/win_handler.rs:598:9
  24: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint
             at ./src/win_handler.rs:906:9
  25: druid_shell::backend::gtk::window::WindowBuilder::build::{{closure}}::{{closure}}
             at /home/manmeet/src/druid/druid-shell/src/backend/gtk/window.rs:450:25
  26: druid_shell::backend::gtk::window::WindowState::with_handler_and_dont_check_the_other_borrows
             at /home/manmeet/src/druid/druid-shell/src/backend/gtk/window.rs:762:31
  27: druid_shell::backend::gtk::window::WindowBuilder::build::{{closure}}
             at /home/manmeet/src/druid/druid-shell/src/backend/gtk/window.rs:437:21
  28: <O as gtk::auto::widget::WidgetExt>::connect_draw::draw_trampoline
             at /home/manmeet/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/widget.rs:3747:13
</code></pre>
</details>

**Comment by cmyr** [comment]
Yea, all the textbox stuff is way too fragile 😒
