### ISSUE TITLE
Automatic theme switching.

### ISSUE THREAD

**Issue by edfloreshz** [linebender/druid#1954]
I'm working with an app made using Druid and we want to add an option for OS-aware automatic theme switching, we were thinking of implementing it ourselves but later thought, why not bring it upstream?

Is this something we could implement in Druid?

**Comment by xStrom** [comment]
Sorry for the incredibly late response. Yes, this is generally in-scope for Druid. Dark/Light, an accent color, and maybe something else too. I just recently talked a bit more about the dark/light situation in #2190. We want to have this support and in a proper way that reacts to this setting being changed while the app is running. However it might make sense to work on this after the Druid environment system has improved a bit. I think some changes are coming in a few months.

I'll close this here in favor of #2190 which has some nice screenshots. The issue remains important to us though.
