### ISSUE TITLE
Scroll should try to show the focused widget on focus change

### ISSUE THREAD

**Issue by Maan2003** [linebender/druid#1974]
Whenever focus is changed, scroll should pan to the widget with the focus. in this example when focusing the textboxes outside the viewport, scroll doesn't move
<details><summary>example to test</summary>

```rust
use druid::widget::{Flex, Padding, TextBox};
use druid::{AppLauncher, Widget, WidgetExt, WindowDesc};

pub fn main() {
    let window = WindowDesc::new(build_widget());
    AppLauncher::with_window(window)
        .log_to_console()
        .launch("".to_string())
        .expect("launch failed");
}

fn build_widget() -> impl Widget<String> {
    let mut col = Flex::column();
    for _ in 0..30 {
        col.add_child(Padding::new(3.0, TextBox::new()));
    }
    col.scroll()
}
```
</details>

**Comment by xarvic** [comment]
Maybe this could be done with a notification. Something like `ScrollTo: Selector<Rect>`. Either with global coordinates or by updating the notification with n every `WidgetPod` it is passed trough.

**Comment by Maan2003** [comment]
global coordinates should be fine. Nested `Scroll`s will be a good testcase

**Comment by xarvic** [comment]
> Maybe this could be done with a notification. Something like `ScrollTo: Selector<Rect>`.

I just noticed that `FocusChanged` is a lifecycle event, hence we can`t send Notifications. We could use Commands but this feels wrong.
