### ISSUE TITLE
Struggling to make simple, generic widgets

### ISSUE THREAD

**Issue by askoufis** [linebender/druid#1991]
Disclaimer: I'm relatively new to Rust, have read the rust book and made a moderately complicated CLI app, but that's about it. My background is primarily writing frontends in Typescript + React.

Maybe I'm going about building my UI in a weird way, but I'd like to make relatively simple widget builder functions that take `Data` that isn't tied to the app state. As an example, I'd like to have a function that takes some label text as an input, and returns a flex widget containing a `Label`, `TextBox` and a `Stepper`. I want this function to simply return an `impl Widget<f64>` because I want to use a lens to pass an `f64` field from my `AppState` into the resulting widget, and have the value appear in the textbox and be adjustable via the stepper.

Here is my rough code (excluding any nice layout and formatting).
```rust
pub fn stepper_value_field(label: impl Into<LabelText<String>>) -> impl Widget<f64> {
    let field_label = Label::new(label);

    let textbox = TextBox::new()
        .with_formatter(ParseFormatter::new())
        .lens(lens::Identity);

    let stepper = Stepper::new().with_step(10.0);

    let field = Flex::row()
        .main_axis_alignment(MainAxisAlignment::SpaceBetween)
        .with_child(field_label)
        .with_child(textbox)
        .with_child(stepper);

    field
}
```

This doesn't compile because the function is returning an `impl Widget<String>`. I'm assuming this comes from the first child of the flex widget being a `Label`, but this obviously isn't what I want. I'm assuming I'm missing something here to do with lensing the data in the right way, but it's all a bit over my head to be honest.

Looking at other druid apps, I've mostly encountered functions that just return `impl Widget<AppState>`, so I'd appreciate some guidance/clarity on whether this is an idiomatic/supported way of creating widgets with druid, or if I'm just missing something super obvious and/or undocumented.

**Comment by xarvic** [comment]
`LabelText<String>` is the problem here. 
The type parameter of LabelText is the Datatype of the Label.

You can useLabelText<f64>, String or &str instead.

**Comment by askoufis** [comment]
Thanks for the help. I went with `String` since it's the simplest to deal with of the three options and I don't need to worry about localization for now.
