### ISSUE TITLE
nested click handling

### ISSUE THREAD

**Issue by james-lawrence** [linebender/druid#1994]
just curious if anyone has a solution for clicked on a child widget with a click handler when the parent also has one.

since events propagate downwards through the widget tree there doesn't seem to be a way to allow the child to decide before the parent if it should handle a click.

**Comment by Maan2003** [comment]
The parent can let child handle the event first. This is done in Scroll. for example to let child handle the event:
```rust
fn event(....) {
    child.event(...);
    if ctx.is_handled() {
        return;
    }
    ...
}

**Comment by james-lawrence** [comment]
ah nice. I ended up using focus... but might switch to that.
