### ISSUE TITLE
[mac] How do I fully exit an app?

### ISSUE THREAD

**Issue by eric5f3759df** [linebender/druid#2008]
In druid demo running on macOS, click exit button, the window will disappered, but the icon is still on the dock. the app cannot active again.

**Comment by zwlxt** [comment]
In macOS, by default, application does not exit after closing all windows. Application itself is responsible to detect how many window left and decide to exit or not.

Most demos of druid does not implement menus, thus you cannot exit via `cmd+Q` nor top-left menu, you can only exit via right-clicking app icon at the dock, or send `Ctrl+C` in terminal.

The example `multiwin` has implemented macOS's default menu, `cmd+Q` and application's top-left menu works. It also shows how to capture windows events like `window_removed` using `AppDelegate`, in which you can exit application by calling `Application::global().quit()`
