### ISSUE TITLE
1 second delay when doing Ctrl+A

### ISSUE THREAD

**Issue by ELginas** [linebender/druid#2029]
System: Windows 10 (OS Build 19043.1288)
Reproducible on any text input field in any example  (Debug/Release)

If during that 1 second delay you update UI (by checking/unchecking checkbox or selecting different option in option box), Ctrl+A takes effect immediately.

Best example I found is image example.

**Comment by cmyr** [comment]
To me this indicates that we are not correctly requesting paint, and instead only updating when we next need to redraw the cursor.

**Comment by Maan2003** [comment]
I think it was a pending issue after #1931. But didn't open a issue
