### ISSUE TITLE
How do I automatically keep scrolling to the bottom

### ISSUE THREAD

**Issue by lhjok** [linebender/druid#2034]
No case can be queried. Thank you very much for making an example! It's been bothering me for a long time. Please reply me. Sorry for lack of experience, thank you!

**Comment by njust** [comment]
Hi, I am using a small wrapper around the Scroll widget for that:

```rust
pub enum ScrollPos {
    None,
    Bottom
}

pub struct CustomScroll<T, W> {
    child: Scroll<T, W>,
    with_scroll_pos: Box<dyn Fn(&T, &Env) -> ScrollPos>,
}

impl<T: Data, W: Widget<T>> CustomScroll<T, W> {
    pub fn new(widget: W, with_scroll_pos: impl Fn(&T, &Env) -> ScrollPos + 'static) -> Self {
        CustomScroll {
            child: Scroll::new(widget),
            with_scroll_pos: Box::new(with_scroll_pos),
        }
    }
}

impl<T: Data, W: Widget<T>> Widget<T> for CustomScroll<T, W> {
    fn event(&mut self, ctx: &mut EventCtx, event: &Event, data: &mut T, env: &Env) {
        self.child.event(ctx, event, data, env);
    }

    fn lifecycle(&mut self, ctx: &mut LifeCycleCtx, event: &LifeCycle, data: &T, env: &Env) {
        self.child.lifecycle(ctx, event, data, env);
    }

    fn update(&mut self, ctx: &mut UpdateCtx, old_data: &T, data: &T, env: &Env) {
        self.child.update(ctx, old_data, data, env);
        if !old_data.same(data) {
            let scroll = (self.with_scroll_pos)(data, env);
            match scroll {
                ScrollPos::None => (),
                ScrollPos::Bottom => {
                    let pos = self.child.child_size().height;
                    self.child.scroll_to_on_axis(Axis::Vertical, pos);
                }
            }
            ctx.request_paint();
        }
    }

    fn layout(&mut self, ctx: &mut LayoutCtx, bc: &BoxConstraints, data: &T, env: &Env) -> Size {
        self.child.layout(ctx, bc, data, env)
    }

    fn paint(&mut self, ctx: &mut PaintCtx, data: &T, env: &Env) {
        self.child.paint(ctx, data, env);
    }
}
```

**Comment by lhjok** [comment]
Thank you.

**Comment by lhjok** [comment]
Hello! If the data is not updated in time, it will always slow down by one event.

**Comment by lhjok** [comment]
> Hi, I am using a small wrapper around the Scroll widget for that:
> 
> ```rust
> pub enum ScrollPos {
>     None,
>     Bottom
> }
> 
> pub struct CustomScroll<T, W> {
>     child: Scroll<T, W>,
>     with_scroll_pos: Box<dyn Fn(&T, &Env) -> ScrollPos>,
> }
> 
> impl<T: Data, W: Widget<T>> CustomScroll<T, W> {
>     pub fn new(widget: W, with_scroll_pos: impl Fn(&T, &Env) -> ScrollPos + 'static) -> Self {
>         CustomScroll {
>             child: Scroll::new(widget),
>             with_scroll_pos: Box::new(with_scroll_pos),
>         }
>     }
> }
> 
> impl<T: Data, W: Widget<T>> Widget<T> for CustomScroll<T, W> {
>     fn event(&mut self, ctx: &mut EventCtx, event: &Event, data: &mut T, env: &Env) {
>         self.child.event(ctx, event, data, env);
>     }
> 
>     fn lifecycle(&mut self, ctx: &mut LifeCycleCtx, event: &LifeCycle, data: &T, env: &Env) {
>         self.child.lifecycle(ctx, event, data, env);
>     }
> 
>     fn update(&mut self, ctx: &mut UpdateCtx, old_data: &T, data: &T, env: &Env) {
>         self.child.update(ctx, old_data, data, env);
>         if !old_data.same(data) {
>             let scroll = (self.with_scroll_pos)(data, env);
>             match scroll {
>                 ScrollPos::None => (),
>                 ScrollPos::Bottom => {
>                     let pos = self.child.child_size().height;
>                     self.child.scroll_to_on_axis(Axis::Vertical, pos);
>                 }
>             }
>             ctx.request_paint();
>         }
>     }
> 
>     fn layout(&mut self, ctx: &mut LayoutCtx, bc: &BoxConstraints, data: &T, env: &Env) -> Size {
>         self.child.layout(ctx, bc, data, env)
>     }
> 
>     fn paint(&mut self, ctx: &mut PaintCtx, data: &T, env: &Env) {
>         self.child.paint(ctx, data, env);
>     }
> }
> ```

Hello! If the data is not updated in time, it will always slow down by one event.

**Comment by lhjok** [comment]
Seems on_click event, first trigger scroll update, and then execute on_click event, resulting in failure to update the latest data.

**Comment by lhjok** [comment]
Seems on_click event, first trigger scroll update, and then execute on_click event, resulting in failure to update the latest data.
Case address: https://github.com/lhjok/Calc-ui/blob/master/src/main.rs

**Comment by lhjok** [comment]
How to solve this problem?
