### ISSUE TITLE
Cannot quit program gracefully with exit code: 0x80000003

### ISSUE THREAD

**Issue by wspl** [linebender/druid#2062]
Just run `cargo run --example hello` on command line. Then press `Ctrl+C` to exit program. It hangs a few seconds then print:
```
error: process didn't exit successfully: `target\debug\examples\hello.exe` (exit code: 0x80000003)
```

Windows 10

**Comment by james-lawrence** [comment]
you need to wire in signal handling yourself. it'd be nice if there had a standard default that could be used. but it doesn't exist atm.

look at the [AppDelegate](https://github.com/linebender/druid/blob/master/druid/src/app_delegate.rs#L83) and [sys commands](https://github.com/linebender/druid/blob/master/druid/src/command.rs#L185).

basically create an app delegate that backgrounds a signal event loop and when you see the terminate/interrupt signal then you send the sys command to the application.

**Comment by wspl** [comment]
@james-lawrence I'm not sure about the design of druid. But it looks like AppDelegate can only handle commands and events that druid already implements.
I found crates like ctrlc and singal_hook, but have no idea how to integrate them into druid's event loop.

And I found that both iced and conrod can exit the program directly from the command line with Ctrl+C. They exit with the expected error message:
```
error: process didn't exit successfully: `target\release\examples\all_winit_glium.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```
Is this caused by an implementation difference?

**Comment by james-lawrence** [comment]
AppDelegate lets you send commands to the application. and one of those commands will quit the application. see the links I provided you.

**Comment by wspl** [comment]
@james-lawrence Depending on the rules of the Rust language, and the design of the Druid, I may not be able to pass DelegateCtx into a new thread or into a callback to receive events and send commands.

I don't know if there is any other way. If you have experience with this, can you provide a simple example? Thank you very much.

**Comment by Maan2003** [comment]
> I may not be able to pass DelegateCtx into a new thread or into a callback to receive SIGINT singal and send commands.

you need `ExtEventSink`, get this from `AppLauncher::get_external_handle`. This is `Send`

**Comment by Maan2003** [comment]
@wspl  This should work, but I can haven't tried my self.
```rust
fn main() {
   let launcher = AppLauncher::........;
   let ext = launcher.get_extern_handle();
   ctrlc::set_handler(move || {
      ext.submit_command(QUIT_APP, (), Target::Global);
  })
  launcher.launch(())
}
```

**Comment by wspl** [comment]
@Maan2003 This is great. I can now get my program to exit normally with Ctrl+C.

BTW, other programs can be exited directly by Ctrl+C. Is there a design in Druid that prevents Ctrl+C from working properly?

**Comment by Maan2003** [comment]
depend on the druid shell backend being used. for example, x11 wayland and gtk backend exit with ctrl-c properly.

**Comment by wspl** [comment]
**This issue should be taken seriously.**

If I run the druid App and its message loop in a new thread and run another infinite loop in the main thread. This will cause Ctrl+C to lose its work completely (even if handle Ctrl+C to execute QUIT_APP).

This is obviously a bug, as other frameworks such as Conrod and Iced do not have similar problems. I will try to troubleshoot the problem, but I only have very little experience with Win32 programming and this may be difficult for me.

**Comment by wspl** [comment]
This is a very simple Win32 window program. It can exit normally with `(exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)`.

So this problem is not a system mechanism problem, but Druid has something to prevent the normal exit of the program, may be the subscribing of some signal (I can't find any related code in source)

```rust
use std::ffi::OsStr;
use std::iter::once;
use std::mem;
use std::os::windows::ffi::OsStrExt;
use std::ptr::null_mut;
use winapi::shared::minwindef::{LPARAM, LRESULT, UINT, WPARAM};
use winapi::shared::windef::{HBRUSH, HWND};
use winapi::um::libloaderapi::{GetModuleHandleW};
use winapi::um::winuser::{
    BeginPaint, CreateWindowExW, DefWindowProcW, DestroyWindow, DispatchMessageW, EndPaint,
    FillRect, GetMessageW, LoadCursorW, PostQuitMessage, RegisterClassW, ShowWindow,
    TranslateMessage, COLOR_WINDOW, CW_USEDEFAULT, IDC_ARROW, MSG, PAINTSTRUCT, SW_SHOWNORMAL, WM_CLOSE, WM_DESTROY,
    WM_PAINT, WNDCLASSW, WS_OVERLAPPEDWINDOW,
};

pub fn to_widestr(str: &str) -> Vec<u16> {
    OsStr::new(str).encode_wide().chain(once(0)).collect()
}

pub unsafe extern "system" fn wndproc(
    hwnd: HWND,
    msg: UINT,
    wparam: WPARAM,
    lparam: LPARAM,
) -> LRESULT {
    match msg {
        WM_CLOSE => {
            DestroyWindow(hwnd);
            0
        }
        WM_DESTROY => {
            PostQuitMessage(0);
            0
        }
        WM_PAINT => {
            let mut ps: PAINTSTRUCT = mem::zeroed();
            let hdc = BeginPaint(hwnd, &mut ps);
            FillRect(hdc, &ps.rcPaint, COLOR_WINDOW as HBRUSH);
            EndPaint(hwnd, &ps);
            0
        }
        _ => DefWindowProcW(hwnd, msg, wparam, lparam),
    }
}

fn main() {
    unsafe {
        let cls_name = "MainWindow";

        let hinstance = GetModuleHandleW(null_mut());

        let mut wndclass: WNDCLASSW = mem::zeroed();
        wndclass.lpfnWndProc = Some(wndproc);
        wndclass.hInstance = hinstance;
        wndclass.lpszClassName = to_widestr(cls_name).as_ptr();
        wndclass.hCursor = LoadCursorW(null_mut(), IDC_ARROW);

        RegisterClassW(&mut wndclass);

        let hwnd = CreateWindowExW(
            0,
            to_widestr(cls_name).as_ptr(),
            to_widestr("MyWindow").as_ptr(),
            WS_OVERLAPPEDWINDOW,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            null_mut(),
            null_mut(),
            hinstance,
            null_mut(),
        );

        ShowWindow(hwnd, SW_SHOWNORMAL);

        let mut msg: MSG = std::mem::zeroed();
        loop {
            if GetMessageW(&mut msg, null_mut(), 0, 0) > 0 {
                TranslateMessage(&msg);
                DispatchMessageW(&msg);
            }
        }
    }
}
```

**Comment by wspl** [comment]
This question seems to be related to Piet https://github.com/linebender/piet/issues/478, so I'll close it for now.
