### ISSUE TITLE
could not find `im` in `druid`

### ISSUE THREAD

**Issue by hu76589** [linebender/druid#2080]
When compile the example "list", there is a error:
error[E0432]: unresolved import `druid::im`
  --> src\main.rs:20:12
   |
20 | use druid::im::{vector, Vector};
   |            ^^ could not find `im` in `druid`

why?

**Comment by Maan2003** [comment]
enable feature `im`

**Comment by cmyr** [comment]
yep, `cargo run --example=list --features=im` should work?

**Comment by hu76589** [comment]
like this:
[dependencies]
druid = { version = "0.7.0", features = ["im"] }
