### ISSUE TITLE
Allow change window visibility programmatically

### ISSUE THREAD

**Issue by wspl** [linebender/druid#2089]
For the visibility of the window needs to be extended:
- Allows to describe in `WindowDesc` whether the window is visible by default or not.
- `WindowHandle::show` should be allowed to be called repeatedly.
- Add `WindowHandle::hide` method to be able to hide the window.

**Comment by sjoshid** [comment]
It doesnt make sense to create a new, hidden window. So by default, a new window must always be visible. 
You can very well hide/show it after its creation. I dont know your exact requirements but I guess you want to run your app in the background. So I think this is a valid request. 
If you have fixed this please open a PR. If not, I can take it up.

**Comment by newcomb-luke** [comment]
I may try to work on this, as it can be useful for very strange projects. One of which I have.

**Comment by xStrom** [comment]
With #2191 merged this should be at least mostly supported now.

If there are specific issues with repeated calls to `WindowHandle::show` or such, that should get a new issue.
