### ISSUE TITLE
Documenting `window_min_size`

### ISSUE THREAD

**Issue by saona-raimundo** [linebender/druid#2092]
Hi all! Thank you for the crate, I have had a really nice experience so far!

As I was trying out, as a beginner, I wondered if you would accept some documentation recommendations. In particular, I would propose to document more about `window_min_size` and its default value.

Places I would put some documentation are:
- [impl Default for WindowConfig](https://docs.rs/druid/latest/druid/struct.WindowConfig.html#impl-Default)
- [WindowDesc::new](https://docs.rs/druid/latest/druid/struct.WindowDesc.html#method.new)
- [WindowDesc::with_min_size](https://docs.rs/druid/latest/druid/struct.WindowDesc.html#method.with_min_size)

And it would be something along the lines of
```
The default value is (400, 400).
```

## Maintainability of the docs

If you would like for the docs to be easier to maintain, the documentation could also be something like
```
The default value is given in `WindowConfig::default`.
```
and document the actual value only under `WindowConfig::default`.

Just for reference, the actual value is [expressed as a constant](https://docs.rs/druid/latest/src/druid/app.rs.html#27) and only used in `WindowConfig::default`. 

Once we agree on the changes, I can do the PR if you want :)

**Comment by PoignardAzur** [comment]
WINDOW_MIN_SIZE has been removed from the code. I'm making a commit to better explain how WindowDesc works.
