### ISSUE TITLE
[Question] How to specify Flex's childs' space occupation in percentage?

### ISSUE THREAD

**Issue by alexmozaidze** [linebender/druid#2098]
It's kind of a noob question but still. I have a Flex that has children, and I want to control how much space in Flex children occupy, in percentage. Is there a method for that? I was searching for a while and couldn't find anything like that.

**Comment by maurerdietmar** [comment]
Just specify the the flex value, for example:

    Flex::row()
        .with_flex_child(Label::new("test1").expand_width(), 20.) // 20%
        .with_flex_child(Label::new("test2").expand_width(), 80.) // 80 %
