### ISSUE TITLE
Text input behaves as if Shift was constantly pressed on new wayland backend

### ISSUE THREAD

**Issue by jplatte** [linebender/druid#2112]
cc @james-lawrence (let me know if you can't reproduce)

**Comment by jplatte** [comment]
Oh, now I already can't reproduce anymore myself. I'll close this and reopen if I can reproduce reliably.

**Comment by ratmice** [comment]
I think I can reliably reproduce, press the left shift, then right shift, release left shift, then right shift,
typed text should show up in caps

**Comment by james-lawrence** [comment]
confirmed, will take a look.
