### ISSUE TITLE
Codes in Readme and  Examples are outdated for version `0.7.0`

### ISSUE THREAD

**Issue by duyixian1234** [linebender/druid#2120]
[example in Readme](https://github.com/linebender/druid#example)
```rust
fn main() -> Result<(), PlatformError> {
    let main_window = WindowDesc::new(ui_builder());  // Should use `ui_builder` instead of `ui_builder()`
    let data = 0_u32;
    AppLauncher::with_window(main_window)
        .log_to_console() // Should use `use_simple_logger` instead of `log_to_console`
        .launch(data)
}
```

**Comment by jneem** [comment]
These examples are for working with the master branch instead of 0.7.0. Under the example there's a comment about this, along with a link to examples that work in `0.7.0`. Maybe we can make this more prominent somehow?
