### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [linebender/druid#2122]
Hi I have some questions regarding this project:
1. How are the main differences to [`iced`](https://github.com/iced-rs/iced) GUI library in terms of ease of use?
2. Does it use WGPU or something else?
3. Is it retained, or immediate or both?
4. Do you have a Discord Server?
5. Does `druid` have a "Lock in framework" like [`bevy`](https://github.com/bevyengine/bevy) does?

**Comment by Maan2003** [comment]
I can't answer 1.

2. Currently, direct-2d on windows, cairo on linux and core graphics on mac os.
3. very heavily retained.
4. README says [zulip](https://xi.zulipchat.com/)
5. Yes, druid forces cheaply clonable data structures for `data`. druid controls the event loop. druid locks you into `piet` renderer.

**Comment by Raj2032** [comment]
I see thanks mate :)
