### ISSUE TITLE
Multi dimension lists

### ISSUE THREAD

**Issue by Hero9909** [linebender/druid#2134]
This is more a Question than a issues.
Ive got a list of structs each contains a list of different length.
each struct is immutable. But how should i build a table of it?

the table would not contain more than just Strings. Ive got a structure in mind but stopping how i would iterate over deeper properties.

ive searched the examples but didnt found or realized what im needing, maybe something with the syntax like ViewSwitcher?

any help appreciated

**Comment by xarvic** [comment]
There is a [Table Widget](https://github.com/linebender/druid-widget-nursery/tree/master/src/table) in the nursery.

**Comment by Hero9909** [comment]
sry for the late response.
looks it looks wonderfull, I wasn't aware of this crate. would be nice if the package is published if there is a "stable" version or maybe a list of good revs. but that's another thing.

thanks again for your hint.
