### ISSUE TITLE
What does `runIdle` do?

### ISSUE THREAD

**Issue by gfreezy** [linebender/druid#2136]
https://github.com/linebender/druid/blob/53321e2a8d7fcd3a6cff57266fe604216f86a0ea/druid-shell/src/backend/mac/window.rs#L457

I can't find any documents about `runIdel`.

**Comment by cmyr** [comment]
it's an internal mechanism used to wake up the system runloop for when the application has work to do that does not originate with the runloop (for instance when an external event arrives)
