### ISSUE TITLE
issue using druid::im::{Vector}

### ISSUE THREAD

**Issue by bwintertkb** [linebender/druid#2137]
Hi guys,

I'm pretty new to rust and I've been spending some time looking at the UI options out there. This one is awesome!

I have an issue though using the druid immutable vector. I can't seem to import it.

It doesn't work if my dependency is druid = "0.7" or the repo link. 

Do you guys know how to import it? Currently going through your example files.

**Comment by Maan2003** [comment]
duplicate of #2080

**Comment by bwintertkb** [comment]
> duplicate of #2080

legend
