### ISSUE TITLE
Codebase uses approx_eq incorrectly

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/druid#2140]
The macro `approx_eq!(...)` is used in several tests in places where `assert_approx_eq!(...)` should probably be used instead. Because of this, several tests might not actually be checking anything.

Example: https://github.com/linebender/druid/blob/ac3e0a6601fabeefa56c1ca7f6e4f4096febf4b5/druid-derive/tests/with_lens.rs#L63

**Comment by cmyr** [comment]
good catch!

**Comment by PoignardAzur** [comment]
I noticed when I tried to tweak some tests in my fork, and noticed that the tests were passing even with absurd values.

**Comment by xStrom** [comment]
This was solved by #2331.
