### ISSUE TITLE
Configurable SizedBox size

### ISSUE THREAD

**Issue by GoldsteinE** [linebender/druid#2144]
I want `SizedBox` width/height to be configurable by user. I tried to do this by putting values to env and then calling `.fix_width()` with `Key<f64>`, but it only accepts plain `f64` values.

How to achieve non-static fixed widget size?

**Comment by xarvic** [comment]
You can use [EnvScope](https://docs.rs/druid/latest/druid/widget/struct.EnvScope.html) to change those vales based on the app state.

**Comment by GoldsteinE** [comment]
I sent a PR.

Should I add myself to the `AUTHORS`? It’s a small patch, but the header says “for copyright purposes”, so probably everone who made a contribution should be in it?
