### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by th4s** [linebender/druid#2150]
I wanted to politely ask what is the current status of this project and the future plans. I have been following it for 1-2 years now and was always thinking that I would like to possibly use this for some projects.

Is the plan still to further develop druid to a performant GUI library for all major OSs? Are the core contributors still involved? Is there any new release planned soon?

**Comment by cmyr** [comment]
Good question, and this should be answered more officially at some point.

The short answer is that I am currently occupied with other projects, and although I would like to return to spending more time on Druid at some point, I do not have a credible timeline.

In the near-term various contributors are continuing to hack away and make improvements and add some features, but there is not currently a roadmap or any firm plans.


My current advice would be that if you want to hack together a simple GUI app for personal use, druid can do quite a bit right now, but if you want something professional feeling you should look elsewhere. :)

**Comment by th4s** [comment]
Thanks for this update!
