### ISSUE TITLE
Enable/Disable widget on events

### ISSUE THREAD

**Issue by Blackwave81** [linebender/druid#2155]
Hi everyone, i've read many post about Enable/Disable widget in Druid, from 1 or 2 years ago.
First of all, i'm a beginner and i want to know how to do it and how the situation has evolved. 

Specifically, in my project, i want to Enable a Spinner when a thread doing a task and disable it when the thread finish tasks.
I'm trying to use a ViewSwitcher controlled by an AppState.value, but it doesn't seem to work.
Thanks in advance.

Sardina Simone

**Comment by ratmice** [comment]
Sardina, please have a look at druid/examples/blocking_function.rs which if I recall does a similar thing using the Either widget.

**Comment by Blackwave81** [comment]
@ratmice thanks for reply. Yeah, i've already saw that code and i've implemented some parts of it.
I used a Viewswitcher instead of Either but the Delegate part is almost the same. 
The only difference between mine and blocking_function, is that i don't pass any variable inside the thread through sink.submit_command, as a payload. This thing confuse me a lot also because submit command require a payload.

Furthermore blocking_function confuse me a lot because, is write all in main.rs file and i use main, view and data .rs files.

Thanks in advance.

Sardina Simone

**Comment by xarvic** [comment]
> This thing confuse me a lot also because submit command require a payload.

If you don't have a payload you can just use `()`.

> Specifically, in my project, i want to Enable a Spinner when a thread doing a task and disable it when the thread finish tasks.
I'm trying to use a ViewSwitcher controlled by an AppState.value, but it doesn't seem to work.
Thanks in advance.

And just to clarify this `ViewSwitcher` and Enable/Disable are two completely different things. Which posts do you mean?

>Furthermore blocking_function confuse me a lot because, is write all in main.rs file and i use main, view and data .rs files.

The blocking_fuction example was written as one file just for readability. It makes no difference.

**Comment by Blackwave81** [comment]
@xarvic thanks for reply. 
The function submit.command( ) require three argument, i can't use ( ) for it. Also, i want to use inside that the SELECTOR to manage AppDelegate.

Thanks in advance.

**Comment by xarvic** [comment]
My bad. What I meant to say was: You can create a `Selector<() >`. `()` carries no information therefore you get a Selector without a payload. You still have to write `() ` every time you use it but you can ignore that.

**Comment by Blackwave81** [comment]
@xarvic thanks for reply. Oh, i got it,; now it works even without a payload!
Thanks a lot Christoph.

Regards, 
Sardina Simone
