### ISSUE TITLE
Add .bmp file in the Main Window

### ISSUE THREAD

**Issue by Blackwave81** [linebender/druid#2156]
Hi, everyone, how can I add an existing .bmp file in the main window for Druid?

Thanks in advance.

Sardina Simone

**Comment by xarvic** [comment]
What does 'add' mean in this context. Do you want to drag the file into the window?

**Comment by Blackwave81** [comment]
@xarvic Thanks for replying me. Sorry i didn't make myself clear. I meant how to show an image in the main window, for example a logo at the top of it, using an existing .bmp file in the source.

Thanks in regards,

Sardina Simone
