### ISSUE TITLE
How to write a multi-layer layout like swiftui z-stack ?

### ISSUE THREAD

**Issue by kingzcheung** [linebender/druid#2166]
How to write a multi-layer layout like  swiftui z-stack ?

I looked through a lot of documentation and couldn't find a way to support cascading widgets on the z-axis.

**Comment by xStrom** [comment]
Z-order is determined by the order you paint them.

```rust
    fn paint(...) {
        widget_pod_a.paint(...); // bottom layer
        widget_pod_b.paint(...); // middle layer
        widget_pod_c.paint(...); // top layer
    }
```

**Comment by kingzcheung** [comment]
I have to custom widgets to paint them instead of using existing widgets (like Flex or TextBox), right?

**Comment by kingzcheung** [comment]
> Z-order is determined by the order you paint them.
> 
> ```rust
>     fn paint(...) {
>         widget_pod_a.paint(...); // bottom layer
>         widget_pod_b.paint(...); // middle layer
>         widget_pod_c.paint(...); // top layer
>     }
> ```


I have to custom widgets to paint them instead of using existing widgets (like Flex or TextBox), right?

**Comment by kingzcheung** [comment]
> > Z-order is determined by the order you paint them.
> > ```rust
> >     fn paint(...) {
> >         widget_pod_a.paint(...); // bottom layer
> >         widget_pod_b.paint(...); // middle layer
> >         widget_pod_c.paint(...); // top layer
> >     }
> > ```
> 
> I have to custom widgets to ‎漆‎ them instead of using existing widgets (like Flex or TextBox), right?

Sorry,i found the paint method of an existing widget.

**Comment by xStrom** [comment]
You can use existing widgets (like Flex or TextBox) inside of `WidgetPod`. Then to Z-order them, see my previous example.

**Comment by platlas** [comment]
Couldn't druid::widget::[ZStack](https://docs.rs/druid/latest/druid/widget/struct.ZStack.html#) be used here? (I'm not familiar with swiftui)
