### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [linebender/druid#2174]
Hi guys I got some questions regarding this project:
1. Am I able to integrate this into a game engine?
2. Does this crate lock you into some kind of framework like Bevy does?
3. Is there a Discord channel by any chance?

**Comment by Zarenor** [comment]
Hi there.

1. No, Druid does not integrate well with game engines. It's more for standalone applications. There is some progress in integrating as child windows for a VST-type scenario, but no support or plans for sharing a draw surface or overlaying, as you'd need for a game engine.
2. This crate locks you in to it's 'framework' in that it doesn't have support for sharing the window handles, really. You can access the raw handles, but that's generally 'breaking out of the sandbox' and so isn't a case we're looking to directly support.
3. There is not a discord channel. However, we have a fairly active [Zulip instance](xi.zulipchat.com), shared with a few other linebender projects. Questions and thoughts are welcome there!

**Comment by Raj2032** [comment]
@Zarenor Hey mate

> No, Druid does not integrate well with game engines. It's more for standalone applications. There is some progress in integrating as child windows for a VST-type scenario, but no support or plans for sharing a draw surface or overlaying, as you'd need for a game engine.

I see thanks mate :)

> This crate locks you in to it's 'framework' in that it doesn't have support for sharing the window handles, really. You can access the raw handles, but that's generally 'breaking out of the sandbox' and so isn't a case we're looking to directly support.

Ah right mate.

> There is not a discord channel. However, we have a fairly active [Zulip instance](https://github.com/linebender/druid/issues/xi.zulipchat.com), shared with a few other linebender projects. Questions and thoughts are welcome there!

Thanks for the link mate I will post stuff over there if I have future questions :)
