### ISSUE TITLE
Is is really native rust?

### ISSUE THREAD

**Issue by acz2022** [linebender/druid#2182]
Hi,
How can druid claim to be "Rust-native UI toolkit" if it requires gtk? 
Could somebody explain that?
Thank you

**Comment by raphlinus** [comment]
It is Rust native on the most popular platforms, and there are (still experimental) X11 and Wayland back-ends that do not require GTK.

**Comment by acz2022** [comment]
I try to understand the "native" notion. I work on Ubuntu, most people would agree that it is a popular platform. Can I use druid without having gtk installed and do regular gui with it?

**Comment by Maan2003** [comment]
> Can I use druid without having gtk installed and do regular gui with it?

you can try Wayland and X11 backends (`--no-default-features --features x11`). 

There is more discussion in #1956

**Comment by acz2022** [comment]
@Maan2003 But those are still experimental as @raphlinus mentioned, so in theory yes druid had native support, in practice no, druid doesn't provide native support. Native support in druid is experimental.

**Comment by Maan2003** [comment]
IMO, "Rust-native" is the public API feeling like it is made for Rust. 

So, I consider Druid to be Rust-native even if it uses gtk for windowing. This is same as Rust's standard library being Rust-native even though it depends on libc on linux.

**Comment by acz2022** [comment]
Mehh... In that case we are talking about wrapper...
OK, thanks for clarification.
