### ISSUE TITLE
`mouseDragged` event shoud call `mouse_move` with `MouseButton::Left`

### ISSUE THREAD

**Issue by gfreezy** [linebender/druid#2192]
https://github.com/linebender/druid/blob/6c72829df66f0cfb602ab5f481326032f219bb16/druid-shell/src/backend/mac/window.rs#L422

https://github.com/linebender/druid/blob/6c72829df66f0cfb602ab5f481326032f219bb16/druid-shell/src/backend/mac/window.rs#L737-L744

**Comment by raphlinus** [comment]
I don't think so. The `button` field is for buttons that are changing their pressed status, which is not true for drag gestures. The client should be looking at the `buttons` field to see which button(s) are pressed during the drag.
