### ISSUE TITLE
How to open file dialog to save or choose file

### ISSUE THREAD

**Issue by pubg-hacks** [linebender/druid#2194]
I'm new to druid and wanted to open a file dialog to choose or save file but I can't figure how. I think this method  should  do it: https://docs.rs/druid/0.6.0/druid/struct.WindowHandle.html#method.open_file_sync
But I don't  know how to obtain  a WindowHandle to open a dialog with ?

**Comment by raphlinus** [comment]
Take a look at https://github.com/linebender/druid/blob/master/druid/examples/open_save.rs
