### ISSUE TITLE
scroll bars should have larger minimum size

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#223]
Currently scrollbars can be _very_ small. They should have some minimum size, especially once they are interactive. I would take a look at some existing gui toolkits for guidance picking those sizes.

<img width="612" alt="Screen Shot 2019-10-23 at 11 16 38 AM" src="https://user-images.githubusercontent.com/3330916/67408312-ca4d5800-f586-11e9-9508-ae0676a192ff.png">

**Comment by ForLoveOfCats** [comment]
Fixed in https://github.com/linebender/druid/pull/688
