### ISSUE TITLE
Question: Keyboard events

### ISSUE THREAD

**Issue by dominikwilkowski** [linebender/druid#2232]
Is there a way to listen to keyboard events at all?
When the window is in focus of course.

**Comment by xStrom** [comment]
There's [`Event::KeyUp`](https://docs.rs/druid/0.7.0/druid/enum.Event.html#variant.KeyUp) for example. You'll also need to get *focus* which is a Druid specific term meaning that a widget receives key events. The [`is_focused`](https://docs.rs/druid/0.7.0/druid/struct.EventCtx.html#method.is_focused) method docs are a good starting place.

**Comment by dominikwilkowski** [comment]
Oh this is great @xStrom thank you. I'd love to see a more evolved example in the examples sometime soon but this should do for now.
