### ISSUE TITLE
Subwindow on Windows may causes memory leak

### ISSUE THREAD

**Issue by Steve-xmh** [linebender/druid#2234]
To reproduce this, run the `sub_window` example repeat open-and-close windows as much as you can.

Even I put it here for a while the memory usage still no going down.

![image](https://user-images.githubusercontent.com/39523898/180968971-1a2bc775-c1de-4c93-8783-d85af64c2025.png)

Video example (I close these sub-window by Alt-F4):

https://user-images.githubusercontent.com/39523898/180968560-db285a35-848e-480d-ace9-ed15ccd5351f.mp4

**Comment by Maan2003** [comment]
duplicate of #2001 ?

**Comment by Steve-xmh** [comment]
> duplicate of #2001 ?

It also happended at other versions of Windows.

**Comment by Maan2003** [comment]
> It also happened at other versions of Windows.

that is just incorrect title

**Comment by Steve-xmh** [comment]
> > It also happened at other versions of Windows.
> 
> that is just incorrect title(now fixed)

Oh okey, I will close this.
