### ISSUE TITLE
Publish `druid-shell` again?

### ISSUE THREAD

**Issue by kud1ing** [linebender/druid#2236]
The published druid-shell 0.7.0 depends on the one year old piet 0.3.2.
This lacks some niceties like Default implementations and export of `StrokeDash`.

https://crates.io/crates/druid-shell/0.7.0/dependencies

**Comment by xStrom** [comment]
Yes, this will happen soon™, among other reasons we're waiting for [piet 0.6.0](https://github.com/linebender/piet/pull/518) which should arrive even sooner.

**Comment by kud1ing** [comment]
Piet 0.6.0 seems to have been released now.

**Comment by jneem** [comment]
Yes, I'm working on it...

**Comment by kud1ing** [comment]
Thanks a lot.
