### ISSUE TITLE
Failed Examples Build

### ISSUE THREAD

**Issue by netlander** [linebender/druid#2242]
Really like this library but having problem running the examples, after running `cargo run --example anim` here's the failed build output:

```
   Compiling anyhow v1.0.60
   Compiling remove_dir_all v0.5.3
   Compiling open v1.7.1
   Compiling piet-direct2d v0.5.0
   Compiling rand v0.7.3
   Compiling tracing-subscriber v0.3.15
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\yasseen\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.60\src\lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `anyhow` due to previous error
warning: build failed, waiting for other jobs to finish...
```

Looks like a dependency issue, any ideas on how to proceed from here?
Thanks

**Comment by jneem** [comment]
Funny, I had the same issue today (but on a different crate). `cargo clean` solved it for me...

**Comment by netlander** [comment]
I've seen this `cargo clean` command come up as a solution to a lot of build problems, should try using it more often..
Thanks for the answer!
