### ISSUE TITLE
Hotkeys with different language layouts

### ISSUE THREAD

**Issue by megaredb** [linebender/druid#2257]
Hello! I created my own implementation of the Hotkey. The current Druid Hotkey cannot handle different language layouts, so I created my own. I know the code is not perfect, but it works. Do I need to create a Pull Request, or is that not required at this time?

https://gist.github.com/megaredb/ceea8eaec665e41f26e4b7027b2933b6

Example usage:

```rust
fn fallback_do_builtin_command(
      &mut self,
      ctx: &mut EventCtx,
      key: &KeyEvent
) -> Option<Command> {
      use commands as sys;
      let our_id = ctx.widget_id();

      match key {
          key if HotKey::new(Mods::Cmd, Code::KeyC, KeyState::Down).matches(key) => {
              Some(sys::COPY.to(our_id))
          }
          ^^^
          ...
      }
```

**Comment by xStrom** [comment]
Pull requests with improvements are always welcome. I think the hotkey code is actually rather robust, so you would need to also give a specific example of a situation where the current code fails.
