### ISSUE TITLE
Scroll bug when using ZStack

### ISSUE THREAD

**Issue by xarvic** [linebender/druid#2258]
When using a `ZStack` inside a `Scroll` you can't scroll when the `ZStack` is hot.

Example:
```rust
use druid::{Color, Widget, RenderContext, WindowDesc, AppLauncher, WidgetExt, UnitPoint};
use druid::widget::{CrossAxisAlignment, Flex, Label, Painter, Scroll, SizedBox, ZStack};

fn main() {
    let window = WindowDesc::new(build_ui());

    AppLauncher::with_window(window)
        .log_to_console()
        .launch(())
        .unwrap();
}

fn build_ui() -> impl Widget<()> {
    let mut container = Flex::column()
        .cross_axis_alignment(CrossAxisAlignment::Fill);

    for _ in 0..10 {
        container.add_child(SizedBox::empty().height(200.0));
        container.add_child(
            ZStack::new(
                Label::new("Base layer")
                    .align_vertical(UnitPoint::TOP)
                    .expand_width()
                    .fix_height(200.0)
                    .background(Color::grey8(20))
                )
                .with_centered_child(
                    Label::new("Overlay")
                        .center()
                        .fix_height(100.0)
                        .background(Color::grey8(0))
                )
        );
    }

    Scroll::new(container)
        .vertical()
}
```

This happens because `ZStack` uses `ctx.set_handled()` to indicate to a widget that the position the cursor is on is overlapped by another widget. Therefore `Scroll` thinks one of its children already used the `MouseWheel` event and does not scroll.

**Comment by xarvic** [comment]
@jneem, do you think it would be fine to use the obstructed flag instead? It should fix the bug since the obstructed flag is only propagated up and not down the tree.

**Comment by xarvic** [comment]
I think part of the problem is that MouseEvents and `ctx.set_handled()` don't do interact well in general. `ctx.set_handled()` treats all events detached from one another, but `MouseMove` and `MouseUp` events after a `MouseDown` event should be handled by the same widget which handled the `MouseDown`. Calling `set_handled()` for them in another widget does not make sense.

> ah, it was for updating the hot state, right? Maybe there could be a different mechanism for saying "your subtree is no longer hot,"

It is not just to update the hot state. For an example a `Slider` inside a `ZStack` needs to receive those `MouseMove` events to work properly. 

I see two options to solve this:
- We could remove the [special handling](https://github.com/linebender/druid/blob/79eb7749c96550fe16e4ef36e212f4275af3977e/druid/src/core.rs#L672) in `WidgetPod::event` for `MouseDown` and `Wheel` events. Therefore only keeping it for "follow up events". 
- Or we introduce the obstructed flag

Introducing overlapping widgets makes druid probably more complex in any case. I like the obstructed flag more because i think it is more straightforward to use. Using the `set_handled()` mechanism for this feels like a hack and is based on some assumptions how druid is getting used. The obstructed flag on the other hand is its own feature having it separate is more to remember, but my feeling is that we would have less edge cases like this one when using it.

**Comment by jneem** [comment]
> but MouseMove and MouseUp events after a MouseDown event should be handled by the same widget which handled the MouseDown

I thought this was the motivation behind `set_active`, which you can call during `MouseDown` in order to ensure that you get the rest of the events. Or is the problem that `set_active` and `set_handled` don't work well together?

> For an example a Slider inside a ZStack needs to receive those MouseMove events to work properly.

Can you explain this to me? If the Slider is on top, it should already be getting them right? And if the Slider is not on top, then why would I want it to receive those events? I would expect them to just get sent to the widget on top...

Sorry to be slow here, I just want to better understand the options. As far as I can tell, we currently have (at least) 4 ways of controlling event propagation:

- keyboard focus (restricted to keyboard events)
- `set_handled`, for suppressing certain events
- `set_active`, for (whatever the opposite of "suppressing" is) certain events
- having the parent widget just decide to send events to some children but not to others.

So I guess what I want to understand is: what event propagation pattern do we want to express that cannot be expressed with these ingredients?

**Comment by jneem** [comment]
> In case the Slider is visible and active it should still receive those events. Otherwise if you press the slider Knob and drag the cursor over the widget on top, the slider would stop to react the the mouse move.

Just to be sure we're talking about the same thing, are you referring to a situation like this picture?
![bitmap](https://user-images.githubusercontent.com/1448113/190871931-b7df6eb0-e06a-4aa1-8f2c-ba3bf96c4e7f.png)

where the slider is in green, and some other widget in red is obstructing it. Someone clicks on the X, and then drags the mouse in the direction of the arrow. And even though the mouse is over the red widget, we still want the green widget to receive the mouse events, right?

If so, I think it is exactly what `set_active` is for: the green widget should call `set_active` when the mouse is pressed, and the parent should use that active flag to indicate that the green widget should get those events even though it's obstructed.

**Comment by xarvic** [comment]
> Just to be sure we're talking about the same thing, are you referring to a situation like this picture? where the slider is in green, and some other widget in red is obstructing it. Someone clicks on the X, and then drags the mouse in the direction of the arrow. And even though the mouse is over the red widget, we still want the green widget to receive the mouse events, right? 

Yes that is a good example.

> If so, I think it is exactly what set_active is for: the green widget should call set_active when the mouse is pressed, and the parent should use that active flag to indicate that the green widget should get those events even though it's obstructed.

What happens if the parent receives a `MouseUp` event while the cursor is still on the red widget? The parent has to send the `MouseUp` event to the green widget. Otherwise the slider would continue to move afterwards. On the other hand, the green widget could also be a button. In this case the parent needs a way to indicate to the widget that it can't react to the `MouseUp`.
Therefore zstack has to use `set_handled()` but only if one of its children is `active`. For the `MouseDown` -> `MouseMove` -> `MouseUp` cycle this should work. I am not sure if this should also apply to the `Wheel` event, the current bug is solved either way.

It still feels like a hack to use `set_handled()` in two completely different ways depending on the `active` state of a widget but i think it will work so im ok with doing it that way :)

**Comment by jneem** [comment]
> What happens if the parent receives a `MouseUp` event while the cursor is still on the red widget? The parent has to send the `MouseUp` event to the green widget. Otherwise the slider would continue to move afterwards. On the other hand, the green widget could also be a button. In this case the parent needs a way to indicate to the widget that it can't react to the `MouseUp`.

Something like this is already handled by `Button` (or, to be more precise, the `Click` wrapper). Suppose the user presses `MouseDown` on the button, then moves the mouse outside the button, and then there is a `MouseUp` while the mouse is still outside the button. In this case, the button gets the `MouseUp` (because it called `set_active`) but sees that it is not hot and so does not trigger a click. Note that `set_handled` is not involved at all.

Couldn't the same work for a button that is partly obstructed? I'd expect that the green widget is not "hot" while the mouse is over the red widget.

**Comment by xarvic** [comment]
I made a PR based on your suggestion to use a combination of `ctx.is_active()` and `ctx.set_handled()` to route the events correctly and set the hot state. This covers most of the issue.

The only thing left to decide is whether `Event::Wheel` is a follow up event. On the one hand it also interacts with the hot state of the widget and needs to be aware of the obstructed state of the widget, but on the other hand `Event::Wheel` events don't need to be consumed by the widget which called `ctx.set_active()`.

And another thought about `set_handled()` vs `obstructed`. Using `set_handled()` instead of `obstructed` 
works since we only need `obstructed` for follow up events, where we ignore the `ctx.set_handled()` state. But they have a different scope, which was the cause for the original bug. `obstructed` only affects the children for the widget which sets this flag, since it is a field of `MouseEvent`. ctx.set_handled() on the other hand affects all widgets which react to this event after it was called, including the `Scroll` widget which saw that the Wheel event was already used by another widget. 

The bug is resolved since `ZStack` only calls `set_handled()` if one of its children is active, but that means it still happens when you press the mouse and try to scroll. 

All in all i think both version work well enough for this.
