### ISSUE TITLE
Druid Image Loading Example does not work. 

### ISSUE THREAD

**Issue by RylanYancey** [linebender/druid#2261]
![image](https://user-images.githubusercontent.com/76256852/191375451-5fc3270a-2f71-4765-ab98-247127bf7e82.png)

I'm getting this error on this lines of code in Image.rs example:

```rs
fn build_widget(state: &AppState) -> Box<dyn Widget<AppState>> {
    let png_data = ImageBuf::from_data(include_bytes!("./assets/PicWithAlpha.png")).unwrap(); // <- error here
```

It seems Piet no longer supports creating images in this manner? I'm using the latest Github version.

**Comment by graymind75** [comment]
Hi, You have to import `image, png` features. in `cargo.toml`:

```
druid = { version = "0.7.0", features = ["image", "png"] }
```
