### ISSUE TITLE
Drag & Drop interfaces in Druid

### ISSUE THREAD

**Issue by RylanYancey** [linebender/druid#2262]
Hi, I'm trying to find a good framework for creating a drag and drop interface to build neural network models entirely within a GUI. Is it possible to do this in Druid?  I'll need to be able to click and drag a  "Module" (a widget I'd implement myself), create connections between modules, and zoom in and out.

**Comment by xStrom** [comment]
Yes it is possible, however right now you have to implement the drag-n-drop yourself based on mouse events. I have done it in my own apps and it is rather straightforward.
