### ISSUE TITLE
Support `xdg-desktop-portal` on Linux.

### ISSUE THREAD

**Issue by ImperatorStorm** [linebender/druid#2269]
Currently, `druid`, as best I can tell, doesn't support the [`xdg-desktop-portal`](https://github.com/flatpak/xdg-desktop-portal) [specification](https://flatpak.github.io/xdg-desktop-portal/), causing non-GNOME users to see this mess of a filechooser that likely doesn't conform to their desktop environment: ![GTK filechooser on Plasma](https://user-images.githubusercontent.com/30777770/168449243-368f2caa-3c3f-4c51-84e7-d09c389c4315.png)

Programs that do support the specification(e.g. Firefox+derivatives) instead provide a file chooser provided by their desktop environment. For example, Plasma provides this:
![Plasma filechooser](https://user-images.githubusercontent.com/30777770/168449316-33dcd343-a8e5-4e9b-96dd-157036a044dc.png)

**Comment by Maan2003** [comment]
We are using `GtkFIleChooserNative`, so it should use portals if available. are you setting `GTK_USE_PORTAL=1` environment var.

**Comment by ImperatorStorm** [comment]
> We are using `GtkFIleChooserNative`, so it should use portals if available. are you setting `GTK_USE_PORTAL=1` environment var.

Yes, I have it set in `.zshenv` and that works for applications that support portals. It might be that Lapce doesn't support it on their end, so I'll close this and open an issue in their repo.
