### ISSUE TITLE
Mouse move events do not work properly on macOS13.

### ISSUE THREAD

**Issue by Cupnfish** [linebender/druid#2280]
Mouse move events do not work properly on macOS13

**Comment by Cupnfish** [comment]
In addition, the mouse dragging event works properly.

**Comment by liias** [comment]
Same for me. E.g `HotChanged` lifecycle event is not fired at all.

**Comment by liias** [comment]
I think I found a fix. You need to move `view.addTrackingArea` from `make_view` after `view.initWithFrame_` is called.
macOS docs does not specify it as mandatory, but [says](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/TrackingAreaObjects/TrackingAreaObjects.html):

> You can create an NSTrackingArea instance and add it to a view at any point because successful creation does not depend on the view being added to a window. Listing 6-1 shows the creation and addition of an NSTrackingArea instance in a custom view’s [initWithFrame:] method;

I have example hotfix at
https://github.com/Browsers-software/druid/commit/c248c63aabd7339ea77ab004e6e7d681a1ed9695

**Comment by raphlinus** [comment]
Sounds good. I don't have access to a 13 box here. @liias would you be willing to PR that?

**Comment by liias** [comment]
Sure! Will do a PR, and some discussion can happen there.
