### ISSUE TITLE
Fix documentation of automatic focus in LifeCycle events

### ISSUE THREAD

**Issue by sprocklem** [linebender/druid#2318]
Currently, the documentation tells users to to call `LifeCycleCtx::register_for_focus()` in the documentation for both `LifeCycle::WidgetAdded` (as in version 0.7) and the new `LifeCycle::BuildFocusChain`. I believe that the relevant section in the former simply needs to be deleted.

I can submit a pull request for this when I have time later today, if need be.

**Comment by sprocklem** [comment]
Also, there is a spelling error in the latter ("witch" should be "which").

**Comment by xStrom** [comment]
There are some doc changes in #2301, but at a quick glance doesn't look like it addresses this. Might be worth taking a look at that to confirm.

If you think the docs are wrong then a pull request would definitely be welcome.
