### ISSUE TITLE
Extremely inconsistent click-drag behaviour

### ISSUE THREAD

**Issue by cbondurant** [linebender/druid#2344]
I was testing the modal window example, and found that clicking and dragging was extremely inconsistent in a very strange way.
[Example](https://user-images.githubusercontent.com/12928246/214763953-978ba3ed-2096-4299-8b98-857255c86bd5.webm)

I have actually had similar behavior to this while attempting to work on a general graphics canvas widget for my project [Lipuma](https://sr.ht/~cbondurant/Lipuma/). At the time I thought it was due to a misunderstanding of mine but now it seems that it might be deeper than that. 

In terms of platform I have currently tested this using i3 as my window manager on X11. It's late as I'm writing this, and I will double check this with KDE Plasma tomorrow morning.

**Comment by cbondurant** [comment]
I just confirmed that the same behavior occurs under cinnamon and KDE Plasma.

**Comment by cbondurant** [comment]
I have identified the problem: The debug output used to print out all of the move events was causing handling the event to take so long that the event loop was failing to keep up.

This doesn't explain the jitter I've been dealing with in Lipuma, but before this incident I had assumed it was my code anyways.
Closing as user error.

**Comment by jneem** [comment]
I think maybe we should change the example... it's demonstrating how to set the child position programmatically, but this definitely isn't the *right* way to have a moveable child window.
