### ISSUE TITLE
Option::Unwrap on a None value layout.rs:228:34

### ISSUE THREAD

**Issue by jantb** [linebender/druid#2361]
Hello, I am getting the above error message on https://github.com/linebender/druid/blob/bae9c18ac6396cc1ad4e54033dee7971c2edcb65/druid/src/text/layout.rs#L228

I am not sure what is causing it, but it happens when i try to render RichText in a label on windows, I can't replicate the error on mac, maybe due to testing data. This happens on the master branch and on the 0.8.2 release.

**Comment by xStrom** [comment]
Do you have some (preferably minimal) example code that replicates this?

**Comment by jantb** [comment]
Closing the issue until I can provide a short example or figure out what is wrong.
