### ISSUE TITLE
Add tests to Lens derive macro

### ISSUE THREAD

**Issue by futurepaul** [linebender/druid#250]
Will be especially helpful for future expansions to Lens (#213).

**Comment by cmyr** [comment]
If we want to get really professional, there is an excellent overview of macro testing in [dtolonay's proc-macro-workshop](https://github.com/dtolnay/proc-macro-workshop#test-harness) repo.

In particular, it talks about basically property testing compilation failures to ensure error messages stay useful.

**Comment by PoignardAzur** [comment]
Is this still relevant?

If it is, I might take a stab at it. I need to look at dtolnay's workshop anyway for Panoramix macros.

**Comment by cmyr** [comment]
I think this is something we might want eventually, but it is not high priority.
