### ISSUE TITLE
Add cross-platform IME support to druid-shell

### ISSUE THREAD

**Issue by futurepaul** [linebender/druid#267]
As mentioned in #16, IME support is an important feature for druid, and a first step will be to add a cross-platform IME abstraction to druid-shell.

There are some good visuals and an explanation of what an IME (Input Method Editor) is [in this blog post](https://lord.io/blog/2019/text-editing-hates-you-too/).

![editing_6](https://user-images.githubusercontent.com/543668/68322320-1664c600-0078-11ea-952f-f8f199a2d4b7.png)

Both [Makepad](https://github.com/makepad/makepad) and [winit](https://github.com/rust-windowing/winit) have some amount of cross-platform IME code we might be able to use for reference.

**Comment by Finnerale** [comment]
Linked to #1040.

**Comment by black7375** [comment]
https://github.com/Riey/kime
It still supports only English and Korean (+ emoji, math) but is actively developing using Rust.

**Comment by cmyr** [comment]
The IME API and mac implementation were added in #1619, and we can use #1308 as the tracking issue for other backends.
