### ISSUE TITLE
standardize child/inner naming in widgets

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#269]
@zaynetro was asking about this earlier: if a widget contains another widget, what should the name of the variable pointing to the contained widget be? Currently we use `inner` in some places and `child` in other places.

I think we should pick one and stick with it; I personally vote for `child`, which I find slightly more descriptive.

**Comment by PoignardAzur** [comment]
Probably still relevant. I'm putting it on my todo-list.

**Comment by Maan2003** [comment]
I also vote for `child`.
