### ISSUE TITLE
tab view widget

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#364]
This should be a standard tab view, where each tab corresponds to a different root widget. Ultimately this should support dragging to rearrange, closing tags, and other additional features.

this is definitely something we'll get to eventually, but if someone is interested in a project it could be fun; mentorship is available.

**Comment by mendelt** [comment]
Is anyone working on this? I'd like to give it a try and this seems to be something I can really sink my teeth into. I will be leaning druid though so this might take me some time. If anyone else is itching to pick this up I can find another issue to pick up.

**Comment by cmyr** [comment]
it's all yours. :)

**Comment by rjwittams** [comment]
I've got one here : https://github.com/rjwittams/druid/blob/binding-scroll/druid/src/widget/tabs.rs
