### ISSUE TITLE
Consider moving Lens to a new crate

### ISSUE THREAD

**Issue by Ploppz** [linebender/druid#392]
The whole `lens.rs` file is very useful and I want to use it in my own project (except for example `impl Widget for Lens` etc).
Consider making a new `lens` crate. The name `lens` is taken but I would contact the person holding it and ask.

**Comment by Ralith** [comment]
Note that lenses in Rust are pretty much a research area right now, and the approach that makes sense for druid (e.g. only exposing references) may not make sense for other people, which a general-purpose library might be more obliged to support.

**Comment by cmyr** [comment]
Certainly something we could consider at some point. One downside is that we would have to separate out the derive implementations, currently data and lens derive are in the same place.
