### ISSUE TITLE
Update lens module documentation to also document deriving Lens

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#431]
The best place to look for examples of how to use lens is in `lens.rs`, but these examples don't mention `derive(Lens)`. In particular, reading these docs might suggest someone should use the `lens!` macro when `Type::field` syntax would be easier.

It might also be worth mentioning the `WidgetTrait::lens` method in here, although that is less important? That can be communicated in examples.

**Comment by PoignardAzur** [comment]
The Lens documentation is missing on several points. I'm adding it to my list.
