### ISSUE TITLE
add a PaintBrush type

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#526]
I'm reminded by #523 of something we'd talked about a little while ago, and might as well have an issue for. There is currently a `PaintBrush` type in piet, which is a way of representing disparate different things that act like colors; the idea is that we can treat colors or gradients equivalently for the sake of our API.

@futurepaul brought up a good point, which is that it would be nice if we could treat env/theme keys as colors, where appropriate, so that you could write,

```rust
let my_widget = TextBox::raw().padding(5.0).background(theme::BACKGROUND_LIGHT);
```

And then have your color be determined by the value of that key at runtime.

I think we can do this, and I think it's pretty simple. I propose that we add a type to druid, also called `PaintBrush`, which should look like this:

```rust
pub enum PaintBrush {
    Concrete(piet::PaintBrush),
    Key(Key<Color>),
    // other variants possible
}
```

And then we should be able to take one of these types, pass it an `Env`, and get something we can actually paint, like:

```rust
impl PaintBrush {
    fn resolve(&self, env: &Env) -> piet::PaintBrush { ... }
}
```

The idea is that a method like `Container::background` would take as its argument `impl Into<PaintBrush>`, and so you could then pass it *either* an actual color/gradient or a key that could be resolved to a color/gradient at runtime.

This isn't too tricky, but it does require some understanding of the type system and of how `Env` works, but not much more than that.

**Comment by futurepaul** [comment]
I have this working for `Key<Color>`, having a lifetime issue with `Key<LinearGradient>`

**Comment by cmyr** [comment]
push a branch and we can take a look?

**Comment by PoignardAzur** [comment]
With #592 merged, is this still relevant? KeyOrValue is ubiquitous in the codebase now.
