### ISSUE TITLE
Failure to deliver mouse events outside of the window (win)

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#558]
This is the same issue as #541, but on in the windows backend.

> Druid expects to receive a mouse move event when the mouse moves outside of the window.
> 

> 
> It is not necessary that we receive all events outside the window, but it is pretty important that we receive at least one. On platforms that have mouse entered/exited notifications, it would be acceptable to handle that on the platform and send mouse_moved to druid-shell then.

**Comment by PoignardAzur** [comment]
Is this still relevant?

**Comment by cmyr** [comment]
unclear. I do not recall fixing it.

**Comment by xStrom** [comment]
This was working in April 2020 already, as evidenced by #828. For completeness I verified it just now and it is still working.
