### ISSUE TITLE
Add to 7GUIs

### ISSUE THREAD

**Issue by dumblob** [linebender/druid#573]
Druid seems to have traction, so it would make sense to accept the challenge and add it to [7GUIs](https://github.com/eugenkiss/7guis ).

**Comment by futurepaul** [comment]
This is really good goal.

We can absolutely do counter, converter, timer, and circle right now. Flight booker needs drop-down menus (I believe that will be covered by #429), crud needs a selection list (shouldn't be hard?), and I don't really know how to approach cells.

**Comment by dumblob** [comment]
>I don't really know how to approach cells.

Unfortunately I'm still new to druid, but you might get some inspiration from other frameworks already mentioned/linked from the 7GUIs web page and/or repository. See e.g. ["Data API"](https://github.com/fyne-io/fyne/wiki/Data-API ) in Fyne and some valuable discussion/hints about the background ideas: https://github.com/fyne-io/7guis/issues/3 .

Of course, there is also the ["ultimate king of cells implementations"](https://www.red-lang.org/2016/07/native-reactive-spreadsheet-in-17-loc.html ) (nicely [formatted version](https://gist.github.com/dockimbel/b0a413342dc39568696207412a2ef5e7 )) in Red (yeah, just 17 SLOC :open_mouth:), but that's apples & oranges.

**Comment by futurepaul** [comment]
Here's a [zulip topic on the subject](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/deriving.20Data.20for.20Vecs)

**Comment by kud1ing** [comment]
Does this count? https://github.com/MrGibus/Druid-7guis

**Comment by dumblob** [comment]
@kud1ing yes, it does - the only thing missing is a PR in the [7GUIs](https://github.com/eugenkiss/7guis ) repository.

**Comment by dumblob** [comment]
@MrGibus would you mind making the PR?

**Comment by MrGibus** [comment]
> @MrGibus would you mind making the PR?

Already did, just needs merging.

**Comment by kud1ing** [comment]
True: https://github.com/eugenkiss/7guis/pull/45

**Comment by kud1ing** [comment]
Oh: https://github.com/eugenkiss/7guis/issues/57

**Comment by dumblob** [comment]
Thanks a lot! Closing.
