### ISSUE TITLE
Add ctrl support in textbox

### ISSUE THREAD

**Issue by pyroxymat** [linebender/druid#615]
Currently textbox allows selection of text using the shift key and arrow keys to add/remove individual letters to the selection. Ctrl + arrows keys causes you to jump to the front or end.

A common use-case is to use ctrl + shift to select entire words in their entirely. Ctrl + arrow keys to jump through words. Ctrl + backspace to delete word before you (or selection). Ctrl + Delete to delete word behind you (or selection).

**Comment by cmyr** [comment]
So this is slightly complicated: basically, in the long term, we don't want to have all of the actual event handling in textbox; we want to have something like the [`Edit` enum in xi](https://github.com/xi-editor/xi-editor/blob/master/rust/core-lib/src/rpc.rs#L383),  and then we want to have some modular component that maps keyboard events into edit actions in a way that can easily vary per-platform, and be reused by different editable components.

That said, if you wanted to start working on something in this direction you would be welcome to. A good start would be to remove all the direct handling of keyboard events from the textbox (at least those related to text editing) and to move to something that consumes key events and produces edit actions.

I think realistically this should be a trait, something like,

```rust
trait TextInput {
    fn handle_event(&self, event: SomeKeyEvent) -> Option<EditAction>;
}
```

or something. This would let us be very flexible in terms of how we handle keyboard input.

**Comment by Ciantic** [comment]
This is pretty good already, only one thing that didn't work:

- [x] Ctrl+Left jumps word left
- [x] Ctrl+Right jumps word left
- [x] Ctrl+Shift+Left selects word on left
- [x] Ctrl+Shift+Right selects word on right
- [ ] Ctrl+Backspace deletes word on left
- [x] Ctrl+Del deletes word on right

**Comment by Ciantic** [comment]
Now

- [x] <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> deletes word on left
