### ISSUE TITLE
Cross-crate links in the documentation are broken.

### ISSUE THREAD

**Issue by xStrom** [linebender/druid#655]
For example the docs for [druid::LinearGradient](https://docs.rs/druid/0.4.0/druid/struct.LinearGradient.html) link to `FixedLinearGradient` because the docs are from `piet`. However druid doesn't surface `FixedLinearGradient` so the link doesn't work. In other cases the linked item might be surfaced in druid, but in another folder, which would also mean a broken link.

One solution might be to use type based links and let Rust figure it out, however that isn't implemented yet. There's [some documentation for it](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md) and it's tracked in rust-lang/rust#43466.

**Comment by jyn514** [comment]
Small note: this is implemented (and has been for a while), it's just not stable. Since docs.rs builds with nightly, it's possible to use intra-doc links for docs.rs.

**Comment by PoignardAzur** [comment]
Is this still a problem?

**Comment by jyn514** [comment]
Not sure, but intra-doc links are now stable.

**Comment by PoignardAzur** [comment]
I see. I'm adding "use crate path links" to my todo-list.

**Comment by cmyr** [comment]
I believe this is fixed, we're largely migrated to intra-doc links and we test this in CI.
