### ISSUE TITLE
Add an 'Event Viewer' example

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#705]
It would be nice to have this as a general tool, and it would make sense for it to live in `examples`.

This should, at the very least, print out information about keyboard and mouse events. A nice inspiration might be the [w3c key event viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html).

This should have a scrollable list of events, a text box, and some area that accepts mouse clicks.

**Comment by Finnerale** [comment]
Would be a starter for / side effect of #1026.
