### ISSUE TITLE
The MouseLeave event is unrelieable with the GTK shell

### ISSUE THREAD

**Issue by luleyleo** [linebender/druid#852]
Currently `MouseLeave` originates from `drawing_area.connect_leave_notify_event` which does not fire when moving the mouse at normal / fast speed.

A possible solution could be connecting it to the window, which might be more reliable.

For testing this #845 would be useful.

**Comment by PoignardAzur** [comment]
Is this still a problem?

**Comment by jneem** [comment]
I just tested it out using the "glow when hot" thing from #845 and couldn't reproduce the problem.

**Comment by jneem** [comment]
Ah, never mind, I can reproduce this with overlapping windows (got the hint from #927). I still can't find an issue related to mouse speed, though.

**Comment by PoignardAzur** [comment]
Yup, can confirm, the problem still happens with overlapping windows.

**Comment by jneem** [comment]
Turns out this is because we're calling `mouse_move` instead of `mouse_leave` from within the "leave-notify-event" handler. I've fixed this in my PointerEvent branch, so I probably won't do a separate patch.
