### ISSUE TITLE
Rework menus to function more like widgets

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#965]
(a tracking issue for this piece of future work)

Currently managing menus is totally manual; if you want to change a menu you need to create the new one from scratch, and then set it. This was enough to get menus working reasonably well initially, but I'd like to rework this so that menus work more like widgets; they get an `update` event, during which they can inspect the `Data` and modify themselves as needed.

If we wanted to be really fancy, we could do some sort of diffing where instead of rebuilding the whole menu graph from scratch (on the platform) after each change, we only updated what was necessary; but I think we can get away without this optimization for now.

**Comment by xStrom** [comment]
This sounds like a big improvement if we can get it done, because it would remove a whole concept that developers have to learn and instead would piggyback on existing druid concepts.

There's also some potential overlap here with the need for menus for X11. I've been thinking about this and I'm not sure if `druid-shell` is even the place that should implement a menu. To do it properly it would need to import `druid` - for all the mouse hot state tracking, layout, drawing, etc.

Perhaps the solution is to have this new druid menu system that works as similarly to a widget as makes sense. Differences being e.g. that other widgets couldn't overpaint on top of the menu widget for one, but also `Event::WindowSize` shouldn't contain the menu size.

Then this druid menu system would use the platform menu under the hood if the platform provides one. However in the case of a platform like X11 the menu would be fully druid. (*Using features we don't yet have but will need anyway for dropdowns etc.*)

**Comment by sjoshid** [comment]
@cmyr I noticed this issue when I added the debug menu while tracing events [Trace events Zuplip topic](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/Trace.20events).
Would be ok for me to take this up and follow the approach you mentioned in OP?

**Comment by jneem** [comment]
I've been thinking a bit about this, and have some proposals. I want to run through them quickly, because implementing this sounds like a bunch of work, and I don't want to spend too much time on a dead-end.

The tl;dr is that I'm proposing an API with three main improvements over the current one:
- on activation, menu entries trigger a callback (which has access to the data and the env)
- menu entries dynamically determine their text, whether they're selected, and whether they're disabled based on the current data
- menu entries and submenus can be lensed

My proposal doesn't allow for dynamically changing the structure of the menus (i.e. adding/deleting entries). You can still achieve that by rebuilding everything from scratch. This is mainly for implementation simplicity, because handling dynamic menu trees would require copying over a fair amount of complexity from the widget trees (e.g. `children_changed`, `WidgetAdded`, etc.). I also don't *think* it's an important case, because most of the time it's a better experience if menu entries get disabled rather than disappearing.

This proposal also doesn't allow for custom structs implementing a menu trait, like widgets do. I started out that way, but defining menus like that requires a fair amount of boilerplate and doesn't seem to add much power. (Internally, I still plan to have a menu trait, so it's a step in that direction if we want to go there in the future.)

After all that, here's the API I propose:
```rust
impl<T: Data> Menu<T> {
    /// Create an empty menu.
    pub fn empty() -> Menu<T> {
        todo!()
    }

    /// Create a menu with the given name.
    pub fn new(title: LocalizedString<T>) -> Menu<T> {
        todo!()
    }

    /// Append a menu entry to this menu, returning the modified menu.
    pub fn with_entry(self, entry: impl Into<MenuEntry<T>>) -> Self {
        todo!()
    }

    /// Append a menu entry to this menu.
    pub fn append_entry(&mut self, entry: impl Into<MenuEntry<T>>) {
        todo!()
    }

    /// Append a separator to this menu, returning the modified menu.
    pub fn with_separator(self) -> Self {
        todo!()
    }

    /// Append a separator to this menu.
    pub fn append_separator(&mut self) {
        todo!()
    }

    /// Supply a function to check when this menu needs to rebuild itself.
    ///
    /// The arguments to the callback are (in order):
    /// - the previous value of the data,
    /// - the current value of the data, and
    /// - the current value of the environment.
    ///
    /// The callback should return true if the menu needs to rebuild.
    ///
    /// This callback is intended to be purely an optimization. If you do create a menu without
    /// supplying a rebuild callback, the menu will recursively check whether any children have
    /// changed and rebuild itself if any have. By supplying a callback here, you can short-circuit
    /// those recursive calls.
    pub fn needs_rebuild(self, rebuild: impl FnMut(&T, &T, &Env) -> bool) -> Self {
        todo!()
    }

    /// Wraps this menu in a lens, so that it can be added to a `Menu<S>`.
    pub fn lens<S: Data>(self, lens: impl Lens<S, T> + 'static) -> MenuEntry<S> {
        MenuLensWrap {
            lens,
            inner: Box::new(self),
        }
        .into()
    }
}

impl<T: Data> MenuItem<T> {
    /// Create a new menu item with a given name.
    pub fn new(title: LocalizedString<T>) -> MenuItem<T> {
        todo!()
    }

    /// Provide a callback that will be invoked when this menu item is chosen.
    pub fn on_activate(self, on_activate: impl FnMut(&mut MenuEventCtx, &mut T, &Env)) -> Self {
        todo!()
    }

    /// Provide a hotkey for activating this menu item.
    ///
    /// This is equivalent to `self.dynamic_hotkey(|_, _| Some(hotkey))`.
    pub fn hotkey(self, hotkey: HotKey) -> Self {
        todo!()
    }

    /// Provide a dynamic hotkey for activating this menu item.
    ///
    /// The hotkey can change depending on the data.
    pub fn dynamic_hotkey(self, hotkey: impl FnMut(&T, &Env) -> Option<HotKey>) -> Self {
        todo!()
    }

    /// Provide a callback for determining whether this menu item should be enabled.
    ///
    /// Whenever the callback returns `true`, the item will be enabled.
    pub fn enabled(self, enabled: impl FnMut(&T, &Env) -> bool) -> Self {
        todo!()
    }

    /// Provide a callback for determining whether this menu item should be selected.
    ///
    /// Whenever the callback returns `true`, the item will be selected.
    pub fn selected(self, selected: impl FnMut(&T, &Env) -> bool) -> Self {
        todo!()
    }

    /// Wraps this menu item in a lens, so that it can be added to a `Menu<S>`.
    pub fn lens<S: Data>(self, lens: impl Lens<S, T> + 'static) -> MenuEntry<S> {
        MenuLensWrap {
            lens,
            inner: Box::new(self),
        }
        .into()
    }
}

```

**Comment by cmyr** [comment]
So... I've typed up and deleted a bunch of stuff here, and I've also gone and written a bunch of code in an editor, and basically: I think that the solution you describe is the right compromise.

There are a few things I'd like to see, though:

- How does a menu rebuild itself? Is this a mutating method? Is there a separate `MenuBuilder`? 
- For `MenuItem`s, what's the mechanism for updating the underlying state?

    I could imagine a world where we added simple methods to the `druid_shell::Menu` types like `set_enabled`, `set_selected`, etc, and then I could imagine an `update` method on and `MenuItem`, that was only responsible for updating in place. Each `MenuItem` has an identifier corresponding to its backing platform menu, so it shouldn't be too hard for us to make *something* work along the lines of,

    ```rust
    struct MenuItem<T> {
        // title, command, etc:
        is_selected_fn: Box<dyn Fn(&T) -> bool>,
        is_selected: bool,
        platform_id: MenuItemId,
    }

    impl<T> MenuItem<T> {
        fn update(&mut self, ctx: &mut SomeNewCtx, data: &T) {
            if (self.is_selected_fn)(data) != self.is_selected {
                self.is_selected = !self.is_selected;
                ctx.with_platform_menu(self.platform_id, |menu| menu.set_selected(self.is_selected));
            }
        }
    }
    ```
   we could also make this easier by actually giving the `MenuItem` a handle to the underlying platform menu itself, instead of just an identifier.

- What does the code look like, in this world, for setting up a basic application menu?

I'm sure there are other questions too, but these are the things that jump out at me. Overall, though, I think we're on the same page!

**Comment by jneem** [comment]
So I'm not completely sure that this is the right way to go, but I was planning not to change `druid_shell`. (Mainly just to reduce the initial amount of work that has to be implemented on multiple platforms.) Instead, we would check to see if any part of the tree has changed, and if it has then just rebuild the whole menu. This wouldn't be visible in the public API, though, so it could change later. Here is the trait definition that I had planned:

```rust
// This has submit_command
pub struct MenuEventCtx;
// This has add_dropdown, add_item, add_separator
pub struct MenuBuildCtx;

trait MenuTrait<T> {
    /// Called when a menu item is activated.
    ///
    /// `id` is the id of the entry that got activated. If this is different from your id, you are
    /// responsible for routing the activation to your child items.
    fn activate(&mut self, ctx: &MenuEventCtx, id: MenuEntryId, data: &mut T, env: &Env);

    /// Called when the data is changed.
    ///
    /// If this returns `true`, the `build` function will be called.
    fn update(&mut self, old_data: &T, data: &T, env: &Env) -> bool;

    /// Called to rebuild the menu.
    fn build(&mut self, ctx: &MenuBuildCtx, data: &T, env: &Env);
}
```

The basic mechanism for checking whether a rebuild is necessary is just to "resolve" each menu item and check whether it's changed. (But as an optimization you can also use the `needs_rebuild` function on the `Menu` type above.) So I have
```rust
// The resolved state of a menu item.
#[derive(PartialEq)]
struct MenuItemState {
    title: String,
    hotkey: Option<HotKey>, // FIXME: make HotKey partialeq
    selected: bool,
    enabled: bool,
}

pub struct MenuItem<T> {
    id: MenuEntryId,

    title: LabelText<T>,
    callback: Box<dyn FnMut(&mut MenuEventCtx, &mut T, &Env)>,
    hotkey: Option<Box<dyn FnMut(&T, &Env) -> Option<HotKey>>>,
    selected: Option<Box<dyn FnMut(&T, &Env) -> bool>>,
    enabled: Option<Box<dyn FnMut(&T, &Env) -> bool>>,

    // The last resolved state of this menu item. This is basically consists of all the properties
    // above, but "static" versions of them not depending on the data.
    old_state: Option<MenuItemState>,
}
```

The code for building a menu doesn't look a whole lot different than it does now. The main difference is that your callbacks get access to data. So for example:
```rust
fn file_menu() -> Menu<AppState>
    let new = MenuItem::new(
        LocalizedString::new("common-menu-file-new"),
        |ctx, _, _| ctx.submit_command(commands::NEW_FILE),
    )
    .hotkey(SysMods::Cmd, "n");

    let open = MenuItem::new(
        LocalizedString::new("common-menu-file-open"),
        |ctx, _, _| ctx.submit_command(commands::SHOW_OPEN_PANEL)
            .with(FileDialogOptions::new().allowed_types(vec![SCRIBL_FILE_TYPE])),
    )
    .hotkey(SysMods::Cmd, "o");

    let save = MenuItem::new(
        LocalizedString::new("common-menu-file-save"),
        // The unwrap is ok because we're disabled if there isn't a path.
        |ctx, data, _| ctx.submit_command(commands::SAVE_FILE_AS.with(data.save_path.unwrap()))
    )
    .hotkey(SysMods::Cmd, "s")
    .enabled(|data, _| data.save_path.is_some());

    // Obviously this wouldn't go in the file menu, but it demonstrates a dynamic text.
    let undo = MenuItem::new(
        |data, _| format!("Undo {}", data.undo_state.description()),
        |_, data, _| data.pop_undo_state(),
    )
   .hotkey(SysMods::Cmd, "z")
   .enabled(|data, _| !data.undo_state.is_empty());

    MenuDesc::new(LocalizedString::new("common-menu-file-menu"))
        .append(new)
        .append(open)
        .append(save)
        .append(undo)
}
```

**Comment by cmyr** [comment]
Let's say I want to remove the file menu altogether under certain circumstances. Is there a mechanism in this design that allows for this?

**Comment by jneem** [comment]
Thierry Arnoux (don't know his github id) suggested on zulip that there be a `hidden` function analogous to `enabled`. There would also still be the option of calling `ctx.set_menu()` to rebuild them from scratch.

**Comment by cmyr** [comment]
Another option I would suggest is to have a separate `MenuBuilder` that you pass, and which generates your initial menu; then your menu can indicate that it needs to be rebuilt, which means we call the builder again, passing it the current data?

**Comment by jneem** [comment]
Can you elaborate on what `MenuBuilder`'s API would look like? The simplest thing I can imagine would essentially be a `Fn(&Data, &Env) -> MenuDesc`, but I don't see how to easily check for rebuilds. (I mean, you can also include a `Fn(&Data, &Env) -> bool` for checking rebuilds, but I think you really want the rebuild checker to have the same hierarchical structure as the menu itself.)

**Comment by cmyr** [comment]
Yea so my thinking is that the builder is dumb, and only has the method you describe, and it is up to the menu itself to indicate that it needs to be rebuilt. The user wouldn't pass `MenuDesc` around; it would only create a `MenuBuilder`, and then the framework would construct the initial menu, and rebuild the menu subsequently as needed.

**Comment by jneem** [comment]
After a long hiatus, I'm starting to get this going again. The implementation is very much WIP, but at least I can show the public API. This is a re-write of the relevant parts of the multiwin example; note the lack of commands.

```rust
#[allow(unused_assignments)]
fn make_menu(state: &State, _: &Env) -> Menu<State> {
    let mut base = Menu::empty();
    #[cfg(target_os = "macos")]
    {
        base = druid::platform_menus::mac::menu_bar();
    }
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    {
        base.append_entry(druid::platform_menus::win::file::default());
    }
    if state.menu_count != 0 {
        let mut custom = Menu::new(LocalizedString::new("Custom"));

        for i in 1..=state.menu_count {
            custom.append_entry(
                MenuItem::new(
                    LocalizedString::new("hello-counter")
                        .with_arg("count", move |_: &State, _| i.into()),
                )
                .on_activate(move |_ctx, data, _env| data.selected = i)
                .enabled(move |_data, _env| i % 3 != 0)
                .selected(move |data, _env| i == data.selected),
            );
        }
        base.append_entry(custom);
    }
    base.needs_rebuild(|old_data, data, _env| old_data.menu_count != data.menu_count)
}

fn make_context_menu(_state: &State, _env: &Env) -> Menu<State> {
    Menu::empty()
        .with_entry(
            MenuItem::new(LocalizedString::new("Increment"))
                .on_activate(|_ctx, data: &mut State, _env| data.menu_count += 1),
        )
        .with_entry(
            MenuItem::new(LocalizedString::new("Decrement")).on_activate(
                |_ctx, data: &mut State, _env| data.menu_count = data.menu_count.saturating_sub(1),
            ),
        )
        .with_entry(
            MenuItem::new(LocalizedString::new("Glow when hot"))
                .on_activate(|_ctx, data: &mut State, _env| data.glow_hot = !data.glow_hot),
        )
}
```

**Comment by jneem** [comment]
I am a bit stumped about the root menu on mac, though. Is there a way to set it if there are no windows around? Don't we need a `WindowHandle` for that?

**Comment by cmyr** [comment]
Good question. iirc this was part of the motivation for adding an `AppDelegate` in druid; it's a type that persists even if no windows are open, and can at least *receive* commands.

While the druid-shell API hangs menus off of `WindowHandle` there's no reason we couldn't have a mac-only extension that lets you set the menu via some method on the app object, although I'd want to be careful with this; we might want to come up with some mechanism to ensure this only happens when no windows are open?


Also of interest: on mac there's generally a 'Window' menu, which shows information about the currently open windows. In order to populate this correctly, you need to know, when building the menu, what the current window is, and what other windows exist, along with their window Ids; not sure if this is something worth thinking about for you, at this stage?

**Comment by jneem** [comment]
Also, I've discovered an issue with rebuilding the menus on data change: GTK (at least) isn't happy when we swap out a menu that is currently being used. This means that we can't just rebuild the menus whenever we want.

**Comment by Ciantic** [comment]
Btw, I have full menu builder for Windows in my `trayicon-rs` with ability to set icons for items etc:

https://github.com/Ciantic/trayicon-rs

Example of the usage of the menubuilder:

https://github.com/Ciantic/trayicon-rs/blob/master/examples/winit/src/main.rs

**Comment by jneem** [comment]
@Ciantic nice! Do you have support for changing the menu dynamically? That's my current main worry.

@cymr would it be ok on mac to maintain one menu per window *and* a separate global window, and then choose which one to show depending on whether there are windows and which one has focus? So if you call `set_menu` on the app, it will store that as the root menu, but not show it until the windows are all closed.

Related to this, from reading the current code (I can't test it, though) it seems like on mac we display the current window's menu when it gets focus, but if an unfocused window updates its menu then that window's menu will be displayed instead?

**Comment by cmyr** [comment]
@jneem interesting question.

The reality is that, on mac, there really *aren't* window menus; it's just that in druid it's easier for us to pretend that there are, and use the window menus to update the global menu.

I wonder if there's a better way?  Your solution does sound workable, so I'm not opposed..
